from __future__ import annotations
from uuid import UUID
from sqlalchemy import Boolean, CheckConstraint, ForeignKey, Index, Integer, JSON, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column
from app.db.base import Base, TimestampMixin, UUIDPrimaryKeyMixin

class Institution(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__="institutions"; __table_args__=(CheckConstraint("status IN ('applicant','verified','suspended','revoked')",name="ck_institution_status"),UniqueConstraint("organisation_id","slug",name="uq_institution_org_slug"),Index("ix_institution_country_status","country_code","status"))
    organisation_id:Mapped[UUID]=mapped_column(ForeignKey("organisations.id",ondelete="CASCADE"),nullable=False); slug:Mapped[str]=mapped_column(String(120),nullable=False); legal_name:Mapped[str]=mapped_column(String(240),nullable=False); institution_type:Mapped[str]=mapped_column(String(32),nullable=False); country_code:Mapped[str]=mapped_column(String(2),nullable=False); website_url:Mapped[str]=mapped_column(String(500),nullable=False); verification_evidence_sha256:Mapped[str]=mapped_column(String(64),nullable=False); status:Mapped[str]=mapped_column(String(16),nullable=False,default="applicant",server_default="applicant")
class InstitutionAccreditation(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__="institution_accreditations"; __table_args__=(CheckConstraint("status IN ('pending','active','expired','revoked')",name="ck_institution_accreditation_status"),UniqueConstraint("institution_id","accreditation_type","version",name="uq_institution_accreditation_version"))
    institution_id:Mapped[UUID]=mapped_column(ForeignKey("institutions.id",ondelete="CASCADE"),nullable=False); accreditation_type:Mapped[str]=mapped_column(String(40),nullable=False); version:Mapped[str]=mapped_column(String(40),nullable=False); evidence_sha256:Mapped[str]=mapped_column(String(64),nullable=False); reviewer_id:Mapped[UUID|None]=mapped_column(ForeignKey("users.id",ondelete="SET NULL")); expires_in_days:Mapped[int]=mapped_column(Integer,nullable=False); status:Mapped[str]=mapped_column(String(16),nullable=False,default="pending",server_default="pending")
class InstitutionPortal(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__="institution_portals"; __table_args__=(CheckConstraint("status IN ('draft','review','published','suspended','retired')",name="ck_institution_portal_status"),UniqueConstraint("institution_id","slug",name="uq_institution_portal_slug"))
    institution_id:Mapped[UUID]=mapped_column(ForeignKey("institutions.id",ondelete="CASCADE"),nullable=False); slug:Mapped[str]=mapped_column(String(120),nullable=False); locale:Mapped[str]=mapped_column(String(16),nullable=False); domain_url:Mapped[str]=mapped_column(String(500),nullable=False); content_types_json:Mapped[list]=mapped_column(JSON,nullable=False,default=list,server_default="[]"); evidence_only:Mapped[bool]=mapped_column(Boolean,nullable=False,default=True,server_default="true"); status:Mapped[str]=mapped_column(String(16),nullable=False,default="draft",server_default="draft")
class InstitutionGovernanceReview(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__="institution_governance_reviews"; __table_args__=(CheckConstraint("outcome IN ('pending','passed','failed','conditional')",name="ck_institution_governance_review_outcome"),)
    institution_id:Mapped[UUID]=mapped_column(ForeignKey("institutions.id",ondelete="CASCADE"),nullable=False); review_version:Mapped[str]=mapped_column(String(40),nullable=False); outcome:Mapped[str]=mapped_column(String(16),nullable=False,default="pending",server_default="pending"); evidence_sha256:Mapped[str]=mapped_column(String(64),nullable=False); controls_json:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict,server_default="{}")
class RegionalDataPolicy(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__="regional_data_policies"; __table_args__=(UniqueConstraint("organisation_id","region","version",name="uq_regional_data_policy_version"),)
    organisation_id:Mapped[UUID]=mapped_column(ForeignKey("organisations.id",ondelete="CASCADE"),nullable=False); region:Mapped[str]=mapped_column(String(20),nullable=False); version:Mapped[str]=mapped_column(String(40),nullable=False); storage_regions_json:Mapped[list]=mapped_column(JSON,nullable=False,default=list,server_default="[]"); processing_regions_json:Mapped[list]=mapped_column(JSON,nullable=False,default=list,server_default="[]"); cross_border_transfer:Mapped[bool]=mapped_column(Boolean,nullable=False,default=False,server_default="false"); transfer_basis:Mapped[str|None]=mapped_column(String(40)); status:Mapped[str]=mapped_column(String(16),nullable=False,default="draft",server_default="draft")
class LocalizationRelease(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__="localization_releases"; __table_args__=(CheckConstraint("status IN ('draft','review','published','rejected','superseded')",name="ck_localization_release_status"),UniqueConstraint("portal_id","locale","release_version",name="uq_localization_release_version"))
    portal_id:Mapped[UUID]=mapped_column(ForeignKey("institution_portals.id",ondelete="CASCADE"),nullable=False); locale:Mapped[str]=mapped_column(String(16),nullable=False); release_version:Mapped[str]=mapped_column(String(40),nullable=False); source_sha256:Mapped[str]=mapped_column(String(64),nullable=False); translation_sha256:Mapped[str]=mapped_column(String(64),nullable=False); semantic_alignment_score:Mapped[int]=mapped_column(Integer,nullable=False); content_type:Mapped[str]=mapped_column(String(32),nullable=False); native_reviewer_id:Mapped[UUID|None]=mapped_column(ForeignKey("users.id",ondelete="SET NULL")); scholarly_reviewed:Mapped[bool]=mapped_column(Boolean,nullable=False,default=False,server_default="false"); status:Mapped[str]=mapped_column(String(16),nullable=False,default="draft",server_default="draft")
class ResidencyAssessment(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__="residency_assessments"; __table_args__=(CheckConstraint("outcome IN ('pending','passed','failed','conditional')",name="ck_residency_assessment_outcome"),)
    data_policy_id:Mapped[UUID]=mapped_column(ForeignKey("regional_data_policies.id",ondelete="CASCADE"),nullable=False); outcome:Mapped[str]=mapped_column(String(16),nullable=False,default="pending",server_default="pending"); evidence_sha256:Mapped[str]=mapped_column(String(64),nullable=False); findings_json:Mapped[list]=mapped_column(JSON,nullable=False,default=list,server_default="[]")
class RegionalSupportCoverage(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__="regional_support_coverage"; __table_args__=(UniqueConstraint("organisation_id","region",name="uq_regional_support_org_region"),)
    organisation_id:Mapped[UUID]=mapped_column(ForeignKey("organisations.id",ondelete="CASCADE"),nullable=False); region:Mapped[str]=mapped_column(String(20),nullable=False); languages_json:Mapped[list]=mapped_column(JSON,nullable=False,default=list,server_default="[]"); coverage_hours:Mapped[int]=mapped_column(Integer,nullable=False,default=0,server_default="0"); escalation_available:Mapped[bool]=mapped_column(Boolean,nullable=False,default=False,server_default="false")
class PublicTransparencyReport(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__="public_transparency_reports"; __table_args__=(CheckConstraint("status IN ('draft','published','corrected','withdrawn')",name="ck_public_transparency_report_status"),UniqueConstraint("institution_id","report_version",name="uq_public_transparency_report_version"))
    institution_id:Mapped[UUID]=mapped_column(ForeignKey("institutions.id",ondelete="CASCADE"),nullable=False); report_version:Mapped[str]=mapped_column(String(40),nullable=False); fingerprint_sha256:Mapped[str]=mapped_column(String(64),nullable=False); source_coverage_percent:Mapped[int]=mapped_column(Integer,nullable=False); unresolved_high_risk_claims:Mapped[int]=mapped_column(Integer,nullable=False,default=0,server_default="0"); metrics_json:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict,server_default="{}"); status:Mapped[str]=mapped_column(String(16),nullable=False,default="draft",server_default="draft")
class PublicCorrectionCase(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__="public_correction_cases"; __table_args__=(CheckConstraint("severity IN ('low','medium','high','critical')",name="ck_public_correction_case_severity"),CheckConstraint("status IN ('open','review','approved','released','rejected')",name="ck_public_correction_case_status"))
    institution_id:Mapped[UUID]=mapped_column(ForeignKey("institutions.id",ondelete="CASCADE"),nullable=False); severity:Mapped[str]=mapped_column(String(16),nullable=False); status:Mapped[str]=mapped_column(String(16),nullable=False,default="open",server_default="open"); evidence_sha256:Mapped[str]=mapped_column(String(64),nullable=False); affected_content_types_json:Mapped[list]=mapped_column(JSON,nullable=False,default=list,server_default="[]"); summary:Mapped[str]=mapped_column(Text,nullable=False); user_notification_planned:Mapped[bool]=mapped_column(Boolean,nullable=False,default=False,server_default="false")
class PublicTrustIncident(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__="public_trust_incidents"; __table_args__=(CheckConstraint("status IN ('open','contained','resolved','dismissed')",name="ck_public_trust_incident_status"),)
    institution_id:Mapped[UUID]=mapped_column(ForeignKey("institutions.id",ondelete="CASCADE"),nullable=False); severity:Mapped[str]=mapped_column(String(16),nullable=False); status:Mapped[str]=mapped_column(String(16),nullable=False,default="open",server_default="open"); evidence_sha256:Mapped[str]=mapped_column(String(64),nullable=False); public_notice_url:Mapped[str|None]=mapped_column(String(500)); summary:Mapped[str]=mapped_column(Text,nullable=False)
class TransparencyAuditEvent(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__="transparency_audit_events"; __table_args__=(UniqueConstraint("institution_id","sequence_number",name="uq_transparency_audit_sequence"),)
    institution_id:Mapped[UUID]=mapped_column(ForeignKey("institutions.id",ondelete="CASCADE"),nullable=False); sequence_number:Mapped[int]=mapped_column(Integer,nullable=False); event_type:Mapped[str]=mapped_column(String(60),nullable=False); evidence_sha256:Mapped[str]=mapped_column(String(64),nullable=False); previous_sha256:Mapped[str|None]=mapped_column(String(64)); event_sha256:Mapped[str]=mapped_column(String(64),nullable=False); metadata_json:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict,server_default="{}")
class RegionalRolloutReview(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__="regional_rollout_reviews"; __table_args__=(CheckConstraint("outcome IN ('pending','passed','failed','conditional')",name="ck_regional_rollout_review_outcome"),UniqueConstraint("organisation_id","region","review_version",name="uq_regional_rollout_review_version"))
    organisation_id:Mapped[UUID]=mapped_column(ForeignKey("organisations.id",ondelete="CASCADE"),nullable=False); region:Mapped[str]=mapped_column(String(20),nullable=False); review_version:Mapped[str]=mapped_column(String(40),nullable=False); outcome:Mapped[str]=mapped_column(String(16),nullable=False,default="pending",server_default="pending"); portable_ready:Mapped[bool]=mapped_column(Boolean,nullable=False,default=False,server_default="false"); production_ready:Mapped[bool]=mapped_column(Boolean,nullable=False,default=False,server_default="false"); evidence_sha256:Mapped[str]=mapped_column(String(64),nullable=False)
class GlobalLaunchReview(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__="global_launch_reviews"; __table_args__=(CheckConstraint("outcome IN ('pending','passed','failed','conditional')",name="ck_global_launch_review_outcome"),UniqueConstraint("organisation_id","review_version",name="uq_global_launch_review_version"))
    organisation_id:Mapped[UUID]=mapped_column(ForeignKey("organisations.id",ondelete="CASCADE"),nullable=False); review_version:Mapped[str]=mapped_column(String(40),nullable=False); outcome:Mapped[str]=mapped_column(String(16),nullable=False,default="pending",server_default="pending"); portable_ready:Mapped[bool]=mapped_column(Boolean,nullable=False,default=False,server_default="false"); production_ready:Mapped[bool]=mapped_column(Boolean,nullable=False,default=False,server_default="false"); evidence_sha256:Mapped[str]=mapped_column(String(64),nullable=False); controls_json:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict,server_default="{}")
class InstitutionalNetworkAcceptance(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__="institutional_network_acceptances"; __table_args__=(UniqueConstraint("organisation_id","milestone_version",name="uq_institutional_network_acceptance_version"),)
    organisation_id:Mapped[UUID]=mapped_column(ForeignKey("organisations.id",ondelete="CASCADE"),nullable=False); milestone_version:Mapped[str]=mapped_column(String(40),nullable=False); outcome:Mapped[str]=mapped_column(String(16),nullable=False); portable_acceptance:Mapped[bool]=mapped_column(Boolean,nullable=False,default=False,server_default="false"); production_acceptance:Mapped[bool]=mapped_column(Boolean,nullable=False,default=False,server_default="false"); evidence_sha256:Mapped[str]=mapped_column(String(64),nullable=False); notes:Mapped[str|None]=mapped_column(Text)
