from uuid import UUID
from sqlalchemy import Boolean,ForeignKey,Integer,JSON,String,Text,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column
from app.db.base import Base,TimestampMixin,UUIDPrimaryKeyMixin
class PlatformComponent(UUIDPrimaryKeyMixin,TimestampMixin,Base):
 __tablename__='platform_components';__table_args__=(UniqueConstraint('organisation_id','component_slug','version',name='uq_platform_component'),)
 organisation_id:Mapped[UUID]=mapped_column(ForeignKey('organisations.id',ondelete='CASCADE'));component_slug:Mapped[str]=mapped_column(String(120));version:Mapped[str]=mapped_column(String(40));domain_name:Mapped[str]=mapped_column(String(120));artifact_sha256:Mapped[str]=mapped_column(String(64));status:Mapped[str]=mapped_column(String(20),default='draft',server_default='draft')
class IntegrationContract(UUIDPrimaryKeyMixin,TimestampMixin,Base):
 __tablename__='integration_contracts';component_id:Mapped[UUID]=mapped_column(ForeignKey('platform_components.id',ondelete='CASCADE'));contract_name:Mapped[str]=mapped_column(String(160));contract_version:Mapped[str]=mapped_column(String(40));schema_sha256:Mapped[str]=mapped_column(String(64));idempotent:Mapped[bool]=mapped_column(Boolean,default=False,server_default='false')
class CrossDomainVerification(UUIDPrimaryKeyMixin,TimestampMixin,Base):
 __tablename__='cross_domain_verifications';organisation_id:Mapped[UUID]=mapped_column(ForeignKey('organisations.id',ondelete='CASCADE'));verification_type:Mapped[str]=mapped_column(String(80));coverage_percent:Mapped[int]=mapped_column(Integer);critical_failures:Mapped[int]=mapped_column(Integer);evidence_sha256:Mapped[str]=mapped_column(String(64));outcome:Mapped[str]=mapped_column(String(20))
class SecurityPostureReview(UUIDPrimaryKeyMixin,TimestampMixin,Base):
 __tablename__='security_posture_reviews';organisation_id:Mapped[UUID]=mapped_column(ForeignKey('organisations.id',ondelete='CASCADE'));audit_coverage_percent:Mapped[int]=mapped_column(Integer);critical_vulnerabilities:Mapped[int]=mapped_column(Integer);high_vulnerabilities:Mapped[int]=mapped_column(Integer);evidence_sha256:Mapped[str]=mapped_column(String(64));outcome:Mapped[str]=mapped_column(String(20))
class ComplianceControlResult(UUIDPrimaryKeyMixin,TimestampMixin,Base):
 __tablename__='compliance_control_results';review_id:Mapped[UUID]=mapped_column(ForeignKey('security_posture_reviews.id',ondelete='CASCADE'));control_code:Mapped[str]=mapped_column(String(100));framework:Mapped[str]=mapped_column(String(80));passed:Mapped[bool]=mapped_column(Boolean,default=False,server_default='false');evidence_sha256:Mapped[str]=mapped_column(String(64))
class ReleaseCandidate(UUIDPrimaryKeyMixin,TimestampMixin,Base):
 __tablename__='release_candidates';__table_args__=(UniqueConstraint('organisation_id','release_version',name='uq_release_candidate'),)
 organisation_id:Mapped[UUID]=mapped_column(ForeignKey('organisations.id',ondelete='CASCADE'));release_version:Mapped[str]=mapped_column(String(40));migration_head:Mapped[str]=mapped_column(String(40));manifest_sha256:Mapped[str]=mapped_column(String(64));status:Mapped[str]=mapped_column(String(20),default='draft',server_default='draft')
class ReleaseArtifact(UUIDPrimaryKeyMixin,TimestampMixin,Base):
 __tablename__='release_artifacts';release_id:Mapped[UUID]=mapped_column(ForeignKey('release_candidates.id',ondelete='CASCADE'));artifact_name:Mapped[str]=mapped_column(String(180));artifact_type:Mapped[str]=mapped_column(String(60));artifact_sha256:Mapped[str]=mapped_column(String(64));signed:Mapped[bool]=mapped_column(Boolean,default=False,server_default='false')
class SoftwareBillOfMaterials(UUIDPrimaryKeyMixin,TimestampMixin,Base):
 __tablename__='software_bills_of_materials';release_id:Mapped[UUID]=mapped_column(ForeignKey('release_candidates.id',ondelete='CASCADE'));format_name:Mapped[str]=mapped_column(String(40));component_count:Mapped[int]=mapped_column(Integer);document_sha256:Mapped[str]=mapped_column(String(64));verified:Mapped[bool]=mapped_column(Boolean,default=False,server_default='false')
class ObservabilityReadiness(UUIDPrimaryKeyMixin,TimestampMixin,Base):
 __tablename__='observability_readiness';organisation_id:Mapped[UUID]=mapped_column(ForeignKey('organisations.id',ondelete='CASCADE'));service_coverage_percent:Mapped[int]=mapped_column(Integer);metrics_coverage_percent:Mapped[int]=mapped_column(Integer);trace_coverage_percent:Mapped[int]=mapped_column(Integer);runbook_coverage_percent:Mapped[int]=mapped_column(Integer);outcome:Mapped[str]=mapped_column(String(20))
class ServiceLevelObjective(UUIDPrimaryKeyMixin,TimestampMixin,Base):
 __tablename__='service_level_objectives';observability_id:Mapped[UUID]=mapped_column(ForeignKey('observability_readiness.id',ondelete='CASCADE'));service_name:Mapped[str]=mapped_column(String(140));availability_basis_points:Mapped[int]=mapped_column(Integer);latency_ms:Mapped[int]=mapped_column(Integer);error_budget_policy:Mapped[dict]=mapped_column(JSON,default=dict,server_default='{}')
class DisasterRecoveryReview(UUIDPrimaryKeyMixin,TimestampMixin,Base):
 __tablename__='disaster_recovery_reviews';organisation_id:Mapped[UUID]=mapped_column(ForeignKey('organisations.id',ondelete='CASCADE'));rpo_minutes:Mapped[int]=mapped_column(Integer);rto_minutes:Mapped[int]=mapped_column(Integer);last_exercise_days:Mapped[int]=mapped_column(Integer);data_loss_detected:Mapped[bool]=mapped_column(Boolean,default=False,server_default='false');outcome:Mapped[str]=mapped_column(String(20))
class RecoveryExercise(UUIDPrimaryKeyMixin,TimestampMixin,Base):
 __tablename__='recovery_exercises';review_id:Mapped[UUID]=mapped_column(ForeignKey('disaster_recovery_reviews.id',ondelete='CASCADE'));scenario:Mapped[str]=mapped_column(String(180));restore_minutes:Mapped[int]=mapped_column(Integer);failover_passed:Mapped[bool]=mapped_column(Boolean,default=False,server_default='false');failback_passed:Mapped[bool]=mapped_column(Boolean,default=False,server_default='false');evidence_sha256:Mapped[str]=mapped_column(String(64))
class PerformanceBenchmark(UUIDPrimaryKeyMixin,TimestampMixin,Base):
 __tablename__='performance_benchmarks';organisation_id:Mapped[UUID]=mapped_column(ForeignKey('organisations.id',ondelete='CASCADE'));peak_rps:Mapped[int]=mapped_column(Integer);tested_rps:Mapped[int]=mapped_column(Integer);p95_latency_ms:Mapped[int]=mapped_column(Integer);error_rate_basis_points:Mapped[int]=mapped_column(Integer);headroom_percent:Mapped[int]=mapped_column(Integer);outcome:Mapped[str]=mapped_column(String(20))
class ReleaseGovernanceDecision(UUIDPrimaryKeyMixin,TimestampMixin,Base):
 __tablename__='release_governance_decisions';release_id:Mapped[UUID]=mapped_column(ForeignKey('release_candidates.id',ondelete='CASCADE'));decision:Mapped[str]=mapped_column(String(20));owner_reference:Mapped[str]=mapped_column(String(180));rollback_authority_reference:Mapped[str]=mapped_column(String(180));evidence_sha256:Mapped[str]=mapped_column(String(64))
class ProductionValidationRecord(UUIDPrimaryKeyMixin,TimestampMixin,Base):
 __tablename__='production_validation_records';release_id:Mapped[UUID]=mapped_column(ForeignKey('release_candidates.id',ondelete='CASCADE'));validation_type:Mapped[str]=mapped_column(String(80));passed:Mapped[bool]=mapped_column(Boolean,default=False,server_default='false');external_party:Mapped[str|None]=mapped_column(String(180));evidence_sha256:Mapped[str]=mapped_column(String(64))
class PlatformV1Acceptance(UUIDPrimaryKeyMixin,TimestampMixin,Base):
 __tablename__='platform_v1_acceptance';__table_args__=(UniqueConstraint('organisation_id','release_version',name='uq_platform_v1_acceptance'),)
 organisation_id:Mapped[UUID]=mapped_column(ForeignKey('organisations.id',ondelete='CASCADE'));release_version:Mapped[str]=mapped_column(String(40));outcome:Mapped[str]=mapped_column(String(20));portable_ready:Mapped[bool]=mapped_column(Boolean,default=False,server_default='false');production_ready:Mapped[bool]=mapped_column(Boolean,default=False,server_default='false');evidence_sha256:Mapped[str]=mapped_column(String(64));notes:Mapped[str|None]=mapped_column(Text)
