from typing import Annotated
from fastapi import APIRouter, Depends, HTTPException

from app.api.dependencies.auth import get_current_user, require_csrf
from app.api.dependencies.platform_admin import require_platform_administrator
from app.api.dependencies.auth import DbSession
from app.models.identity import Session, User
from app.schemas.retrieval import RetrievalQueryRequest
from app.services.retrieval import ALLOWED_CORPORA, search_evidence

router = APIRouter(prefix="/retrieval", tags=["retrieval"])


@router.post("/query")
async def query_retrieval(payload: RetrievalQueryRequest, db: DbSession, _: Annotated[User, Depends(get_current_user)]):
    corpora = set(payload.corpora)
    if not corpora.issubset(ALLOWED_CORPORA):
        raise HTTPException(status_code=422, detail="unsupported corpus requested")
    evidence = await search_evidence(db, corpora, payload.query, payload.limit)
    return {"policy_version": "retrieval-v1", "insufficient": len(evidence) == 0, "evidence": [
        {"chunk_id": item.chunk_id, "corpus_type": item.corpus_type, "canonical_reference": item.canonical_reference,
         "exact_text": item.exact_text, "text_sha256": item.text_sha256, "source_edition_id": item.source_edition_id,
         "source_passage_id": item.source_passage_id, "attribution": item.attribution, "licence": item.licence}
        for item in evidence
    ]}


@router.post("/admin/projections", status_code=202)
async def start_projection(_: Annotated[User, Depends(require_platform_administrator)], __: Annotated[Session, Depends(require_csrf)]):
    return {"status": "accepted", "policy_version": "retrieval-v1", "note": "projection worker contract registered; no corpus content is generated by this endpoint"}
