from pydantic import BaseModel,Field
class LineageManifestRequest(BaseModel):lineage_slug:str;scholar_ids:list[str]=Field(min_length=1);institution_ids:list[str]=[];evidence_sha256:list[str]=Field(min_length=1)
class ScholarlyLineageRequest(BaseModel):qualified_scholars:int=Field(ge=0);independent_institutions:int=Field(ge=0);teacher_student_links_verified:bool;chronology_consistent:bool;evidence_coverage_percent:int=Field(ge=0,le=100);minority_traditions_preserved:bool;manifest_sha256:str
class TranslationGovernanceRequest(BaseModel):source_language_verified:bool;target_language_reviewers:int=Field(ge=0);independent_reviewers:int=Field(ge=0);terminology_glossary_versioned:bool;semantic_alignment_percent:int=Field(ge=0,le=100);disputed_terms_disclosed:bool;scholarly_approval:bool
class VerifiableCredentialRequest(BaseModel):issuer_verified:bool;subject_verified:bool;credential_schema_versioned:bool;signature_sha256:str;revocation_registry:bool;expires_days:int=Field(ge=0);evidence_linked:bool
class CivilizationalEventRequest(BaseModel):verified_hosts:int=Field(ge=0);jurisdictions:int=Field(ge=0);scholarly_program_reviewed:bool;safeguarding_plan:bool;accessibility_plan:bool;privacy_notice:bool;emergency_plan:bool;recording_consent:bool
class PolicyLifecycleRequest(BaseModel):policy_owner_assigned:bool;consultation_complete:bool;scholarly_review_complete:bool;legal_review_complete:bool;versioned:bool;supersession_defined:bool;review_interval_days:int=Field(ge=0);impact_assessment:bool
class OperationalIntelligenceRequest(BaseModel):metrics_coverage_percent:int=Field(ge=0,le=100);trace_coverage_percent:int=Field(ge=0,le=100);log_integrity:bool;sensitive_data_redacted:bool;forecast_accuracy_percent:int=Field(ge=0,le=100);alert_routes_tested:bool;human_override_available:bool
class ContinuityPlanRequest(BaseModel):successor_stewards:int=Field(ge=0);independent_archive_copies:int=Field(ge=0);credential_escrow_verified:bool;annual_restore_test:bool;knowledge_handover_complete:bool;rpo_minutes:int=Field(ge=0);rto_hours:int=Field(ge=0);external_custodian:bool
class ICOSAcceptanceRequest(BaseModel):lineage_passed:bool;translation_passed:bool;credentials_passed:bool;events_passed:bool;policy_passed:bool;operations_passed:bool;continuity_passed:bool;live_institutional_validation:bool;external_scholarly_audit:bool;live_continuity_exercise:bool
