from pydantic import BaseModel,Field
class TimeProfileManifestRequest(BaseModel):profile_slug:str;method_code:str;authority_ids:list[str]=Field(min_length=1);parameter_sha256:list[str]=Field(min_length=1)
class PrayerTimeGovernanceRequest(BaseModel):verified_authorities:int=Field(ge=0);jurisdictions:int=Field(ge=0);calculation_method_published:bool;high_latitude_rule_defined:bool;location_precision_meters:int=Field(ge=0);astronomical_validation_percent:int=Field(ge=0,le=100);manual_override_audited:bool;manifest_sha256:str
class HijriCalendarReleaseRequest(BaseModel):authority_verified:bool;observation_method_published:bool;calculation_fallback_disclosed:bool;jurisdiction_scope_defined:bool;disagreement_disclosed:bool;release_notice_hours:int=Field(ge=0);evidence_sha256:str
class HalalStandardRequest(BaseModel):scholarly_board_members:int=Field(ge=0);independent_labs:int=Field(ge=0);ingredient_traceability_percent:int=Field(ge=0,le=100);supply_chain_audited:bool;cross_contamination_controls:bool;recall_process:bool;public_standard:bool
class HalalCertificationRequest(BaseModel):certifier_verified:bool;facility_audited:bool;product_scope_defined:bool;certificate_sha256:str;expires_days:int=Field(ge=0);revocation_registry:bool;critical_findings:int=Field(ge=0)
class EthicalCommerceRequest(BaseModel):price_transparency:bool;terms_plain_language:bool;no_deceptive_marketing:bool;labour_due_diligence:bool;environmental_claims_verified:bool;complaints_channel:bool;traceability_percent:int=Field(ge=0,le=100)
class IslamicFinanceProductRequest(BaseModel):shariah_board_members:int=Field(ge=0);independent_reviewers:int=Field(ge=0);contract_structure_disclosed:bool;fees_fully_disclosed:bool;asset_or_service_linked:bool;late_payment_treatment_disclosed:bool;annual_shariah_audit:bool;critical_findings:int=Field(ge=0)
class FamilyServiceRequest(BaseModel):qualified_practitioners:int=Field(ge=0);safeguarding_policy:bool;privacy_controls:bool;informed_consent:bool;domestic_abuse_escalation:bool;child_protection_path:bool;legal_scope_disclosed:bool;scholarly_scope_disclosed:bool
class HeritageStewardshipRequest(BaseModel):ownership_verified:bool;significance_documented:bool;conservation_plan:bool;digital_twin_or_archive:bool;community_consultation:bool;conflict_risk_assessed:bool;public_access_policy:bool;evidence_sha256:str
class IslamicLifeAcceptanceRequest(BaseModel):timekeeping_passed:bool;calendar_passed:bool;halal_passed:bool;commerce_passed:bool;finance_passed:bool;family_passed:bool;heritage_passed:bool;live_authority_validation:bool;external_shariah_audit:bool;live_traceability_exercise:bool
