from pydantic import BaseModel,Field
class ReleaseManifestRequest(BaseModel):release_version:str;component_ids:list[str]=Field(min_length=1);migration_head:str;artifact_sha256:list[str]=Field(min_length=1)
class CrossDomainIntegrationRequest(BaseModel):registered_domains:int=Field(ge=0);required_domains:int=Field(ge=0);contract_coverage_percent:int=Field(ge=0,le=100);cross_domain_foreign_keys_verified:bool;tenant_isolation_verified:bool;event_contracts_versioned:bool;idempotency_coverage_percent:int=Field(ge=0,le=100);critical_integration_failures:int=Field(ge=0)
class SecurityComplianceRequest(BaseModel):auth_controls_passed:bool;tenant_isolation_passed:bool;secrets_encrypted:bool;audit_coverage_percent:int=Field(ge=0,le=100);critical_vulnerabilities:int=Field(ge=0);high_vulnerabilities:int=Field(ge=0);dependency_scan_passed:bool;privacy_review_passed:bool;scholarly_governance_passed:bool
class ReleaseCandidateRequest(BaseModel):build_reproducible:bool;test_pass_percent:int=Field(ge=0,le=100);migration_rendered:bool;rollback_plan_verified:bool;release_notes_complete:bool;artifact_signed:bool;sbom_generated:bool;open_blockers:int=Field(ge=0);manifest_sha256:str
class ObservabilitySLORequest(BaseModel):service_coverage_percent:int=Field(ge=0,le=100);metrics_coverage_percent:int=Field(ge=0,le=100);trace_coverage_percent:int=Field(ge=0,le=100);log_integrity:bool;alert_routes_tested:bool;slo_definitions_complete:bool;error_budget_policy:bool;runbooks_complete_percent:int=Field(ge=0,le=100)
class DisasterRecoveryRequest(BaseModel):backup_verified:bool;restore_tested:bool;rpo_minutes:int=Field(ge=0);rto_minutes:int=Field(ge=0);failover_tested:bool;failback_tested:bool;data_loss_detected:bool;last_exercise_days:int=Field(ge=0)
class PerformanceReadinessRequest(BaseModel):peak_rps:int=Field(ge=0);tested_rps:int=Field(ge=0);p95_latency_ms:int=Field(ge=0);error_rate_basis_points:int=Field(ge=0);headroom_percent:int=Field(ge=0);corpus_records:int=Field(ge=0);load_profile_representative:bool
class ReleaseGovernanceRequest(BaseModel):release_owner_assigned:bool;change_approval_complete:bool;rollback_authority_assigned:bool;maintenance_window_defined:bool;stakeholder_notice_complete:bool;support_handover_complete:bool;go_no_go_recorded:bool
class V1AcceptanceRequest(BaseModel):integration_passed:bool;security_passed:bool;release_candidate_passed:bool;observability_passed:bool;disaster_recovery_passed:bool;performance_passed:bool;governance_passed:bool;live_deployment_validated:bool;external_security_audit:bool;external_scholarly_audit:bool;live_failover_exercise:bool
