package testutil

import (
	"bufio"
	"fmt"
	"net"
	"strings"
	"sync"
	"testing"
)

// FakeSMTPServer implements just enough of the SMTP protocol to accept a
// message from Go's net/smtp.SendMail (used by the mailer package). It is a
// real TCP server speaking the real protocol -- a legitimate test double for
// the external mail relay dependency, not a mock of anything internal to
// GRIDKEEP.
type FakeSMTPServer struct {
	Addr string

	mu       sync.Mutex
	messages []string

	listener net.Listener
}

func StartFakeSMTPServer(t *testing.T) *FakeSMTPServer {
	t.Helper()
	ln, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatalf("start fake smtp server: %v", err)
	}
	s := &FakeSMTPServer{Addr: ln.Addr().String(), listener: ln}

	go s.acceptLoop()
	t.Cleanup(func() { _ = ln.Close() })
	return s
}

func (s *FakeSMTPServer) acceptLoop() {
	for {
		conn, err := s.listener.Accept()
		if err != nil {
			return
		}
		go s.handleConn(conn)
	}
}

func (s *FakeSMTPServer) handleConn(conn net.Conn) {
	defer func() { _ = conn.Close() }()
	r := bufio.NewReader(conn)
	w := bufio.NewWriter(conn)

	write := func(msg string) {
		_, _ = w.WriteString(msg + "\r\n")
		_ = w.Flush()
	}

	write("220 gridkeep-test-smtp ESMTP")

	var body strings.Builder
	inData := false

	for {
		line, err := r.ReadString('\n')
		if err != nil {
			return
		}
		line = strings.TrimRight(line, "\r\n")

		if inData {
			if line == "." {
				inData = false
				s.mu.Lock()
				s.messages = append(s.messages, body.String())
				s.mu.Unlock()
				body.Reset()
				write("250 OK")
				continue
			}
			body.WriteString(line + "\n")
			continue
		}

		upper := strings.ToUpper(line)
		switch {
		case strings.HasPrefix(upper, "EHLO"), strings.HasPrefix(upper, "HELO"):
			write("250 gridkeep-test-smtp")
		case strings.HasPrefix(upper, "MAIL FROM"):
			write("250 OK")
		case strings.HasPrefix(upper, "RCPT TO"):
			write("250 OK")
		case upper == "DATA":
			inData = true
			write("354 End data with <CR><LF>.<CR><LF>")
		case upper == "QUIT":
			write("221 Bye")
			return
		default:
			write("250 OK")
		}
	}
}

// LastMessageContaining returns the most recently received message whose
// body contains substr, and true if one was found.
func (s *FakeSMTPServer) LastMessageContaining(substr string) (string, bool) {
	s.mu.Lock()
	defer s.mu.Unlock()
	for i := len(s.messages) - 1; i >= 0; i-- {
		if strings.Contains(s.messages[i], substr) {
			return s.messages[i], true
		}
	}
	return "", false
}

// ExtractToken pulls the token= query parameter out of the first URL found
// in msg, matching the links generated by the mailer templates
// (.../verify-email?token=..., .../reset-password?token=..., .../invitations/accept?token=...).
func ExtractToken(msg string) (string, error) {
	idx := strings.Index(msg, "token=")
	if idx == -1 {
		return "", fmt.Errorf("no token= parameter found in message")
	}
	rest := msg[idx+len("token="):]
	end := strings.IndexAny(rest, "\r\n \t")
	if end == -1 {
		end = len(rest)
	}
	return rest[:end], nil
}
