"""ExecutiveIntelligence: the orchestration loop from
docs/architecture/01-executive-intelligence.md, implemented at the scope
this codebase can genuinely support today — no fleet of specialist
agents exists yet (docs/agents/README.md is still design-only), so this
does the part that's real: for each goal due for review, ask the Model
Router for the single next concrete step, record that reasoning as a
Decision (answering "why did you make that decision" for real, not by
re-prompting after the fact), and enqueue it as a durable task. It holds
no Policy Engine write access and no ability to expand its own
permissions — consistent with docs/architecture/04-agent-architecture.md.
"""
from __future__ import annotations

from dataclasses import dataclass

from ..memory import MemoryStore
from ..memory.models import Decision
from ..providers import ModelRouter, NoProviderAvailable
from ..tasks import TaskEngine
from .goal_engine import GoalEngine
from .goal_models import Goal


@dataclass
class ReviewOutcome:
    goal_id: str
    decision: Decision | None
    task_id: str | None
    error: str | None = None


class ExecutiveIntelligence:
    def __init__(
        self, goals: GoalEngine, tasks: TaskEngine, memory: MemoryStore, model_router: ModelRouter,
    ) -> None:
        self._goals = goals
        self._tasks = tasks
        self._memory = memory
        self._model_router = model_router

    async def review_goal(self, goal: Goal) -> ReviewOutcome:
        prompt = (
            f"Goal: {goal.statement}\n"
            f"Success metric: {goal.success_metric}\n"
            f"Current progress: {goal.progress:.0%}\n"
            "In one sentence, state the single next concrete step."
        )
        try:
            chunks = [chunk async for chunk in self._model_router.generate_stream(prompt, history=[])]
        except NoProviderAvailable as exc:
            return ReviewOutcome(goal_id=goal.id, decision=None, task_id=None, error=str(exc))

        plan = "".join(chunks).strip()

        decision = self._memory.record_decision(
            goal=goal.id, statement=plan,
            reasoning="generated by the Model Router during a scheduled goal review",
            source="executive",
        )
        task = self._tasks.enqueue("execute_goal_step", {"goal_id": goal.id, "plan": plan})
        self._goals.mark_reviewed(goal.id)
        return ReviewOutcome(goal_id=goal.id, decision=decision, task_id=task.id)

    async def run_review_cycle(self) -> list[ReviewOutcome]:
        """The Executive's one scheduled duty today: review every active
        goal whose review_interval has elapsed. Real specialist-agent
        delegation (docs/agents/README.md) is future work — this
        produces a task and a reasoned decision per goal, not a full
        autonomous execution."""
        return [await self.review_goal(goal) for goal in self._goals.due_for_review()]
