"""milestone2 integrations and assets schema

Revision ID: 2f1fafad959a
Revises: 762368bc730d
Create Date: 2026-07-15 17:26:05.805758

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '2f1fafad959a'
down_revision: str | None = '762368bc730d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_types',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_types'))
    )
    op.create_index(op.f('ix_asset_types_key'), 'asset_types', ['key'], unique=True)
    op.create_table('integration_catalog',
    sa.Column('provider_id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('auth_method', sa.String(length=30), nullable=False),
    sa.Column('required_scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('permission_risk', sa.String(length=20), nullable=False),
    sa.Column('supported_data_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sync_modes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('webhook_support', sa.Boolean(), nullable=False),
    sa.Column('is_simulator', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_catalog'))
    )
    op.create_index(op.f('ix_integration_catalog_provider_id'), 'integration_catalog', ['provider_id'], unique=True)
    op.create_table('tenant_integrations',
    sa.Column('catalog_entry_id', sa.UUID(), nullable=False),
    sa.Column('credential_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('connecting', 'connected', 'error', 'disconnected', name='tenant_integration_status'), nullable=False),
    sa.Column('sync_mode', sa.String(length=20), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disconnected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['catalog_entry_id'], ['integration_catalog.id'], name=op.f('fk_tenant_integrations_catalog_entry_id_integration_catalog'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['credential_id'], ['integration_credentials.id'], name=op.f('fk_tenant_integrations_credential_id_integration_credentials'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_integrations'))
    )
    op.create_index(op.f('ix_tenant_integrations_tenant_id'), 'tenant_integrations', ['tenant_id'], unique=False)
    op.create_table('assets',
    sa.Column('asset_type_id', sa.UUID(), nullable=False),
    sa.Column('tenant_integration_id', sa.UUID(), nullable=True),
    sa.Column('display_name', sa.String(length=300), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('criticality', sa.Enum('low', 'medium', 'high', 'critical', name='asset_criticality'), nullable=False),
    sa.Column('exposure', sa.Enum('internal', 'external', 'unknown', name='asset_exposure'), nullable=False),
    sa.Column('lifecycle_status', sa.Enum('active', 'inactive', 'decommissioned', name='asset_lifecycle_status'), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_assessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_type_id'], ['asset_types.id'], name=op.f('fk_assets_asset_type_id_asset_types'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_integration_id'], ['tenant_integrations.id'], name=op.f('fk_assets_tenant_integration_id_tenant_integrations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets'))
    )
    op.create_index(op.f('ix_assets_tenant_id'), 'assets', ['tenant_id'], unique=False)
    op.create_table('integration_health',
    sa.Column('tenant_integration_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('healthy', 'degraded', 'error', name='integration_health_status'), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_integration_id'], ['tenant_integrations.id'], name=op.f('fk_integration_health_tenant_integration_id_tenant_integrations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_health'))
    )
    op.create_index(op.f('ix_integration_health_tenant_id'), 'integration_health', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_integration_health_tenant_integration_id'), 'integration_health', ['tenant_integration_id'], unique=False)
    op.create_table('integration_sync_runs',
    sa.Column('tenant_integration_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('running', 'success', 'failed', name='integration_sync_run_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('records_created', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_integration_id'], ['tenant_integrations.id'], name=op.f('fk_integration_sync_runs_tenant_integration_id_tenant_integrations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_sync_runs'))
    )
    op.create_index(op.f('ix_integration_sync_runs_tenant_id'), 'integration_sync_runs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_integration_sync_runs_tenant_integration_id'), 'integration_sync_runs', ['tenant_integration_id'], unique=False)
    op.create_table('asset_changes',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('tenant_integration_id', sa.UUID(), nullable=True),
    sa.Column('field_name', sa.String(length=120), nullable=False),
    sa.Column('old_value', sa.String(length=2000), nullable=True),
    sa.Column('new_value', sa.String(length=2000), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_changes_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_integration_id'], ['tenant_integrations.id'], name=op.f('fk_asset_changes_tenant_integration_id_tenant_integrations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_changes'))
    )
    op.create_index(op.f('ix_asset_changes_asset_id'), 'asset_changes', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_changes_tenant_id'), 'asset_changes', ['tenant_id'], unique=False)
    op.create_table('asset_identifiers',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('identifier_type', sa.String(length=60), nullable=False),
    sa.Column('identifier_value', sa.String(length=500), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_identifiers_asset_id_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_identifiers')),
    sa.UniqueConstraint('tenant_id', 'identifier_type', 'identifier_value', name='uq_asset_identifiers_dedup_key')
    )
    op.create_index(op.f('ix_asset_identifiers_asset_id'), 'asset_identifiers', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_identifiers_tenant_id'), 'asset_identifiers', ['tenant_id'], unique=False)
    op.create_table('asset_owners',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ownership_type', sa.String(length=40), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_owners_asset_id_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_owners')),
    sa.UniqueConstraint('tenant_id', 'asset_id', 'user_id', name='uq_asset_owners_pair')
    )
    op.create_index(op.f('ix_asset_owners_asset_id'), 'asset_owners', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_owners_tenant_id'), 'asset_owners', ['tenant_id'], unique=False)
    op.create_table('asset_relationships',
    sa.Column('from_asset_id', sa.UUID(), nullable=False),
    sa.Column('to_asset_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=60), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_asset_id'], ['assets.id'], name=op.f('fk_asset_relationships_from_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_asset_id'], ['assets.id'], name=op.f('fk_asset_relationships_to_asset_id_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_relationships')),
    sa.UniqueConstraint('tenant_id', 'from_asset_id', 'to_asset_id', 'relationship_type', name='uq_asset_relationships_edge')
    )
    op.create_index(op.f('ix_asset_relationships_from_asset_id'), 'asset_relationships', ['from_asset_id'], unique=False)
    op.create_index(op.f('ix_asset_relationships_tenant_id'), 'asset_relationships', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_asset_relationships_to_asset_id'), 'asset_relationships', ['to_asset_id'], unique=False)
    op.create_table('asset_tags',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', sa.String(length=300), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_tags_asset_id_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_tags')),
    sa.UniqueConstraint('tenant_id', 'asset_id', 'key', name='uq_asset_tags_pair')
    )
    op.create_index(op.f('ix_asset_tags_asset_id'), 'asset_tags', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_tags_tenant_id'), 'asset_tags', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_tags_tenant_id'), table_name='asset_tags')
    op.drop_index(op.f('ix_asset_tags_asset_id'), table_name='asset_tags')
    op.drop_table('asset_tags')
    op.drop_index(op.f('ix_asset_relationships_to_asset_id'), table_name='asset_relationships')
    op.drop_index(op.f('ix_asset_relationships_tenant_id'), table_name='asset_relationships')
    op.drop_index(op.f('ix_asset_relationships_from_asset_id'), table_name='asset_relationships')
    op.drop_table('asset_relationships')
    op.drop_index(op.f('ix_asset_owners_tenant_id'), table_name='asset_owners')
    op.drop_index(op.f('ix_asset_owners_asset_id'), table_name='asset_owners')
    op.drop_table('asset_owners')
    op.drop_index(op.f('ix_asset_identifiers_tenant_id'), table_name='asset_identifiers')
    op.drop_index(op.f('ix_asset_identifiers_asset_id'), table_name='asset_identifiers')
    op.drop_table('asset_identifiers')
    op.drop_index(op.f('ix_asset_changes_tenant_id'), table_name='asset_changes')
    op.drop_index(op.f('ix_asset_changes_asset_id'), table_name='asset_changes')
    op.drop_table('asset_changes')
    op.drop_index(op.f('ix_integration_sync_runs_tenant_integration_id'), table_name='integration_sync_runs')
    op.drop_index(op.f('ix_integration_sync_runs_tenant_id'), table_name='integration_sync_runs')
    op.drop_table('integration_sync_runs')
    op.drop_index(op.f('ix_integration_health_tenant_integration_id'), table_name='integration_health')
    op.drop_index(op.f('ix_integration_health_tenant_id'), table_name='integration_health')
    op.drop_table('integration_health')
    op.drop_index(op.f('ix_assets_tenant_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_tenant_integrations_tenant_id'), table_name='tenant_integrations')
    op.drop_table('tenant_integrations')
    op.drop_index(op.f('ix_integration_catalog_provider_id'), table_name='integration_catalog')
    op.drop_table('integration_catalog')
    op.drop_index(op.f('ix_asset_types_key'), table_name='asset_types')
    op.drop_table('asset_types')
    # ### end Alembic commands ###
