"""milestone31 least privilege app db role

Revision ID: 34016597f04f
Revises: f2c53ba8fbc5
Create Date: 2026-07-19 09:00:00.000000

"""
from __future__ import annotations

import os
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '34016597f04f'
down_revision: str | None = 'f2c53ba8fbc5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Hardening-programme Milestone 3 (finding C-01): the application has,
# since Milestone 1, connected to Postgres as the same role Alembic uses to
# run migrations — `gridkeep`, created via `POSTGRES_USER` on the stock
# `postgres` Docker image, which `initdb` always makes a superuser with
# BYPASSRLS regardless of the username chosen. Every Row-Level Security
# policy in this codebase (starting with migration 762368bc730d) has
# therefore been enforcing nothing for any request the running application
# ever actually made — reproduced live in the original security audit (a
# cross-tenant membership INSERT succeeded and committed against this
# exact role configuration) and independently corroborated by three
# pre-existing test failures documented in docs/security-findings-register.md.
#
# This migration creates a second, deliberately unprivileged role for the
# application's own runtime connection. Migrations themselves keep running
# as the superuser via DATABASE_MIGRATION_URL (see migrations/env.py, which
# hard-codes `settings.database_migration_url` as the only URL Alembic ever
# uses) — only DATABASE_URL, the connection api/worker/beat actually make
# requests over, changes to point at this role (docker-compose.yml,
# .github/workflows/ci.yml, tests/conftest.py).
#
# A managed/cloud Postgres deployment (RDS, Cloud SQL, etc.) typically does
# not grant the application's own migration user CREATEROLE at all — there,
# this role would be provisioned once via the provider's IaC/console
# instead of by this migration. Running it here is a pragmatic match for
# this project's actual deployment target today (a self-hosted Postgres
# inside docker-compose, where `gridkeep` genuinely is a real superuser
# with the rights to do this) — documented as a real, current limitation,
# not hidden.
_APP_ROLE = "gridkeep_app"

# Read at migration-run time so a real deployment can set a real, unique
# secret (`GRIDKEEP_APP_DB_PASSWORD`) before running `alembic upgrade head`.
# Falls back to a clearly-labelled development default so local/CI runs
# need no extra setup — matching every other credential this codebase
# ships a dev default for. core.config.Settings' fail-closed validator
# (Milestone 29) refuses to boot in production if DATABASE_URL still
# contains this literal string.
_DEV_DEFAULT_PASSWORD = "gridkeep-app-dev-only-insecure-do-not-use-in-production"


def _app_role_password() -> str:
    return os.environ.get("GRIDKEEP_APP_DB_PASSWORD", _DEV_DEFAULT_PASSWORD)


def upgrade() -> None:
    bind = op.get_bind()
    # Postgres has no bind-parameter support for role passwords in DDL —
    # the value has to be string-interpolated. Quotes are doubled
    # defensively even though every expected source (the dev default above,
    # or a real secret generated by `openssl rand`/a secrets manager) never
    # contains one.
    escaped_password = _app_role_password().replace("'", "''")

    role_exists = (
        bind.execute(
            sa.text("SELECT 1 FROM pg_roles WHERE rolname = :name"), {"name": _APP_ROLE}
        ).scalar_one_or_none()
        is not None
    )
    role_attrs = "NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE NOREPLICATION"
    if role_exists:
        # Idempotent: re-running this migration (or rotating the password
        # by re-running with a new GRIDKEEP_APP_DB_PASSWORD) converges on
        # the same role state rather than erroring on "already exists".
        op.execute(f"ALTER ROLE {_APP_ROLE} WITH LOGIN PASSWORD '{escaped_password}' {role_attrs}")
    else:
        op.execute(f"CREATE ROLE {_APP_ROLE} WITH LOGIN PASSWORD '{escaped_password}' {role_attrs}")

    op.execute(f"GRANT USAGE ON SCHEMA public TO {_APP_ROLE}")
    op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO {_APP_ROLE}")
    op.execute(f"GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO {_APP_ROLE}")
    # Applies to tables/sequences this migration's own connection (the
    # superuser, `gridkeep`) creates in the future — i.e. every later
    # migration — so a new table automatically grants gridkeep_app the same
    # CRUD access without needing its own explicit GRANT statement.
    op.execute(
        f"ALTER DEFAULT PRIVILEGES IN SCHEMA public "
        f"GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO {_APP_ROLE}"
    )
    op.execute(f"ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO {_APP_ROLE}")


def downgrade() -> None:
    op.execute(f"ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE USAGE, SELECT ON SEQUENCES FROM {_APP_ROLE}")
    op.execute(
        f"ALTER DEFAULT PRIVILEGES IN SCHEMA public "
        f"REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM {_APP_ROLE}"
    )
    op.execute(f"REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM {_APP_ROLE}")
    op.execute(f"REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM {_APP_ROLE}")
    op.execute(f"REVOKE USAGE ON SCHEMA public FROM {_APP_ROLE}")
    op.execute(f"DROP ROLE IF EXISTS {_APP_ROLE}")
