"""add deduplication and lead intelligence tables

Revision ID: 01a4e2835a3e
Revises: 3d4875d6ea04
Create Date: 2026-07-18 12:35:47.125154

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "01a4e2835a3e"
down_revision: str | Sequence[str] | None = "3d4875d6ea04"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "business_duplicate_candidates",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("business_id_a", sa.UUID(), nullable=False),
        sa.Column("business_id_b", sa.UUID(), nullable=False),
        sa.Column("match_type", sa.String(length=20), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("matched_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("reviewed_by_user_id", sa.UUID(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["reviewed_by_user_id"],
            ["users.id"],
            name=op.f("fk_business_duplicate_candidates_reviewed_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "business_id_a"],
            ["businesses.tenant_id", "businesses.id"],
            name="fk_business_duplicate_candidates_tenant_business_a",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "business_id_b"],
            ["businesses.tenant_id", "businesses.id"],
            name="fk_business_duplicate_candidates_tenant_business_b",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_business_duplicate_candidates")),
        sa.UniqueConstraint(
            "tenant_id",
            "business_id_a",
            "business_id_b",
            name="uq_business_duplicate_candidates_tenant_pair",
        ),
    )
    op.create_index(
        op.f("ix_business_duplicate_candidates_business_id_a"),
        "business_duplicate_candidates",
        ["business_id_a"],
        unique=False,
    )
    op.create_index(
        op.f("ix_business_duplicate_candidates_business_id_b"),
        "business_duplicate_candidates",
        ["business_id_b"],
        unique=False,
    )
    op.create_index(
        op.f("ix_business_duplicate_candidates_status"),
        "business_duplicate_candidates",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_business_duplicate_candidates_tenant_id"),
        "business_duplicate_candidates",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "business_merge_history",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("winner_business_id", sa.UUID(), nullable=False),
        sa.Column("loser_business_id", sa.UUID(), nullable=False),
        sa.Column("match_type", sa.String(length=20), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("merged_by_user_id", sa.UUID(), nullable=True),
        sa.Column("moved_records", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("field_changes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("undone_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("undone_by_user_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["merged_by_user_id"],
            ["users.id"],
            name=op.f("fk_business_merge_history_merged_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "winner_business_id"],
            ["businesses.tenant_id", "businesses.id"],
            name="fk_business_merge_history_tenant_winner",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["undone_by_user_id"],
            ["users.id"],
            name=op.f("fk_business_merge_history_undone_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_business_merge_history")),
    )
    op.create_index(
        op.f("ix_business_merge_history_loser_business_id"),
        "business_merge_history",
        ["loser_business_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_business_merge_history_tenant_id"),
        "business_merge_history",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_business_merge_history_winner_business_id"),
        "business_merge_history",
        ["winner_business_id"],
        unique=False,
    )
    op.create_table(
        "leads",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "business_id"],
            ["businesses.tenant_id", "businesses.id"],
            name="fk_leads_tenant_business",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_leads")),
        sa.UniqueConstraint("tenant_id", "business_id", name="uq_leads_tenant_business"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_leads_tenant_id_id"),
    )
    op.create_index(op.f("ix_leads_business_id"), "leads", ["business_id"], unique=False)
    op.create_index(op.f("ix_leads_status"), "leads", ["status"], unique=False)
    op.create_index(op.f("ix_leads_tenant_id"), "leads", ["tenant_id"], unique=False)
    op.create_table(
        "lead_opportunities",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("opportunity_type", sa.String(length=50), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("evidence_reference", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "lead_id"],
            ["leads.tenant_id", "leads.id"],
            name="fk_lead_opportunities_tenant_lead",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lead_opportunities")),
        sa.UniqueConstraint(
            "tenant_id",
            "lead_id",
            "opportunity_type",
            name="uq_lead_opportunities_tenant_lead_type",
        ),
    )
    op.create_index(
        op.f("ix_lead_opportunities_lead_id"), "lead_opportunities", ["lead_id"], unique=False
    )
    op.create_index(
        op.f("ix_lead_opportunities_opportunity_type"),
        "lead_opportunities",
        ["opportunity_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lead_opportunities_tenant_id"), "lead_opportunities", ["tenant_id"], unique=False
    )
    op.create_table(
        "lead_recommendations",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("recommendation_type", sa.String(length=50), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column(
            "supporting_opportunity_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("recommended_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "lead_id"],
            ["leads.tenant_id", "leads.id"],
            name="fk_lead_recommendations_tenant_lead",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lead_recommendations")),
        sa.UniqueConstraint(
            "tenant_id",
            "lead_id",
            "recommendation_type",
            name="uq_lead_recommendations_tenant_lead_type",
        ),
    )
    op.create_index(
        op.f("ix_lead_recommendations_lead_id"), "lead_recommendations", ["lead_id"], unique=False
    )
    op.create_index(
        op.f("ix_lead_recommendations_recommendation_type"),
        "lead_recommendations",
        ["recommendation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lead_recommendations_tenant_id"),
        "lead_recommendations",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "lead_scores",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("algorithm_version", sa.String(length=20), nullable=False),
        sa.Column("total_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("max_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("factors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "lead_id"],
            ["leads.tenant_id", "leads.id"],
            name="fk_lead_scores_tenant_lead",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lead_scores")),
    )
    op.create_index(op.f("ix_lead_scores_lead_id"), "lead_scores", ["lead_id"], unique=False)
    op.create_index(op.f("ix_lead_scores_tenant_id"), "lead_scores", ["tenant_id"], unique=False)
    op.add_column("businesses", sa.Column("normalized_phone", sa.String(length=30), nullable=True))
    op.add_column("businesses", sa.Column("merged_into_id", sa.UUID(), nullable=True))
    op.create_index(op.f("ix_businesses_city"), "businesses", ["city"], unique=False)
    op.create_index(
        op.f("ix_businesses_google_place_id"), "businesses", ["google_place_id"], unique=False
    )
    op.create_index(
        op.f("ix_businesses_merged_into_id"), "businesses", ["merged_into_id"], unique=False
    )
    op.create_index(
        op.f("ix_businesses_normalized_phone"), "businesses", ["normalized_phone"], unique=False
    )
    op.create_foreign_key(
        "fk_businesses_tenant_merged_into",
        "businesses",
        "businesses",
        ["tenant_id", "merged_into_id"],
        ["tenant_id", "id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###

    # Row Level Security, same pattern as Milestone 4's migration
    # (3d4875d6ea04): every new table here is strictly tenant-owned
    # (tenant_id NOT NULL), so they all use the plain tenant-match-or-
    # bypass policy. `businesses` itself already has RLS enabled from
    # Milestone 4 - only its new columns changed, not its policy.
    using_clause = (
        "tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid "
        "OR current_setting('app.platform_bypass', true) = 'true'"
    )
    for table in [
        "business_duplicate_candidates",
        "business_merge_history",
        "leads",
        "lead_scores",
        "lead_opportunities",
        "lead_recommendations",
    ]:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING ({using_clause}) WITH CHECK ({using_clause})"
        )


def downgrade() -> None:
    """Downgrade schema."""
    for table in [
        "lead_recommendations",
        "lead_opportunities",
        "lead_scores",
        "leads",
        "business_merge_history",
        "business_duplicate_candidates",
    ]:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_businesses_tenant_merged_into", "businesses", type_="foreignkey")
    op.drop_index(op.f("ix_businesses_normalized_phone"), table_name="businesses")
    op.drop_index(op.f("ix_businesses_merged_into_id"), table_name="businesses")
    op.drop_index(op.f("ix_businesses_google_place_id"), table_name="businesses")
    op.drop_index(op.f("ix_businesses_city"), table_name="businesses")
    op.drop_column("businesses", "merged_into_id")
    op.drop_column("businesses", "normalized_phone")
    op.drop_index(op.f("ix_lead_scores_tenant_id"), table_name="lead_scores")
    op.drop_index(op.f("ix_lead_scores_lead_id"), table_name="lead_scores")
    op.drop_table("lead_scores")
    op.drop_index(op.f("ix_lead_recommendations_tenant_id"), table_name="lead_recommendations")
    op.drop_index(
        op.f("ix_lead_recommendations_recommendation_type"), table_name="lead_recommendations"
    )
    op.drop_index(op.f("ix_lead_recommendations_lead_id"), table_name="lead_recommendations")
    op.drop_table("lead_recommendations")
    op.drop_index(op.f("ix_lead_opportunities_tenant_id"), table_name="lead_opportunities")
    op.drop_index(op.f("ix_lead_opportunities_opportunity_type"), table_name="lead_opportunities")
    op.drop_index(op.f("ix_lead_opportunities_lead_id"), table_name="lead_opportunities")
    op.drop_table("lead_opportunities")
    op.drop_index(op.f("ix_leads_tenant_id"), table_name="leads")
    op.drop_index(op.f("ix_leads_status"), table_name="leads")
    op.drop_index(op.f("ix_leads_business_id"), table_name="leads")
    op.drop_table("leads")
    op.drop_index(
        op.f("ix_business_merge_history_winner_business_id"), table_name="business_merge_history"
    )
    op.drop_index(op.f("ix_business_merge_history_tenant_id"), table_name="business_merge_history")
    op.drop_index(
        op.f("ix_business_merge_history_loser_business_id"), table_name="business_merge_history"
    )
    op.drop_table("business_merge_history")
    op.drop_index(
        op.f("ix_business_duplicate_candidates_tenant_id"),
        table_name="business_duplicate_candidates",
    )
    op.drop_index(
        op.f("ix_business_duplicate_candidates_status"), table_name="business_duplicate_candidates"
    )
    op.drop_index(
        op.f("ix_business_duplicate_candidates_business_id_b"),
        table_name="business_duplicate_candidates",
    )
    op.drop_index(
        op.f("ix_business_duplicate_candidates_business_id_a"),
        table_name="business_duplicate_candidates",
    )
    op.drop_table("business_duplicate_candidates")
    # ### end Alembic commands ###
