"""scholarly collaboration

Revision ID: 20260725_0032
Revises: 20260725_0031
"""
from alembic import op
import sqlalchemy as sa
revision='20260725_0032'; down_revision='20260725_0031'; branch_labels=None; depends_on=None

def upgrade():
    op.create_table('scholar_profiles',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('user_id',sa.Uuid(),sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False),sa.Column('display_name',sa.String(240),nullable=False),sa.Column('biography',sa.Text(),nullable=False,server_default=''),sa.Column('credentials_summary',sa.Text(),nullable=False,server_default=''),sa.Column('verification_status',sa.String(16),nullable=False,server_default='unverified'),sa.Column('verification_notes',sa.Text(),nullable=False,server_default=''),sa.Column('may_issue_platform_rulings',sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('user_id',name='uq_scholar_profile_user'),sa.CheckConstraint("verification_status IN ('unverified','pending','verified','rejected','suspended')",name='scholar_profile_verification_status'))
    op.create_table('scholarly_projects',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('title',sa.String(300),nullable=False),sa.Column('description',sa.Text(),nullable=False,server_default=''),sa.Column('owner_user_id',sa.Uuid(),sa.ForeignKey('users.id',ondelete='RESTRICT'),nullable=False),sa.Column('status',sa.String(16),nullable=False,server_default='draft'),sa.Column('required_islamic_reviews',sa.Integer(),nullable=False,server_default='2'),sa.Column('required_editorial_reviews',sa.Integer(),nullable=False,server_default='1'),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.CheckConstraint("status IN ('draft','in_review','approved','published','archived')",name='scholarly_project_status'))
    op.create_index('ix_scholarly_project_status','scholarly_projects',['status','updated_at'])
    op.create_table('collaborative_drafts',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('project_id',sa.Uuid(),sa.ForeignKey('scholarly_projects.id',ondelete='CASCADE'),nullable=False),sa.Column('slug',sa.String(160),nullable=False),sa.Column('title',sa.String(300),nullable=False),sa.Column('content_type',sa.String(32),nullable=False),sa.Column('current_version_number',sa.Integer(),nullable=False,server_default='0'),sa.Column('locked_for_review',sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('project_id','slug',name='uq_collaborative_draft_project_slug'),sa.CheckConstraint("content_type IN ('commentary','research_note','translation_note','curriculum_note')",name='collaborative_draft_content_type'))
    op.create_table('collaborative_draft_versions',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('draft_id',sa.Uuid(),sa.ForeignKey('collaborative_drafts.id',ondelete='CASCADE'),nullable=False),sa.Column('version_number',sa.Integer(),nullable=False),sa.Column('author_user_id',sa.Uuid(),sa.ForeignKey('users.id',ondelete='RESTRICT'),nullable=False),sa.Column('body',sa.Text(),nullable=False),sa.Column('change_summary',sa.Text(),nullable=False,server_default=''),sa.Column('content_fingerprint',sa.String(64),nullable=False),sa.Column('evidence_fingerprint',sa.String(64),nullable=False),sa.Column('status',sa.String(16),nullable=False,server_default='working'),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('draft_id','version_number',name='uq_collaborative_draft_version'),sa.CheckConstraint("status IN ('working','submitted','superseded','accepted')",name='collaborative_draft_version_status'))
    op.create_table('draft_evidence',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('draft_version_id',sa.Uuid(),sa.ForeignKey('collaborative_draft_versions.id',ondelete='CASCADE'),nullable=False),sa.Column('source_passage_id',sa.Uuid(),sa.ForeignKey('source_passages.id',ondelete='RESTRICT'),nullable=False),sa.Column('locator',sa.String(300),nullable=False),sa.Column('quotation',sa.Text(),nullable=False,server_default=''),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('draft_version_id','source_passage_id',name='uq_draft_version_evidence'))
    op.create_table('scholarly_review_assignments',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('draft_version_id',sa.Uuid(),sa.ForeignKey('collaborative_draft_versions.id',ondelete='CASCADE'),nullable=False),sa.Column('reviewer_user_id',sa.Uuid(),sa.ForeignKey('users.id',ondelete='RESTRICT'),nullable=False),sa.Column('assigned_by_user_id',sa.Uuid(),sa.ForeignKey('users.id',ondelete='RESTRICT'),nullable=False),sa.Column('review_type',sa.String(24),nullable=False),sa.Column('status',sa.String(16),nullable=False,server_default='assigned'),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('draft_version_id','reviewer_user_id','review_type',name='uq_scholarly_review_assignment'),sa.CheckConstraint("review_type IN ('islamic','editorial','source_integrity','translation')",name='scholarly_review_type'),sa.CheckConstraint("status IN ('assigned','in_progress','completed','cancelled')",name='scholarly_review_assignment_status'))
    op.create_table('scholarly_reviews',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('assignment_id',sa.Uuid(),sa.ForeignKey('scholarly_review_assignments.id',ondelete='CASCADE'),nullable=False),sa.Column('reviewer_user_id',sa.Uuid(),sa.ForeignKey('users.id',ondelete='RESTRICT'),nullable=False),sa.Column('decision',sa.String(24),nullable=False),sa.Column('comments',sa.Text(),nullable=False),sa.Column('evidence_checked',sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column('independent',sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('assignment_id',name='uq_scholarly_review_assignment_result'),sa.CheckConstraint("decision IN ('approve','changes_requested','reject','abstain')",name='scholarly_review_decision'))
    op.create_table('scholarly_approvals',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('draft_version_id',sa.Uuid(),sa.ForeignKey('collaborative_draft_versions.id',ondelete='CASCADE'),nullable=False),sa.Column('approved_by_user_id',sa.Uuid(),sa.ForeignKey('users.id',ondelete='RESTRICT'),nullable=False),sa.Column('decision',sa.String(16),nullable=False),sa.Column('rationale',sa.Text(),nullable=False),sa.Column('policy_version',sa.String(40),nullable=False),sa.Column('review_snapshot_fingerprint',sa.String(64),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('draft_version_id',name='uq_scholarly_approval_version'),sa.CheckConstraint("decision IN ('approved','rejected','withdrawn')",name='scholarly_approval_decision'))

def downgrade():
    for name in ['scholarly_approvals','scholarly_reviews','scholarly_review_assignments','draft_evidence','collaborative_draft_versions','collaborative_drafts','scholarly_projects','scholar_profiles']:
        op.drop_table(name)
