"""Milestone 15 community stewardship and analytics
Revision ID: 20260726_0060
Revises: 20260726_0059
"""
from alembic import op
import sqlalchemy as sa
revision='20260726_0060'; down_revision='20260726_0059'; branch_labels=None; depends_on=None
def upgrade():
 op.create_table('governed_community_contributions',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('organisation_id',sa.Uuid(),sa.ForeignKey('organisations.id',ondelete='CASCADE'),nullable=False),sa.Column('contribution_key',sa.String(160),nullable=False),sa.Column('version',sa.String(40),nullable=False),sa.Column('author_id',sa.Uuid(),sa.ForeignKey('users.id'),nullable=False),sa.Column('content_type',sa.String(40),nullable=False),sa.Column('status',sa.String(20),nullable=False,server_default='review'),sa.Column('evidence_json',sa.JSON(),nullable=False,server_default='{}'),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.UniqueConstraint('organisation_id','contribution_key','version',name='uq_governed_contribution_version'))
 op.create_table('stewardship_transfers',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('organisation_id',sa.Uuid(),sa.ForeignKey('organisations.id',ondelete='CASCADE'),nullable=False),sa.Column('from_institution_id',sa.Uuid(),sa.ForeignKey('institutions.id'),nullable=False),sa.Column('to_institution_id',sa.Uuid(),sa.ForeignKey('institutions.id'),nullable=False),sa.Column('asset_inventory_sha256',sa.String(64),nullable=False),sa.Column('audit_handover_sha256',sa.String(64),nullable=False),sa.Column('status',sa.String(20),nullable=False,server_default='planned'),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()))
 op.create_table('privacy_safe_analytics_releases',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('organisation_id',sa.Uuid(),sa.ForeignKey('organisations.id',ondelete='CASCADE'),nullable=False),sa.Column('release_slug',sa.String(100),nullable=False),sa.Column('version',sa.String(40),nullable=False),sa.Column('k_anonymity',sa.Integer(),nullable=False),sa.Column('minimum_group_size',sa.Integer(),nullable=False),sa.Column('export_sha256',sa.String(64),nullable=False),sa.Column('status',sa.String(20),nullable=False,server_default='draft'),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.UniqueConstraint('organisation_id','release_slug','version',name='uq_analytics_release_version'))
def downgrade():
 for t in ['privacy_safe_analytics_releases','stewardship_transfers','governed_community_contributions']:op.drop_table(t)
