"""research workspace foundation

Revision ID: 20260725_0030
Revises: 20260725_0029
"""
from alembic import op
import sqlalchemy as sa
revision='20260725_0030'; down_revision='20260725_0029'; branch_labels=None; depends_on=None

def upgrade():
    op.create_table('research_workspaces',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('owner_user_id',sa.Uuid(),sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False),sa.Column('slug',sa.String(120),nullable=False),sa.Column('title',sa.String(240),nullable=False),sa.Column('description',sa.Text(),nullable=False,server_default=''),sa.Column('visibility',sa.String(16),nullable=False,server_default='private'),sa.Column('version',sa.Integer(),nullable=False,server_default='1'),sa.Column('archived',sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('owner_user_id','slug',name='uq_research_workspace_owner_slug'),sa.CheckConstraint("visibility IN ('private','shared')",name='research_workspace_visibility'))
    op.create_table('research_workspace_members',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('workspace_id',sa.Uuid(),sa.ForeignKey('research_workspaces.id',ondelete='CASCADE'),nullable=False),sa.Column('user_id',sa.Uuid(),sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False),sa.Column('role',sa.String(16),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('workspace_id','user_id',name='uq_research_workspace_member'),sa.CheckConstraint("role IN ('viewer','contributor','editor')",name='research_workspace_member_role'))
    op.create_table('research_collections',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('workspace_id',sa.Uuid(),sa.ForeignKey('research_workspaces.id',ondelete='CASCADE'),nullable=False),sa.Column('slug',sa.String(120),nullable=False),sa.Column('title',sa.String(240),nullable=False),sa.Column('description',sa.Text(),nullable=False,server_default=''),sa.Column('position',sa.Integer(),nullable=False,server_default='0'),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('workspace_id','slug',name='uq_research_collection_workspace_slug'))
    op.create_table('research_items',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('collection_id',sa.Uuid(),sa.ForeignKey('research_collections.id',ondelete='CASCADE'),nullable=False),sa.Column('item_type',sa.String(32),nullable=False),sa.Column('item_id',sa.Uuid()),sa.Column('external_url',sa.String(1000)),sa.Column('title',sa.String(500),nullable=False),sa.Column('position',sa.Integer(),nullable=False,server_default='0'),sa.Column('added_by_user_id',sa.Uuid(),sa.ForeignKey('users.id',ondelete='RESTRICT'),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('collection_id','item_type','item_id',name='uq_research_collection_item'),sa.CheckConstraint("item_type IN ('source_passage','quran_ayah','hadith_narration','tafsir_entry','lesson','external_reference')",name='research_item_type'))
    op.create_table('research_annotations',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('workspace_id',sa.Uuid(),sa.ForeignKey('research_workspaces.id',ondelete='CASCADE'),nullable=False),sa.Column('research_item_id',sa.Uuid(),sa.ForeignKey('research_items.id',ondelete='CASCADE'),nullable=False),sa.Column('owner_user_id',sa.Uuid(),sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False),sa.Column('body',sa.Text(),nullable=False),sa.Column('visibility',sa.String(16),nullable=False,server_default='private'),sa.Column('eligible_as_evidence',sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.CheckConstraint("visibility IN ('private','workspace')",name='research_annotation_visibility'))
    op.create_index('ix_research_annotation_workspace_owner','research_annotations',['workspace_id','owner_user_id'])
    op.create_table('research_citations',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('workspace_id',sa.Uuid(),sa.ForeignKey('research_workspaces.id',ondelete='CASCADE'),nullable=False),sa.Column('research_item_id',sa.Uuid(),sa.ForeignKey('research_items.id',ondelete='RESTRICT'),nullable=False),sa.Column('citation_key',sa.String(120),nullable=False),sa.Column('style',sa.String(32),nullable=False,server_default='woi'),sa.Column('rendered_text',sa.Text(),nullable=False),sa.Column('provenance_json',sa.Text(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('workspace_id','citation_key',name='uq_research_workspace_citation_key'))
    op.create_table('reading_lists',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('workspace_id',sa.Uuid(),sa.ForeignKey('research_workspaces.id',ondelete='CASCADE'),nullable=False),sa.Column('slug',sa.String(120),nullable=False),sa.Column('title',sa.String(240),nullable=False),sa.Column('description',sa.Text(),nullable=False,server_default=''),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('workspace_id','slug',name='uq_reading_list_workspace_slug'))
    op.create_table('reading_list_entries',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('reading_list_id',sa.Uuid(),sa.ForeignKey('reading_lists.id',ondelete='CASCADE'),nullable=False),sa.Column('research_item_id',sa.Uuid(),sa.ForeignKey('research_items.id',ondelete='RESTRICT'),nullable=False),sa.Column('position',sa.Integer(),nullable=False),sa.Column('required',sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('reading_list_id','position',name='uq_reading_list_entry_position'),sa.UniqueConstraint('reading_list_id','research_item_id',name='uq_reading_list_item'))

def downgrade():
    for name in ['reading_list_entries','reading_lists','research_citations','research_annotations','research_items','research_collections','research_workspace_members','research_workspaces']: op.drop_table(name)
