"""Governed datasets, knowledge-record data contract, directory engine; wider knowledge-graph vocabulary.

Adds data_sets / data_set_imports / knowledge_records / directory_listings / directory_reports, full-text
indexes for them, and widens the knowledge-graph entity and relationship type checks.
"""
from alembic import op

revision = "20261001_0084"
down_revision = "20260930_0083"
branch_labels = None
depends_on = None

CREATE_STATEMENTS = [
    "CREATE TABLE data_sets (\n\tdataset_key VARCHAR(120) NOT NULL, \n\tname VARCHAR(300) NOT NULL, \n\tpurpose TEXT NOT NULL, \n\tentity_type VARCHAR(40) NOT NULL, \n\tsource_name VARCHAR(300) NOT NULL, \n\tsource_url VARCHAR(600), \n\tversion VARCHAR(80), \n\tdate_acquired DATE, \n\tlicense_name VARCHAR(240), \n\tlicense_status VARCHAR(40) DEFAULT 'UNKNOWN' NOT NULL, \n\tprovenance TEXT NOT NULL, \n\ttransformation TEXT, \n\timporter VARCHAR(200), \n\timporter_version VARCHAR(40), \n\tchecksum_sha256 VARCHAR(64), \n\tvalidation_status VARCHAR(16) DEFAULT 'NOT_RUN' NOT NULL, \n\tpublication_status VARCHAR(16) DEFAULT 'draft' NOT NULL, \n\treadiness VARCHAR(32) DEFAULT 'OWNER_UPLOAD_REQUIRED' NOT NULL, \n\tenabled BOOLEAN DEFAULT 'true' NOT NULL, \n\trights_confirmation JSONB, \n\tremaining_action TEXT, \n\trecord_count INTEGER DEFAULT '0' NOT NULL, \n\tlast_checked DATE, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_data_sets PRIMARY KEY (id), \n\tCONSTRAINT uq_data_sets_dataset_key UNIQUE (dataset_key), \n\tCONSTRAINT ck_data_sets_license_status CHECK (license_status IN ('VERIFIED_OPEN','PUBLIC_DOMAIN','PD_WORK_OPEN_EDITION_DECLARED','OWNER_PERMISSION_GRANTED','LICENSE_REQUIRED','PROVENANCE_UNCLEAR','UNKNOWN')), \n\tCONSTRAINT ck_data_sets_validation_status CHECK (validation_status IN ('VERIFIED','NEEDS_REVIEW','FAILED','NOT_RUN')), \n\tCONSTRAINT ck_data_sets_publication_status CHECK (publication_status IN ('draft','staged','published','disabled','rejected')), \n\tCONSTRAINT ck_data_sets_readiness CHECK (readiness IN ('VERIFIED','NEEDS_REVIEW','LICENSE_REQUIRED','PROVENANCE_UNCLEAR','UNAVAILABLE','OWNER_UPLOAD_REQUIRED'))\n)",
    "CREATE TABLE data_set_imports (\n\tdataset_id UUID NOT NULL, \n\tfile_sha256 VARCHAR(64) NOT NULL, \n\timporter_version VARCHAR(40) NOT NULL, \n\tstatus VARCHAR(16) DEFAULT 'applied' NOT NULL, \n\tcreated_count INTEGER DEFAULT '0' NOT NULL, \n\tupdated_count INTEGER DEFAULT '0' NOT NULL, \n\tunchanged_count INTEGER DEFAULT '0' NOT NULL, \n\tfailed_count INTEGER DEFAULT '0' NOT NULL, \n\tfailures JSONB DEFAULT '[]' NOT NULL, \n\tsnapshot JSONB DEFAULT '[]' NOT NULL, \n\timported_by_user_id UUID, \n\trolled_back_at TIMESTAMP WITH TIME ZONE, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_data_set_imports PRIMARY KEY (id), \n\tCONSTRAINT ck_data_set_imports_status CHECK (status IN ('applied','rolled_back','failed')), \n\tCONSTRAINT fk_data_set_imports_dataset_id_data_sets FOREIGN KEY(dataset_id) REFERENCES data_sets (id) ON DELETE CASCADE, \n\tCONSTRAINT fk_data_set_imports_imported_by_user_id_users FOREIGN KEY(imported_by_user_id) REFERENCES users (id) ON DELETE SET NULL\n)",
    'CREATE INDEX ix_data_set_imports_dataset_created ON data_set_imports (dataset_id, created_at)',
    "CREATE TABLE knowledge_records (\n\tdataset_id UUID NOT NULL, \n\timport_id UUID, \n\trecord_key VARCHAR(200) NOT NULL, \n\tentity_type VARCHAR(40) NOT NULL, \n\ttitle VARCHAR(500) NOT NULL, \n\tarabic_title VARCHAR(500), \n\tdescription TEXT NOT NULL, \n\tsource VARCHAR(500) NOT NULL, \n\tsource_url VARCHAR(800), \n\tauthor VARCHAR(300), \n\trecord_date VARCHAR(80), \n\tlicense VARCHAR(240) NOT NULL, \n\tprovenance TEXT NOT NULL, \n\tscholarly_status VARCHAR(24) DEFAULT 'unreviewed' NOT NULL, \n\tconfidence INTEGER DEFAULT '0' NOT NULL, \n\tlast_verified DATE, \n\ttags JSONB DEFAULT '[]' NOT NULL, \n\trelationships JSONB DEFAULT '[]' NOT NULL, \n\tcontent_sha256 VARCHAR(64) NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_knowledge_records PRIMARY KEY (id), \n\tCONSTRAINT uq_knowledge_records_dataset_key UNIQUE (dataset_id, record_key), \n\tCONSTRAINT ck_knowledge_records_entity_type CHECK (entity_type IN ('fiqh','aqeedah','seerah','hadith_grading','terminology','library_work','history','civilization','scholar','book','person','event','place','concept','institution')), \n\tCONSTRAINT ck_knowledge_records_scholarly_status CHECK (scholarly_status IN ('unreviewed','reviewed','scholar_verified','disputed','rejected')), \n\tCONSTRAINT ck_knowledge_records_confidence CHECK (confidence BETWEEN 0 AND 100), \n\tCONSTRAINT fk_knowledge_records_dataset_id_data_sets FOREIGN KEY(dataset_id) REFERENCES data_sets (id) ON DELETE CASCADE, \n\tCONSTRAINT fk_knowledge_records_import_id_data_set_imports FOREIGN KEY(import_id) REFERENCES data_set_imports (id) ON DELETE SET NULL\n)",
    'CREATE INDEX ix_knowledge_records_dataset_id ON knowledge_records (dataset_id)',
    'CREATE INDEX ix_knowledge_records_import_id ON knowledge_records (import_id)',
    'CREATE INDEX ix_knowledge_records_type ON knowledge_records (entity_type)',
    "CREATE TABLE directory_listings (\n\tdataset_id UUID, \n\timport_id UUID, \n\texternal_key VARCHAR(200), \n\tlisting_type VARCHAR(24) NOT NULL, \n\tname VARCHAR(300) NOT NULL, \n\tarabic_name VARCHAR(300), \n\tdescription TEXT, \n\tcategory VARCHAR(120), \n\ttags JSONB DEFAULT '[]' NOT NULL, \n\taddress VARCHAR(500), \n\tcity VARCHAR(120), \n\tregion VARCHAR(120), \n\tcountry VARCHAR(2), \n\tlatitude FLOAT, \n\tlongitude FLOAT, \n\tphone VARCHAR(60), \n\temail VARCHAR(254), \n\twebsite VARCHAR(500), \n\tstarts_at TIMESTAMP WITH TIME ZONE, \n\tends_at TIMESTAMP WITH TIME ZONE, \n\tsource VARCHAR(500) NOT NULL, \n\tsource_url VARCHAR(800), \n\tlicense VARCHAR(240) NOT NULL, \n\tprovenance TEXT NOT NULL, \n\tsource_updated_at DATE, \n\tstatus VARCHAR(16) DEFAULT 'pending' NOT NULL, \n\tverification_status VARCHAR(16) DEFAULT 'unverified' NOT NULL, \n\tverified_by_user_id UUID, \n\tverified_at TIMESTAMP WITH TIME ZONE, \n\tmoderation_note VARCHAR(1000), \n\tsubmitted_by_user_id UUID, \n\tduplicate_of_id UUID, \n\tdedupe_key VARCHAR(300) NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_directory_listings PRIMARY KEY (id), \n\tCONSTRAINT ck_directory_listings_listing_type CHECK (listing_type IN ('mosque','business','charity','job','professional','organisation','event','volunteering','health')), \n\tCONSTRAINT ck_directory_listings_status CHECK (status IN ('pending','published','hidden','rejected')), \n\tCONSTRAINT ck_directory_listings_verification_status CHECK (verification_status IN ('unverified','pending','verified','rejected','suspended')), \n\tCONSTRAINT ck_directory_listings_latitude CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90), \n\tCONSTRAINT ck_directory_listings_longitude CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180), \n\tCONSTRAINT ck_directory_listings_coordinates_pair CHECK ((latitude IS NULL) = (longitude IS NULL)), \n\tCONSTRAINT uq_directory_listings_dataset_key UNIQUE (dataset_id, external_key), \n\tCONSTRAINT fk_directory_listings_dataset_id_data_sets FOREIGN KEY(dataset_id) REFERENCES data_sets (id) ON DELETE CASCADE, \n\tCONSTRAINT fk_directory_listings_import_id_data_set_imports FOREIGN KEY(import_id) REFERENCES data_set_imports (id) ON DELETE SET NULL, \n\tCONSTRAINT fk_directory_listings_verified_by_user_id_users FOREIGN KEY(verified_by_user_id) REFERENCES users (id) ON DELETE SET NULL, \n\tCONSTRAINT fk_directory_listings_submitted_by_user_id_users FOREIGN KEY(submitted_by_user_id) REFERENCES users (id) ON DELETE SET NULL, \n\tCONSTRAINT fk_directory_listings_duplicate_of_id_directory_listings FOREIGN KEY(duplicate_of_id) REFERENCES directory_listings (id) ON DELETE SET NULL\n)",
    'CREATE INDEX ix_directory_listings_dataset_id ON directory_listings (dataset_id)',
    'CREATE INDEX ix_directory_listings_dedupe ON directory_listings (dedupe_key)',
    'CREATE INDEX ix_directory_listings_geo ON directory_listings (latitude, longitude)',
    'CREATE INDEX ix_directory_listings_import_id ON directory_listings (import_id)',
    'CREATE INDEX ix_directory_listings_type_status ON directory_listings (listing_type, status)',
    "CREATE TABLE directory_reports (\n\tlisting_id UUID NOT NULL, \n\treporter_user_id UUID, \n\treason VARCHAR(16) NOT NULL, \n\tdetails VARCHAR(2000), \n\tstatus VARCHAR(16) DEFAULT 'open' NOT NULL, \n\tresolved_by_user_id UUID, \n\tresolution_note VARCHAR(1000), \n\tresolved_at TIMESTAMP WITH TIME ZONE, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_directory_reports PRIMARY KEY (id), \n\tCONSTRAINT ck_directory_reports_reason CHECK (reason IN ('incorrect','closed','duplicate','offensive','fraud','other')), \n\tCONSTRAINT ck_directory_reports_status CHECK (status IN ('open','actioned','dismissed')), \n\tCONSTRAINT fk_directory_reports_listing_id_directory_listings FOREIGN KEY(listing_id) REFERENCES directory_listings (id) ON DELETE CASCADE, \n\tCONSTRAINT fk_directory_reports_reporter_user_id_users FOREIGN KEY(reporter_user_id) REFERENCES users (id) ON DELETE SET NULL, \n\tCONSTRAINT fk_directory_reports_resolved_by_user_id_users FOREIGN KEY(resolved_by_user_id) REFERENCES users (id) ON DELETE SET NULL\n)",
    'CREATE INDEX ix_directory_reports_listing_id ON directory_reports (listing_id)',
    'CREATE INDEX ix_directory_reports_status ON directory_reports (status, created_at)',
    "CREATE TABLE platform_audit_events (\n\tactor_user_id UUID, \n\taction VARCHAR(120) NOT NULL, \n\ttarget_type VARCHAR(80), \n\ttarget_id UUID, \n\tmetadata_json JSONB DEFAULT '{}' NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tid UUID NOT NULL, \n\tCONSTRAINT pk_platform_audit_events PRIMARY KEY (id), \n\tCONSTRAINT fk_platform_audit_events_actor_user_id_users FOREIGN KEY(actor_user_id) REFERENCES users (id) ON DELETE SET NULL\n)",
    'CREATE INDEX ix_platform_audit_events_action ON platform_audit_events (action)',
    'CREATE INDEX ix_platform_audit_events_created ON platform_audit_events (created_at)',
]

FULLTEXT = [
    "CREATE INDEX ix_knowledge_records_fts ON knowledge_records USING gin (to_tsvector('simple', title || ' ' || coalesce(arabic_title, '') || ' ' || description))",
    "CREATE INDEX ix_directory_listings_fts ON directory_listings USING gin (to_tsvector('simple', name || ' ' || coalesce(arabic_name, '') || ' ' || coalesce(description, '') || ' ' || coalesce(city, '')))",
]

ENTITY_TYPES = "'quran_ayah','hadith_narration','tafsir_entry','topic','lesson','course','scholar','research','dua','prophet','companion','place','historical_event','quran_surah','hadith_collection','tafsir_work','book','person','event','institution','mosque','organisation','concept'"
OLD_ENTITY_TYPES = "'quran_ayah','hadith_narration','tafsir_entry','topic','lesson','course','scholar','research','dua','prophet','companion','place','historical_event'"
RELATIONSHIP_TYPES = "'explains','supports','authenticates','references','narrated_by','revealed_in','mentions','contradicts_claim','related_topic','prerequisite','continuation_of','derived_from','contextualises','topic_membership','authored','discusses','relates_to','explained_by','part_of','located_in','affiliated_with'"
OLD_RELATIONSHIP_TYPES = "'explains','supports','authenticates','references','narrated_by','revealed_in','mentions','contradicts_claim','related_topic','prerequisite','continuation_of','derived_from','contextualises','topic_membership'"


def _replace_check(table: str, name: str, column: str, values: str) -> None:
    op.execute(f"ALTER TABLE {table} DROP CONSTRAINT {name}")
    op.execute(f"ALTER TABLE {table} ADD CONSTRAINT {name} CHECK ({column} IN ({values}))")


def upgrade() -> None:
    bind = op.get_bind()
    for statement in [*CREATE_STATEMENTS, *FULLTEXT]:
        bind.exec_driver_sql(statement)
    _replace_check("canonical_knowledge_entities", "ck_canonical_knowledge_entities_canonical_knowledge_entity_type", "entity_type", ENTITY_TYPES)
    _replace_check("knowledge_relationships", "ck_knowledge_relationships_knowledge_relationship_type", "relationship_type", RELATIONSHIP_TYPES)


def downgrade() -> None:
    # Graph rows that use the widened vocabulary are derived data (scripts/build_knowledge_graph.py rebuilds them);
    # they must go before the narrower constraints can be restored.
    op.execute(f"DELETE FROM knowledge_relationships WHERE relationship_type NOT IN ({OLD_RELATIONSHIP_TYPES})")
    op.execute(f"DELETE FROM canonical_knowledge_entities WHERE entity_type NOT IN ({OLD_ENTITY_TYPES})")
    _replace_check("knowledge_relationships", "ck_knowledge_relationships_knowledge_relationship_type", "relationship_type", OLD_RELATIONSHIP_TYPES)
    _replace_check("canonical_knowledge_entities", "ck_canonical_knowledge_entities_canonical_knowledge_entity_type", "entity_type", OLD_ENTITY_TYPES)
    for table in ("platform_audit_events", "directory_reports", "directory_listings", "knowledge_records", "data_set_imports", "data_sets"):
        op.execute(f"DROP TABLE IF EXISTS {table}")
