"""Milestone 15 research and education
Revision ID: 20260726_0059
Revises: 20260726_0058
"""
from alembic import op
import sqlalchemy as sa
revision='20260726_0059'; down_revision='20260726_0058'; branch_labels=None; depends_on=None
def upgrade():
 op.create_table('cross_institution_research_projects',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('organisation_id',sa.Uuid(),sa.ForeignKey('organisations.id',ondelete='CASCADE'),nullable=False),sa.Column('project_slug',sa.String(100),nullable=False),sa.Column('title',sa.String(240),nullable=False),sa.Column('lead_scholar_id',sa.Uuid(),sa.ForeignKey('scholar_profiles.id'),nullable=False),sa.Column('methodology_sha256',sa.String(64),nullable=False),sa.Column('status',sa.String(20),nullable=False,server_default='draft'),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.UniqueConstraint('organisation_id','project_slug',name='uq_cross_institution_project_slug'))
 op.create_table('research_institution_participants',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('project_id',sa.Uuid(),sa.ForeignKey('cross_institution_research_projects.id',ondelete='CASCADE'),nullable=False),sa.Column('institution_id',sa.Uuid(),sa.ForeignKey('institutions.id',ondelete='CASCADE'),nullable=False),sa.Column('role',sa.String(60),nullable=False),sa.Column('data_access_scope',sa.String(120),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.UniqueConstraint('project_id','institution_id',name='uq_research_institution_participant'))
 op.create_table('governed_curricula',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('organisation_id',sa.Uuid(),sa.ForeignKey('organisations.id',ondelete='CASCADE'),nullable=False),sa.Column('curriculum_slug',sa.String(100),nullable=False),sa.Column('version',sa.String(40),nullable=False),sa.Column('title',sa.String(240),nullable=False),sa.Column('evidence_coverage_percent',sa.Integer(),nullable=False),sa.Column('status',sa.String(20),nullable=False,server_default='draft'),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.UniqueConstraint('organisation_id','curriculum_slug','version',name='uq_governed_curriculum_version'))
 op.create_table('governed_certification_awards',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('curriculum_id',sa.Uuid(),sa.ForeignKey('governed_curricula.id',ondelete='CASCADE'),nullable=False),sa.Column('learner_id',sa.Uuid(),sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False),sa.Column('assessment_score',sa.Integer(),nullable=False),sa.Column('certificate_fingerprint',sa.String(64),nullable=False),sa.Column('status',sa.String(20),nullable=False,server_default='issued'),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.UniqueConstraint('curriculum_id','learner_id','certificate_fingerprint',name='uq_governed_certificate_award'))
def downgrade():
 for t in ['governed_certification_awards','governed_curricula','research_institution_participants','cross_institution_research_projects']:op.drop_table(t)
