"""community and moderation

Revision ID: 20260725_0031
Revises: 20260725_0030
"""
from alembic import op
import sqlalchemy as sa
revision='20260725_0031'; down_revision='20260725_0030'; branch_labels=None; depends_on=None

def upgrade():
    op.create_table('community_spaces',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('slug',sa.String(120),nullable=False),sa.Column('title',sa.String(240),nullable=False),sa.Column('description',sa.Text(),nullable=False,server_default=''),sa.Column('visibility',sa.String(16),nullable=False,server_default='members'),sa.Column('requires_evidence',sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column('child_access_allowed',sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('slug',name='uq_community_space_slug'),sa.CheckConstraint("visibility IN ('private','members','public')",name='community_space_visibility'))
    op.create_table('community_threads',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('space_id',sa.Uuid(),sa.ForeignKey('community_spaces.id',ondelete='CASCADE'),nullable=False),sa.Column('author_user_id',sa.Uuid(),sa.ForeignKey('users.id',ondelete='RESTRICT'),nullable=False),sa.Column('title',sa.String(300),nullable=False),sa.Column('body',sa.Text(),nullable=False),sa.Column('status',sa.String(16),nullable=False,server_default='open'),sa.Column('evidence_required',sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column('is_religious_claim',sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.CheckConstraint("status IN ('open','locked','hidden','archived')",name='community_thread_status'))
    op.create_index('ix_community_thread_space_status','community_threads',['space_id','status'])
    op.create_table('community_posts',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('thread_id',sa.Uuid(),sa.ForeignKey('community_threads.id',ondelete='CASCADE'),nullable=False),sa.Column('parent_post_id',sa.Uuid(),sa.ForeignKey('community_posts.id',ondelete='CASCADE')),sa.Column('author_user_id',sa.Uuid(),sa.ForeignKey('users.id',ondelete='RESTRICT'),nullable=False),sa.Column('body',sa.Text(),nullable=False),sa.Column('status',sa.String(16),nullable=False,server_default='pending'),sa.Column('is_religious_claim',sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column('authoritative_claim',sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.CheckConstraint("status IN ('visible','pending','hidden','removed')",name='community_post_status'))
    op.create_index('ix_community_post_thread_status','community_posts',['thread_id','status'])
    op.create_table('community_post_evidence',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('post_id',sa.Uuid(),sa.ForeignKey('community_posts.id',ondelete='CASCADE'),nullable=False),sa.Column('source_passage_id',sa.Uuid(),sa.ForeignKey('source_passages.id',ondelete='RESTRICT'),nullable=False),sa.Column('quotation',sa.Text(),nullable=False,server_default=''),sa.Column('locator',sa.String(300),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('post_id','source_passage_id',name='uq_community_post_evidence'))
    op.create_table('community_reports',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('reporter_user_id',sa.Uuid(),sa.ForeignKey('users.id',ondelete='RESTRICT'),nullable=False),sa.Column('target_type',sa.String(16),nullable=False),sa.Column('target_id',sa.Uuid(),nullable=False),sa.Column('category',sa.String(40),nullable=False),sa.Column('details',sa.Text(),nullable=False,server_default=''),sa.Column('status',sa.String(16),nullable=False,server_default='open'),sa.Column('risk_score',sa.Integer(),nullable=False,server_default='0'),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.CheckConstraint("target_type IN ('thread','post','profile')",name='community_report_target_type'),sa.CheckConstraint("status IN ('open','triaged','resolved','dismissed')",name='community_report_status'))
    op.create_index('ix_community_report_status','community_reports',['status','created_at'])
    op.create_table('moderation_decisions',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('report_id',sa.Uuid(),sa.ForeignKey('community_reports.id',ondelete='SET NULL')),sa.Column('moderator_user_id',sa.Uuid(),sa.ForeignKey('users.id',ondelete='RESTRICT'),nullable=False),sa.Column('target_type',sa.String(16),nullable=False),sa.Column('target_id',sa.Uuid(),nullable=False),sa.Column('action',sa.String(16),nullable=False),sa.Column('reason',sa.Text(),nullable=False),sa.Column('policy_code',sa.String(80),nullable=False),sa.Column('reversible',sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.CheckConstraint("action IN ('approve','hide','remove','lock','warn','escalate','dismiss')",name='moderation_decision_action'))
    op.create_table('community_reputation_events',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('user_id',sa.Uuid(),sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False),sa.Column('event_type',sa.String(40),nullable=False),sa.Column('points',sa.Integer(),nullable=False),sa.Column('reason',sa.String(300),nullable=False),sa.Column('grants_religious_authority',sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False))

def downgrade():
    for name in ['community_reputation_events','moderation_decisions','community_reports','community_post_evidence','community_posts','community_threads','community_spaces']:
        op.drop_table(name)
