"""production launch governance and final acceptance

Revision ID: 20260725_0041
Revises: 20260725_0040
"""
from alembic import op
import sqlalchemy as sa
revision = "20260725_0041"
down_revision = "20260725_0040"
branch_labels = None
depends_on = None

def upgrade():
    op.create_table("production_launch_approvals",
        sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("release_id", sa.Uuid(), sa.ForeignKey("deployment_releases.id", ondelete="CASCADE"), nullable=False), sa.Column("approval_type", sa.String(24), nullable=False), sa.Column("status", sa.String(16), nullable=False, server_default="draft"), sa.Column("approver_user_id", sa.Uuid(), sa.ForeignKey("users.id", ondelete="SET NULL"), nullable=True), sa.Column("evidence", sa.JSON(), nullable=False, server_default="{}"), sa.Column("decision_reason", sa.Text(), nullable=True), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.CheckConstraint("status IN ('draft','review','approved','rejected','revoked')", name="ck_launch_approval_status"), sa.CheckConstraint("approval_type IN ('security','privacy','scholarly','operations','product','executive')", name="ck_launch_approval_type"), sa.UniqueConstraint("release_id", "approval_type", name="uq_launch_approval_release_type"))
    op.create_index("ix_launch_approval_release_status", "production_launch_approvals", ["release_id", "status"])
    op.create_table("tenant_lifecycle_exercises",
        sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("organisation_id", sa.Uuid(), sa.ForeignKey("organisations.id", ondelete="CASCADE"), nullable=False), sa.Column("exercise_type", sa.String(20), nullable=False), sa.Column("status", sa.String(16), nullable=False, server_default="planned"), sa.Column("requested_by_user_id", sa.Uuid(), sa.ForeignKey("users.id", ondelete="SET NULL"), nullable=True), sa.Column("evidence_sha256", sa.String(64), nullable=True), sa.Column("cross_tenant_access_detected", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("records_processed", sa.Integer(), nullable=False, server_default="0"), sa.Column("result_summary", sa.JSON(), nullable=False, server_default="{}"), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.CheckConstraint("exercise_type IN ('export','deletion','suspension','reactivation','archive','restore')", name="ck_tenant_lifecycle_exercise_type"), sa.CheckConstraint("status IN ('planned','running','passed','failed','cancelled')", name="ck_tenant_lifecycle_exercise_status"))
    op.create_index("ix_tenant_lifecycle_exercise_tenant_status", "tenant_lifecycle_exercises", ["organisation_id", "status"])
    op.create_table("final_security_audits",
        sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("release_id", sa.Uuid(), sa.ForeignKey("deployment_releases.id", ondelete="CASCADE"), nullable=False), sa.Column("status", sa.String(24), nullable=False, server_default="planned"), sa.Column("independent_auditor", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("tenant_isolation_tested", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("authorization_tested", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("evidence_integrity_tested", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("critical_findings", sa.Integer(), nullable=False, server_default="0"), sa.Column("high_findings", sa.Integer(), nullable=False, server_default="0"), sa.Column("medium_findings", sa.Integer(), nullable=False, server_default="0"), sa.Column("low_findings", sa.Integer(), nullable=False, server_default="0"), sa.Column("report_uri", sa.Text(), nullable=True), sa.Column("report_sha256", sa.String(64), nullable=True), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.CheckConstraint("status IN ('planned','running','passed','failed','accepted_with_risk')", name="ck_final_security_audit_status"), sa.CheckConstraint("critical_findings >= 0 AND high_findings >= 0 AND medium_findings >= 0 AND low_findings >= 0", name="ck_final_security_audit_counts"))
    op.create_index("ix_final_security_audit_release_status", "final_security_audits", ["release_id", "status"])
    op.create_table("milestone_acceptances",
        sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("milestone_key", sa.String(40), nullable=False), sa.Column("release_id", sa.Uuid(), sa.ForeignKey("deployment_releases.id", ondelete="CASCADE"), nullable=False), sa.Column("status", sa.String(16), nullable=False, server_default="draft"), sa.Column("accepted_by_user_id", sa.Uuid(), sa.ForeignKey("users.id", ondelete="SET NULL"), nullable=True), sa.Column("verification_summary", sa.JSON(), nullable=False, server_default="{}"), sa.Column("limitations", sa.JSON(), nullable=False, server_default="[]"), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.CheckConstraint("status IN ('draft','blocked','accepted','revoked')", name="ck_milestone_acceptance_status"), sa.UniqueConstraint("milestone_key", "release_id", name="uq_milestone_acceptance_release"))

def downgrade():
    op.drop_table("milestone_acceptances"); op.drop_table("final_security_audits"); op.drop_table("tenant_lifecycle_exercises"); op.drop_table("production_launch_approvals")
