"""Milestone 15 scholarly governance and provenance
Revision ID: 20260726_0058
Revises: 20260726_0057
"""
from alembic import op
import sqlalchemy as sa
revision='20260726_0058'; down_revision='20260726_0057'; branch_labels=None; depends_on=None
def upgrade():
 op.create_table('scholarly_councils',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('organisation_id',sa.Uuid(),sa.ForeignKey('organisations.id',ondelete='CASCADE'),nullable=False),sa.Column('slug',sa.String(100),nullable=False),sa.Column('name',sa.String(200),nullable=False),sa.Column('quorum_percent',sa.Integer(),nullable=False),sa.Column('evidence_sha256',sa.String(64),nullable=False),sa.Column('status',sa.String(16),nullable=False,server_default='draft'),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.UniqueConstraint('organisation_id','slug',name='uq_scholarly_council_slug'))
 op.create_table('scholarly_council_members',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('council_id',sa.Uuid(),sa.ForeignKey('scholarly_councils.id',ondelete='CASCADE'),nullable=False),sa.Column('scholar_profile_id',sa.Uuid(),sa.ForeignKey('scholar_profiles.id',ondelete='CASCADE'),nullable=False),sa.Column('institution_id',sa.Uuid(),sa.ForeignKey('institutions.id',ondelete='SET NULL')),sa.Column('role',sa.String(40),nullable=False),sa.Column('active',sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.UniqueConstraint('council_id','scholar_profile_id',name='uq_scholarly_council_member'))
 op.create_table('scholarly_council_decisions',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('council_id',sa.Uuid(),sa.ForeignKey('scholarly_councils.id',ondelete='CASCADE'),nullable=False),sa.Column('decision_key',sa.String(160),nullable=False),sa.Column('version',sa.String(40),nullable=False),sa.Column('content_type',sa.String(40),nullable=False),sa.Column('decision_sha256',sa.String(64),nullable=False),sa.Column('outcome',sa.String(20),nullable=False),sa.Column('dissent_json',sa.JSON(),nullable=False,server_default='{}'),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.UniqueConstraint('council_id','decision_key','version',name='uq_scholarly_decision_version'))
 op.create_table('provenance_lineages',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('organisation_id',sa.Uuid(),sa.ForeignKey('organisations.id',ondelete='CASCADE'),nullable=False),sa.Column('canonical_id',sa.String(200),nullable=False),sa.Column('version',sa.String(40),nullable=False),sa.Column('payload_sha256',sa.String(64),nullable=False),sa.Column('lineage_sha256',sa.String(64),nullable=False),sa.Column('status',sa.String(16),nullable=False,server_default='draft'),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.UniqueConstraint('organisation_id','canonical_id','version',name='uq_provenance_lineage_version'))
 op.create_table('provenance_links',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('lineage_id',sa.Uuid(),sa.ForeignKey('provenance_lineages.id',ondelete='CASCADE'),nullable=False),sa.Column('link_type',sa.String(24),nullable=False),sa.Column('linked_fingerprint',sa.String(64),nullable=False),sa.Column('metadata_json',sa.JSON(),nullable=False,server_default='{}'),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.UniqueConstraint('lineage_id','link_type','linked_fingerprint',name='uq_provenance_link'))
def downgrade():
 for t in ['provenance_links','provenance_lineages','scholarly_council_decisions','scholarly_council_members','scholarly_councils']:op.drop_table(t)
