"""knowledge network and advanced navigation

Revision ID: 20260725_0033
Revises: 20260725_0032
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision='20260725_0033'; down_revision='20260725_0032'; branch_labels=None; depends_on=None

def upgrade():
    op.create_table('canonical_knowledge_entities',
        sa.Column('id',sa.Uuid(),primary_key=True), sa.Column('canonical_key',sa.String(220),nullable=False), sa.Column('entity_type',sa.String(40),nullable=False), sa.Column('source_entity_id',sa.Uuid(),nullable=False), sa.Column('english_label',sa.String(320),nullable=False), sa.Column('arabic_label',sa.String(320),nullable=False,server_default=''), sa.Column('transliteration',sa.String(320),nullable=False,server_default=''), sa.Column('summary',sa.Text(),nullable=False,server_default=''), sa.Column('canonical_url',sa.String(500),nullable=False), sa.Column('publication_status',sa.String(16),nullable=False,server_default='draft'), sa.Column('source_passage_id',sa.Uuid(),sa.ForeignKey('source_passages.id',ondelete='RESTRICT')), sa.Column('search_document',postgresql.JSONB(),nullable=False,server_default='{}'), sa.Column('created_at',sa.DateTime(timezone=True),nullable=False), sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),
        sa.UniqueConstraint('canonical_key',name='uq_canonical_knowledge_entity_key'), sa.UniqueConstraint('entity_type','source_entity_id',name='uq_canonical_knowledge_entity_source'), sa.CheckConstraint("entity_type IN ('quran_ayah','hadith_narration','tafsir_entry','topic','lesson','course','scholar','research','dua','prophet','companion','place','historical_event')",name='canonical_knowledge_entity_type'), sa.CheckConstraint("publication_status IN ('draft','reviewed','published','archived')",name='canonical_knowledge_publication_status'))
    op.create_index('ix_canonical_knowledge_entity_type_status','canonical_knowledge_entities',['entity_type','publication_status'])
    op.create_table('knowledge_relationships',
        sa.Column('id',sa.Uuid(),primary_key=True), sa.Column('source_entity_id',sa.Uuid(),sa.ForeignKey('canonical_knowledge_entities.id',ondelete='CASCADE'),nullable=False), sa.Column('target_entity_id',sa.Uuid(),sa.ForeignKey('canonical_knowledge_entities.id',ondelete='CASCADE'),nullable=False), sa.Column('relationship_type',sa.String(40),nullable=False), sa.Column('evidence_passage_id',sa.Uuid(),sa.ForeignKey('source_passages.id',ondelete='RESTRICT'),nullable=False), sa.Column('rationale',sa.Text(),nullable=False), sa.Column('confidence',sa.Integer(),nullable=False,server_default='100'), sa.Column('review_status',sa.String(16),nullable=False,server_default='pending'), sa.Column('reviewed_by_user_id',sa.Uuid(),sa.ForeignKey('users.id',ondelete='RESTRICT')), sa.Column('published',sa.Boolean(),nullable=False,server_default=sa.false()), sa.Column('created_at',sa.DateTime(timezone=True),nullable=False), sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),
        sa.UniqueConstraint('source_entity_id','target_entity_id','relationship_type','evidence_passage_id',name='uq_knowledge_relationship_evidence'), sa.CheckConstraint('source_entity_id <> target_entity_id',name='knowledge_relationship_not_self'), sa.CheckConstraint("relationship_type IN ('explains','supports','authenticates','references','narrated_by','revealed_in','mentions','contradicts_claim','related_topic','prerequisite','continuation_of','derived_from','contextualises','topic_membership')",name='knowledge_relationship_type'), sa.CheckConstraint("review_status IN ('pending','approved','rejected','withdrawn')",name='knowledge_relationship_review_status'), sa.CheckConstraint('confidence BETWEEN 0 AND 100',name='knowledge_relationship_confidence'))
    op.create_index('ix_knowledge_relationship_source','knowledge_relationships',['source_entity_id','relationship_type']); op.create_index('ix_knowledge_relationship_target','knowledge_relationships',['target_entity_id','relationship_type'])
    op.create_table('knowledge_entity_aliases', sa.Column('id',sa.Uuid(),primary_key=True), sa.Column('entity_id',sa.Uuid(),sa.ForeignKey('canonical_knowledge_entities.id',ondelete='CASCADE'),nullable=False), sa.Column('language',sa.String(16),nullable=False), sa.Column('alias',sa.String(320),nullable=False), sa.Column('normalized_alias',sa.String(320),nullable=False), sa.Column('alias_type',sa.String(24),nullable=False,server_default='name'), sa.Column('created_at',sa.DateTime(timezone=True),nullable=False), sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False), sa.UniqueConstraint('entity_id','language','normalized_alias',name='uq_knowledge_entity_alias'))
    op.create_index('ix_knowledge_entity_alias_lookup','knowledge_entity_aliases',['language','normalized_alias'])
    op.create_table('knowledge_traversal_audits', sa.Column('id',sa.Uuid(),primary_key=True), sa.Column('requester_user_id',sa.Uuid(),sa.ForeignKey('users.id',ondelete='SET NULL')), sa.Column('root_entity_id',sa.Uuid(),sa.ForeignKey('canonical_knowledge_entities.id',ondelete='RESTRICT'),nullable=False), sa.Column('max_depth',sa.Integer(),nullable=False), sa.Column('relationship_filters',postgresql.JSONB(),nullable=False,server_default='{}'), sa.Column('result_count',sa.Integer(),nullable=False,server_default='0'), sa.Column('truncated',sa.Boolean(),nullable=False,server_default=sa.false()), sa.Column('created_at',sa.DateTime(timezone=True),nullable=False), sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False), sa.CheckConstraint('max_depth BETWEEN 1 AND 5',name='knowledge_traversal_depth'), sa.CheckConstraint('result_count >= 0',name='knowledge_traversal_result_count'))
    op.create_index('ix_knowledge_traversal_audit_requester','knowledge_traversal_audits',['requester_user_id','created_at'])

def downgrade():
    for name in ['knowledge_traversal_audits','knowledge_entity_aliases','knowledge_relationships','canonical_knowledge_entities']:
        op.drop_table(name)
