"""learning foundation
Revision ID: 20260725_0026
Revises: 20260725_0025
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision='20260725_0026'; down_revision='20260725_0025'; branch_labels=None; depends_on=None

def common(): return [sa.Column('created_at',sa.DateTime(timezone=True),nullable=False,server_default=sa.text('now()')),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False,server_default=sa.text('now()'))]
def upgrade():
 u=postgresql.UUID(as_uuid=True)
 op.create_table('learning_paths',sa.Column('id',u,primary_key=True),sa.Column('slug',sa.String(120),nullable=False),sa.Column('title',sa.String(240),nullable=False),sa.Column('description',sa.Text(),nullable=False),sa.Column('canonical_language',sa.String(8),nullable=False,server_default='en'),sa.Column('audience',sa.String(80),nullable=False),sa.Column('status',sa.String(32),nullable=False,server_default='draft'),*common(),sa.UniqueConstraint('slug',name='uq_learning_paths_slug'))
 op.create_table('courses',sa.Column('id',u,primary_key=True),sa.Column('learning_path_id',u,sa.ForeignKey('learning_paths.id',ondelete='RESTRICT'),nullable=False),sa.Column('slug',sa.String(120),nullable=False),sa.Column('title',sa.String(240),nullable=False),sa.Column('summary',sa.Text(),nullable=False),sa.Column('intended_audience',sa.String(120),nullable=False),sa.Column('estimated_minutes',sa.Integer(),nullable=False),sa.Column('status',sa.String(32),nullable=False,server_default='draft'),sa.Column('current_version',sa.Integer(),nullable=False,server_default='1'),*common(),sa.UniqueConstraint('slug',name='uq_courses_slug'))
 op.create_table('course_versions',sa.Column('id',u,primary_key=True),sa.Column('course_id',u,sa.ForeignKey('courses.id',ondelete='CASCADE'),nullable=False),sa.Column('version',sa.Integer(),nullable=False),sa.Column('title',sa.String(240),nullable=False),sa.Column('summary',sa.Text(),nullable=False),sa.Column('immutable',sa.Boolean(),nullable=False,server_default=sa.text('false')),*common(),sa.UniqueConstraint('course_id','version',name='uq_course_version'))
 op.create_table('course_modules',sa.Column('id',u,primary_key=True),sa.Column('course_version_id',u,sa.ForeignKey('course_versions.id',ondelete='CASCADE'),nullable=False),sa.Column('title',sa.String(240),nullable=False),sa.Column('position',sa.Integer(),nullable=False),sa.Column('required',sa.Boolean(),nullable=False,server_default=sa.text('true')),*common(),sa.UniqueConstraint('course_version_id','position',name='uq_course_module_position'))
 op.create_table('lessons',sa.Column('id',u,primary_key=True),sa.Column('module_id',u,sa.ForeignKey('course_modules.id',ondelete='CASCADE'),nullable=False),sa.Column('title',sa.String(240),nullable=False),sa.Column('position',sa.Integer(),nullable=False),sa.Column('status',sa.String(32),nullable=False,server_default='draft'),sa.Column('version',sa.Integer(),nullable=False,server_default='1'),sa.Column('estimated_minutes',sa.Integer(),nullable=False),*common(),sa.UniqueConstraint('module_id','position',name='uq_lesson_position'))
 op.create_table('lesson_sections',sa.Column('id',u,primary_key=True),sa.Column('lesson_id',u,sa.ForeignKey('lessons.id',ondelete='CASCADE'),nullable=False),sa.Column('section_type',sa.String(32),nullable=False),sa.Column('heading',sa.String(240)),sa.Column('body',sa.Text(),nullable=False),sa.Column('position',sa.Integer(),nullable=False),*common(),sa.UniqueConstraint('lesson_id','position',name='uq_lesson_section_position'))
 op.create_table('lesson_evidence',sa.Column('id',u,primary_key=True),sa.Column('lesson_section_id',u,sa.ForeignKey('lesson_sections.id',ondelete='CASCADE'),nullable=False),sa.Column('source_passage_id',u,sa.ForeignKey('source_passages.id',ondelete='RESTRICT'),nullable=False),sa.Column('claim_label',sa.String(160),nullable=False),sa.Column('required',sa.Boolean(),nullable=False,server_default=sa.text('true')),*common(),sa.UniqueConstraint('lesson_section_id','source_passage_id',name='uq_lesson_evidence_passage'))
 op.create_table('learning_objectives',sa.Column('id',u,primary_key=True),sa.Column('lesson_id',u,sa.ForeignKey('lessons.id',ondelete='CASCADE'),nullable=False),sa.Column('text',sa.String(500),nullable=False),sa.Column('position',sa.Integer(),nullable=False),*common(),sa.UniqueConstraint('lesson_id','position',name='uq_learning_objective_position'))
 op.create_table('vocabulary_terms',sa.Column('id',u,primary_key=True),sa.Column('lesson_id',u,sa.ForeignKey('lessons.id',ondelete='CASCADE'),nullable=False),sa.Column('term',sa.String(160),nullable=False),sa.Column('arabic',sa.String(160)),sa.Column('transliteration',sa.String(160)),sa.Column('definition',sa.Text(),nullable=False),sa.Column('language',sa.String(8),nullable=False),*common(),sa.UniqueConstraint('lesson_id','term','language',name='uq_vocabulary_term_language'))
def downgrade():
 for t in ['vocabulary_terms','learning_objectives','lesson_evidence','lesson_sections','lessons','course_modules','course_versions','courses','learning_paths']: op.drop_table(t)
