"""Milestone 19 finance and family
Revision ID: 20260726_0076
Revises: 20260726_0075
"""
from alembic import op
import sqlalchemy as sa
revision='20260726_0076';down_revision='20260726_0075';branch_labels=None;depends_on=None
def _ts():return [sa.Column('created_at',sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now())]
def upgrade():
 op.create_table('islamic_finance_products',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('organisation_id',sa.Uuid(),sa.ForeignKey('organisations.id',ondelete='CASCADE'),nullable=False),sa.Column('product_slug',sa.String(120),nullable=False),sa.Column('version',sa.String(40),nullable=False),sa.Column('contract_type',sa.String(80),nullable=False),sa.Column('disclosure_sha256',sa.String(64),nullable=False),sa.Column('status',sa.String(20),nullable=False,server_default='draft'),*_ts(),sa.UniqueConstraint('organisation_id','product_slug','version',name='uq_islamic_finance_product'))
 op.create_table('shariah_board_reviews',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('product_id',sa.Uuid(),sa.ForeignKey('islamic_finance_products.id',ondelete='CASCADE'),nullable=False),sa.Column('reviewer_count',sa.Integer(),nullable=False),sa.Column('critical_findings',sa.Integer(),nullable=False),sa.Column('evidence_sha256',sa.String(64),nullable=False),sa.Column('outcome',sa.String(20),nullable=False),*_ts())
 op.create_table('contract_disclosures',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('product_id',sa.Uuid(),sa.ForeignKey('islamic_finance_products.id',ondelete='CASCADE'),nullable=False),sa.Column('language_code',sa.String(16),nullable=False),sa.Column('fees_disclosed',sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column('late_payment_treatment_disclosed',sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column('document_sha256',sa.String(64),nullable=False),*_ts())
 op.create_table('charity_finance_reconciliations',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('organisation_id',sa.Uuid(),sa.ForeignKey('organisations.id',ondelete='CASCADE'),nullable=False),sa.Column('period_reference',sa.String(40),nullable=False),sa.Column('ledger_sha256',sa.String(64),nullable=False),sa.Column('unreconciled_items',sa.Integer(),nullable=False),sa.Column('outcome',sa.String(20),nullable=False),*_ts())
 op.create_table('family_service_programmes',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('organisation_id',sa.Uuid(),sa.ForeignKey('organisations.id',ondelete='CASCADE'),nullable=False),sa.Column('programme_slug',sa.String(120),nullable=False),sa.Column('version',sa.String(40),nullable=False),sa.Column('safeguarding_sha256',sa.String(64),nullable=False),sa.Column('status',sa.String(20),nullable=False,server_default='draft'),*_ts(),sa.UniqueConstraint('organisation_id','programme_slug','version',name='uq_family_service_programme'))
 op.create_table('family_case_safeguards',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('programme_id',sa.Uuid(),sa.ForeignKey('family_service_programmes.id',ondelete='CASCADE'),nullable=False),sa.Column('case_reference',sa.String(180),nullable=False),sa.Column('risk_level',sa.String(20),nullable=False),sa.Column('escalation_active',sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column('evidence_sha256',sa.String(64),nullable=False),*_ts())
def downgrade():
 op.drop_table('family_case_safeguards');op.drop_table('family_service_programmes');op.drop_table('charity_finance_reconciliations');op.drop_table('contract_disclosures');op.drop_table('shariah_board_reviews');op.drop_table('islamic_finance_products')
