"""learning progress and assessments
Revision ID: 20260725_0028
Revises: 20260725_0027
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision='20260725_0028'; down_revision='20260725_0027'; branch_labels=None; depends_on=None
def common(): return [sa.Column('created_at',sa.DateTime(timezone=True),nullable=False,server_default=sa.text('now()')),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False,server_default=sa.text('now()'))]
def upgrade():
 u=postgresql.UUID(as_uuid=True)
 op.create_table('assessments',sa.Column('id',u,primary_key=True),sa.Column('scope_type',sa.String(16),nullable=False),sa.Column('scope_id',u,nullable=False),sa.Column('title',sa.String(240),nullable=False),sa.Column('passing_score',sa.Integer(),nullable=False),sa.Column('max_attempts',sa.Integer()),sa.Column('scoring_policy',sa.String(24),nullable=False,server_default='highest'),sa.Column('published',sa.Boolean(),nullable=False,server_default=sa.text('false')),*common())
 op.create_table('assessment_questions',sa.Column('id',u,primary_key=True),sa.Column('assessment_id',u,sa.ForeignKey('assessments.id',ondelete='CASCADE'),nullable=False),sa.Column('question_type',sa.String(32),nullable=False),sa.Column('prompt',sa.Text(),nullable=False),sa.Column('explanation',sa.Text(),nullable=False),sa.Column('position',sa.Integer(),nullable=False),sa.Column('points',sa.Integer(),nullable=False,server_default='1'),sa.Column('required',sa.Boolean(),nullable=False,server_default=sa.text('true')),*common(),sa.UniqueConstraint('assessment_id','position',name='uq_assessment_question_position'))
 op.create_table('question_options',sa.Column('id',u,primary_key=True),sa.Column('question_id',u,sa.ForeignKey('assessment_questions.id',ondelete='CASCADE'),nullable=False),sa.Column('text',sa.Text(),nullable=False),sa.Column('position',sa.Integer(),nullable=False),sa.Column('correct',sa.Boolean(),nullable=False,server_default=sa.text('false')),*common(),sa.UniqueConstraint('question_id','position',name='uq_question_option_position'))
 op.create_table('question_evidence',sa.Column('id',u,primary_key=True),sa.Column('question_id',u,sa.ForeignKey('assessment_questions.id',ondelete='CASCADE'),nullable=False),sa.Column('source_passage_id',u,sa.ForeignKey('source_passages.id',ondelete='RESTRICT'),nullable=False),*common(),sa.UniqueConstraint('question_id','source_passage_id',name='uq_question_evidence_passage'))
 op.create_table('course_enrollments',sa.Column('id',u,primary_key=True),sa.Column('user_id',u,sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False),sa.Column('course_id',u,sa.ForeignKey('courses.id',ondelete='RESTRICT'),nullable=False),sa.Column('course_version',sa.Integer(),nullable=False),sa.Column('status',sa.String(24),nullable=False,server_default='enrolled'),sa.Column('completion_percent',sa.Integer(),nullable=False,server_default='0'),*common(),sa.UniqueConstraint('user_id','course_id',name='uq_course_enrollment_user_course'))
 op.create_index('ix_course_enrollment_user_status','course_enrollments',['user_id','status'])
 op.create_table('lesson_progress',sa.Column('id',u,primary_key=True),sa.Column('user_id',u,sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False),sa.Column('lesson_id',u,sa.ForeignKey('lessons.id',ondelete='RESTRICT'),nullable=False),sa.Column('completed',sa.Boolean(),nullable=False,server_default=sa.text('false')),sa.Column('resume_section',sa.Integer(),nullable=False,server_default='0'),sa.Column('seconds_spent',sa.Integer(),nullable=False,server_default='0'),*common(),sa.UniqueConstraint('user_id','lesson_id',name='uq_lesson_progress_user_lesson'))
 op.create_table('assessment_attempts',sa.Column('id',u,primary_key=True),sa.Column('user_id',u,sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False),sa.Column('assessment_id',u,sa.ForeignKey('assessments.id',ondelete='RESTRICT'),nullable=False),sa.Column('attempt_number',sa.Integer(),nullable=False),sa.Column('status',sa.String(20),nullable=False,server_default='in_progress'),sa.Column('answers_json',sa.Text(),nullable=False,server_default='{}'),sa.Column('score',sa.Integer()),sa.Column('passed',sa.Boolean()),*common())
 op.create_index('ix_assessment_attempt_user','assessment_attempts',['user_id','assessment_id'])
def downgrade():
 op.drop_index('ix_assessment_attempt_user',table_name='assessment_attempts'); op.drop_table('assessment_attempts'); op.drop_table('lesson_progress'); op.drop_index('ix_course_enrollment_user_status',table_name='course_enrollments'); op.drop_table('course_enrollments'); op.drop_table('question_evidence'); op.drop_table('question_options'); op.drop_table('assessment_questions'); op.drop_table('assessments')
