"""add business persistence and enrichment tables

Revision ID: 3d4875d6ea04
Revises: 43cc58f21f97
Create Date: 2026-07-18 04:22:27.001958

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3d4875d6ea04"
down_revision: str | Sequence[str] | None = "43cc58f21f97"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "businesses",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("category", sa.String(length=150), nullable=True),
        sa.Column("subcategory", sa.String(length=150), nullable=True),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("region", sa.String(length=100), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("area", sa.String(length=100), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("website", sa.String(length=500), nullable=True),
        sa.Column("canonical_domain", sa.String(length=255), nullable=True),
        sa.Column("google_place_id", sa.String(length=255), nullable=True),
        sa.Column("google_maps_url", sa.String(length=500), nullable=True),
        sa.Column("rating", sa.Numeric(precision=2, scale=1), nullable=True),
        sa.Column("review_count", sa.Integer(), nullable=True),
        sa.Column("business_status", sa.String(length=50), nullable=True),
        sa.Column("field_provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_businesses_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_businesses")),
        sa.UniqueConstraint("tenant_id", "id", name="uq_businesses_tenant_id_id"),
    )
    op.create_index(
        op.f("ix_businesses_canonical_domain"), "businesses", ["canonical_domain"], unique=False
    )
    op.create_index(op.f("ix_businesses_tenant_id"), "businesses", ["tenant_id"], unique=False)
    op.create_table(
        "business_enrichments",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("pages_crawled", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.String(length=2000), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "business_id"],
            ["businesses.tenant_id", "businesses.id"],
            name="fk_business_enrichments_tenant_business",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_business_enrichments")),
        sa.UniqueConstraint("tenant_id", "id", name="uq_business_enrichments_tenant_id_id"),
    )
    op.create_index(
        op.f("ix_business_enrichments_business_id"),
        "business_enrichments",
        ["business_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_business_enrichments_status"), "business_enrichments", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_business_enrichments_tenant_id"),
        "business_enrichments",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "enrichment_evidence",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("enrichment_id", sa.UUID(), nullable=False),
        sa.Column("detector_type", sa.String(length=50), nullable=False),
        sa.Column("source_url", sa.String(length=500), nullable=False),
        sa.Column("structured_result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("supporting_snippet", sa.String(length=500), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "business_id"],
            ["businesses.tenant_id", "businesses.id"],
            name="fk_enrichment_evidence_tenant_business",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "enrichment_id"],
            ["business_enrichments.tenant_id", "business_enrichments.id"],
            name="fk_enrichment_evidence_tenant_enrichment",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_enrichment_evidence")),
    )
    op.create_index(
        op.f("ix_enrichment_evidence_business_id"),
        "enrichment_evidence",
        ["business_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_enrichment_evidence_detector_type"),
        "enrichment_evidence",
        ["detector_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_enrichment_evidence_enrichment_id"),
        "enrichment_evidence",
        ["enrichment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_enrichment_evidence_tenant_id"), "enrichment_evidence", ["tenant_id"], unique=False
    )
    op.create_table(
        "business_source_records",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("source_native_id", sa.String(length=255), nullable=False),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_business_source_records_campaign_id_campaigns"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "business_id"],
            ["businesses.tenant_id", "businesses.id"],
            name="fk_business_source_records_tenant_business",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_business_source_records")),
        sa.UniqueConstraint(
            "tenant_id",
            "source",
            "source_native_id",
            name="uq_business_source_records_tenant_source_native_id",
        ),
    )
    op.create_index(
        op.f("ix_business_source_records_business_id"),
        "business_source_records",
        ["business_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_business_source_records_tenant_id"),
        "business_source_records",
        ["tenant_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Row Level Security, same pattern as Milestone 2's migration
    # (43cc58f21f97): all four tables here are strictly tenant-owned
    # (tenant_id NOT NULL), so they use the plain tenant-match-or-bypass
    # policy.
    using_clause = (
        "tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid "
        "OR current_setting('app.platform_bypass', true) = 'true'"
    )
    for table in [
        "businesses",
        "business_source_records",
        "business_enrichments",
        "enrichment_evidence",
    ]:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING ({using_clause}) WITH CHECK ({using_clause})"
        )


def downgrade() -> None:
    """Downgrade schema."""
    for table in [
        "enrichment_evidence",
        "business_enrichments",
        "business_source_records",
        "businesses",
    ]:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_business_source_records_tenant_id"), table_name="business_source_records"
    )
    op.drop_index(
        op.f("ix_business_source_records_business_id"), table_name="business_source_records"
    )
    op.drop_table("business_source_records")
    op.drop_index(op.f("ix_enrichment_evidence_tenant_id"), table_name="enrichment_evidence")
    op.drop_index(op.f("ix_enrichment_evidence_enrichment_id"), table_name="enrichment_evidence")
    op.drop_index(op.f("ix_enrichment_evidence_detector_type"), table_name="enrichment_evidence")
    op.drop_index(op.f("ix_enrichment_evidence_business_id"), table_name="enrichment_evidence")
    op.drop_table("enrichment_evidence")
    op.drop_index(op.f("ix_business_enrichments_tenant_id"), table_name="business_enrichments")
    op.drop_index(op.f("ix_business_enrichments_status"), table_name="business_enrichments")
    op.drop_index(op.f("ix_business_enrichments_business_id"), table_name="business_enrichments")
    op.drop_table("business_enrichments")
    op.drop_index(op.f("ix_businesses_tenant_id"), table_name="businesses")
    op.drop_index(op.f("ix_businesses_canonical_domain"), table_name="businesses")
    op.drop_table("businesses")
    # ### end Alembic commands ###
