"""add campaign engine tables

Revision ID: 43cc58f21f97
Revises: fe3f382fcffa
Create Date: 2026-07-17 12:26:44.056434

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "43cc58f21f97"
down_revision: str | Sequence[str] | None = "fe3f382fcffa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "campaigns",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("source_key", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("result_limit", sa.Integer(), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("reservation_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_campaigns_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["credit_reservations.id"],
            name=op.f("fk_campaigns_reservation_id_credit_reservations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_campaigns_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaigns")),
        sa.UniqueConstraint("tenant_id", "id", name="uq_campaigns_tenant_id_id"),
    )
    op.create_index(op.f("ix_campaigns_status"), "campaigns", ["status"], unique=False)
    op.create_index(op.f("ix_campaigns_tenant_id"), "campaigns", ["tenant_id"], unique=False)
    op.create_table(
        "campaign_events",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("from_status", sa.String(length=30), nullable=True),
        sa.Column("to_status", sa.String(length=30), nullable=True),
        sa.Column("message", sa.String(length=1000), nullable=True),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "campaign_id"],
            ["campaigns.tenant_id", "campaigns.id"],
            name="fk_campaign_events_tenant_campaign",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign_events")),
    )
    op.create_index(
        op.f("ix_campaign_events_campaign_id"), "campaign_events", ["campaign_id"], unique=False
    )
    op.create_index(
        op.f("ix_campaign_events_tenant_id"), "campaign_events", ["tenant_id"], unique=False
    )
    op.create_table(
        "campaign_filters",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("industry", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("subcategory", sa.String(length=100), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=False),
        sa.Column("region", sa.String(length=100), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("area", sa.String(length=100), nullable=True),
        sa.Column("radius_km", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("min_rating", sa.Numeric(precision=2, scale=1), nullable=True),
        sa.Column("min_reviews", sa.Integer(), nullable=True),
        sa.Column("must_have_phone", sa.Boolean(), nullable=False),
        sa.Column("website_requirement", sa.String(length=20), nullable=False),
        sa.Column("business_status", sa.String(length=50), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "campaign_id"],
            ["campaigns.tenant_id", "campaigns.id"],
            name="fk_campaign_filters_tenant_campaign",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign_filters")),
        sa.UniqueConstraint("campaign_id", name="uq_campaign_filters_campaign_id"),
    )
    op.create_index(
        op.f("ix_campaign_filters_tenant_id"), "campaign_filters", ["tenant_id"], unique=False
    )
    op.create_table(
        "campaign_jobs",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("current_cursor", sa.String(length=100), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "campaign_id"],
            ["campaigns.tenant_id", "campaigns.id"],
            name="fk_campaign_jobs_tenant_campaign",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign_jobs")),
        sa.UniqueConstraint("tenant_id", "id", name="uq_campaign_jobs_tenant_id_id"),
    )
    op.create_index(
        op.f("ix_campaign_jobs_campaign_id"), "campaign_jobs", ["campaign_id"], unique=False
    )
    op.create_index(op.f("ix_campaign_jobs_status"), "campaign_jobs", ["status"], unique=False)
    op.create_index(
        op.f("ix_campaign_jobs_tenant_id"), "campaign_jobs", ["tenant_id"], unique=False
    )
    op.create_table(
        "campaign_usage_estimates",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("estimated_credits", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("estimated_results", sa.Integer(), nullable=False),
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "campaign_id"],
            ["campaigns.tenant_id", "campaigns.id"],
            name="fk_campaign_usage_estimates_tenant_campaign",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign_usage_estimates")),
        sa.UniqueConstraint("campaign_id", name="uq_campaign_usage_estimates_campaign_id"),
    )
    op.create_index(
        op.f("ix_campaign_usage_estimates_tenant_id"),
        "campaign_usage_estimates",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "campaign_tasks",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=150), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("cursor_in", sa.String(length=100), nullable=True),
        sa.Column("cursor_out", sa.String(length=100), nullable=True),
        sa.Column("businesses_found", sa.Integer(), nullable=False),
        sa.Column("result_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("locked_by", sa.String(length=100), nullable=True),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.String(length=2000), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "campaign_id"],
            ["campaigns.tenant_id", "campaigns.id"],
            name="fk_campaign_tasks_tenant_campaign",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "job_id"],
            ["campaign_jobs.tenant_id", "campaign_jobs.id"],
            name="fk_campaign_tasks_tenant_job",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign_tasks")),
        sa.UniqueConstraint("idempotency_key", name="uq_campaign_tasks_idempotency_key"),
    )
    op.create_index(
        op.f("ix_campaign_tasks_campaign_id"), "campaign_tasks", ["campaign_id"], unique=False
    )
    op.create_index(op.f("ix_campaign_tasks_job_id"), "campaign_tasks", ["job_id"], unique=False)
    op.create_index(op.f("ix_campaign_tasks_status"), "campaign_tasks", ["status"], unique=False)
    op.create_index(
        op.f("ix_campaign_tasks_tenant_id"), "campaign_tasks", ["tenant_id"], unique=False
    )
    op.create_table(
        "campaign_errors",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column("error_type", sa.String(length=100), nullable=False),
        sa.Column("message", sa.String(length=2000), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["campaign_tasks.id"],
            name=op.f("fk_campaign_errors_task_id_campaign_tasks"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "campaign_id"],
            ["campaigns.tenant_id", "campaigns.id"],
            name="fk_campaign_errors_tenant_campaign",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign_errors")),
    )
    op.create_index(
        op.f("ix_campaign_errors_campaign_id"), "campaign_errors", ["campaign_id"], unique=False
    )
    op.create_index(
        op.f("ix_campaign_errors_tenant_id"), "campaign_errors", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###

    # Row Level Security, same pattern as the Milestone 1 migration
    # (8a1f2c3d4e5f): all seven tables here are strictly tenant-owned
    # (tenant_id NOT NULL), so they use the plain tenant-match-or-bypass
    # policy - none of them have the roles/role_permissions-style nullable
    # tenant_id, so there is no "OR tenant_id IS NULL" clause needed.
    using_clause = (
        "tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid "
        "OR current_setting('app.platform_bypass', true) = 'true'"
    )
    for table in [
        "campaigns",
        "campaign_filters",
        "campaign_usage_estimates",
        "campaign_events",
        "campaign_errors",
        "campaign_jobs",
        "campaign_tasks",
    ]:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING ({using_clause}) WITH CHECK ({using_clause})"
        )


def downgrade() -> None:
    """Downgrade schema."""
    for table in [
        "campaign_tasks",
        "campaign_jobs",
        "campaign_errors",
        "campaign_events",
        "campaign_usage_estimates",
        "campaign_filters",
        "campaigns",
    ]:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_campaign_errors_tenant_id"), table_name="campaign_errors")
    op.drop_index(op.f("ix_campaign_errors_campaign_id"), table_name="campaign_errors")
    op.drop_table("campaign_errors")
    op.drop_index(op.f("ix_campaign_tasks_tenant_id"), table_name="campaign_tasks")
    op.drop_index(op.f("ix_campaign_tasks_status"), table_name="campaign_tasks")
    op.drop_index(op.f("ix_campaign_tasks_job_id"), table_name="campaign_tasks")
    op.drop_index(op.f("ix_campaign_tasks_campaign_id"), table_name="campaign_tasks")
    op.drop_table("campaign_tasks")
    op.drop_index(
        op.f("ix_campaign_usage_estimates_tenant_id"), table_name="campaign_usage_estimates"
    )
    op.drop_table("campaign_usage_estimates")
    op.drop_index(op.f("ix_campaign_jobs_tenant_id"), table_name="campaign_jobs")
    op.drop_index(op.f("ix_campaign_jobs_status"), table_name="campaign_jobs")
    op.drop_index(op.f("ix_campaign_jobs_campaign_id"), table_name="campaign_jobs")
    op.drop_table("campaign_jobs")
    op.drop_index(op.f("ix_campaign_filters_tenant_id"), table_name="campaign_filters")
    op.drop_table("campaign_filters")
    op.drop_index(op.f("ix_campaign_events_tenant_id"), table_name="campaign_events")
    op.drop_index(op.f("ix_campaign_events_campaign_id"), table_name="campaign_events")
    op.drop_table("campaign_events")
    op.drop_index(op.f("ix_campaigns_tenant_id"), table_name="campaigns")
    op.drop_index(op.f("ix_campaigns_status"), table_name="campaigns")
    op.drop_table("campaigns")
    # ### end Alembic commands ###
