"""add integrations tables

Revision ID: 6ab02302f662
Revises: 865e52821072
Create Date: 2026-07-18 22:52:48.102718

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6ab02302f662"
down_revision: str | Sequence[str] | None = "865e52821072"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "integrations",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("type", sa.String(length=30), nullable=False),
        sa.Column("webhook_url", sa.String(length=1000), nullable=False),
        sa.Column("webhook_secret_encrypted", sa.String(length=1000), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_integrations_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_integrations_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integrations")),
        sa.UniqueConstraint("tenant_id", "id", name="uq_integrations_tenant_id_id"),
    )
    op.create_index(
        op.f("ix_integrations_tenant_id"), "integrations", ["tenant_id"], unique=False
    )
    op.create_table(
        "integration_deliveries",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("integration_id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("http_status_code", sa.Integer(), nullable=True),
        sa.Column("response_snippet", sa.String(length=1000), nullable=True),
        sa.Column("error_message", sa.String(length=2000), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("triggered_by_user_id", sa.UUID(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "integration_id"],
            ["integrations.tenant_id", "integrations.id"],
            name="fk_integration_deliveries_tenant_integration",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["triggered_by_user_id"],
            ["users.id"],
            name=op.f("fk_integration_deliveries_triggered_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integration_deliveries")),
    )
    op.create_index(
        op.f("ix_integration_deliveries_integration_id"),
        "integration_deliveries",
        ["integration_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_integration_deliveries_status"),
        "integration_deliveries",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_integration_deliveries_tenant_id"),
        "integration_deliveries",
        ["tenant_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Row Level Security, same pattern as every prior milestone's migration.
    using_clause = (
        "tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid "
        "OR current_setting('app.platform_bypass', true) = 'true'"
    )
    for table in ["integrations", "integration_deliveries"]:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING ({using_clause}) WITH CHECK ({using_clause})"
        )


def downgrade() -> None:
    """Downgrade schema."""
    for table in ["integration_deliveries", "integrations"]:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_integration_deliveries_tenant_id"), table_name="integration_deliveries")
    op.drop_index(op.f("ix_integration_deliveries_status"), table_name="integration_deliveries")
    op.drop_index(
        op.f("ix_integration_deliveries_integration_id"), table_name="integration_deliveries"
    )
    op.drop_table("integration_deliveries")
    op.drop_index(op.f("ix_integrations_tenant_id"), table_name="integrations")
    op.drop_table("integrations")
    # ### end Alembic commands ###
