"""add lead workspace tables

Revision ID: a3024f96410c
Revises: 01a4e2835a3e
Create Date: 2026-07-18 13:11:28.439886

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a3024f96410c"
down_revision: str | Sequence[str] | None = "01a4e2835a3e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "saved_lead_views",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("filters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_saved_lead_views_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_saved_lead_views")),
        sa.UniqueConstraint("tenant_id", "name", name="uq_saved_lead_views_tenant_name"),
    )
    op.create_index(
        op.f("ix_saved_lead_views_tenant_id"), "saved_lead_views", ["tenant_id"], unique=False
    )
    op.create_table(
        "lead_assignments",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("assigned_to_user_id", sa.UUID(), nullable=False),
        sa.Column("assigned_by_user_id", sa.UUID(), nullable=True),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("unassigned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_by_user_id"],
            ["users.id"],
            name=op.f("fk_lead_assignments_assigned_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to_user_id"],
            ["users.id"],
            name=op.f("fk_lead_assignments_assigned_to_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "lead_id"],
            ["leads.tenant_id", "leads.id"],
            name="fk_lead_assignments_tenant_lead",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lead_assignments")),
    )
    op.create_index(
        op.f("ix_lead_assignments_lead_id"), "lead_assignments", ["lead_id"], unique=False
    )
    op.create_index(
        op.f("ix_lead_assignments_tenant_id"), "lead_assignments", ["tenant_id"], unique=False
    )
    op.create_table(
        "lead_notes",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("author_user_id", sa.UUID(), nullable=True),
        sa.Column("body", sa.String(length=4000), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_user_id"],
            ["users.id"],
            name=op.f("fk_lead_notes_author_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "lead_id"],
            ["leads.tenant_id", "leads.id"],
            name="fk_lead_notes_tenant_lead",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lead_notes")),
    )
    op.create_index(op.f("ix_lead_notes_lead_id"), "lead_notes", ["lead_id"], unique=False)
    op.create_index(op.f("ix_lead_notes_tenant_id"), "lead_notes", ["tenant_id"], unique=False)
    op.create_table(
        "lead_status_history",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("from_status", sa.String(length=20), nullable=False),
        sa.Column("to_status", sa.String(length=20), nullable=False),
        sa.Column("changed_by_user_id", sa.UUID(), nullable=True),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("note", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["changed_by_user_id"],
            ["users.id"],
            name=op.f("fk_lead_status_history_changed_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "lead_id"],
            ["leads.tenant_id", "leads.id"],
            name="fk_lead_status_history_tenant_lead",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lead_status_history")),
    )
    op.create_index(
        op.f("ix_lead_status_history_lead_id"), "lead_status_history", ["lead_id"], unique=False
    )
    op.create_index(
        op.f("ix_lead_status_history_tenant_id"), "lead_status_history", ["tenant_id"], unique=False
    )
    op.create_table(
        "lead_tags",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("tag", sa.String(length=50), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_lead_tags_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "lead_id"],
            ["leads.tenant_id", "leads.id"],
            name="fk_lead_tags_tenant_lead",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lead_tags")),
        sa.UniqueConstraint("tenant_id", "lead_id", "tag", name="uq_lead_tags_tenant_lead_tag"),
    )
    op.create_index(op.f("ix_lead_tags_lead_id"), "lead_tags", ["lead_id"], unique=False)
    op.create_index(op.f("ix_lead_tags_tag"), "lead_tags", ["tag"], unique=False)
    op.create_index(op.f("ix_lead_tags_tenant_id"), "lead_tags", ["tenant_id"], unique=False)
    op.add_column("leads", sa.Column("assigned_to_user_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_leads_assigned_to_user_id"), "leads", ["assigned_to_user_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_leads_assigned_to_user_id_users"),
        "leads",
        "users",
        ["assigned_to_user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###

    # Row Level Security, same pattern as every prior milestone's
    # migration: all five new tables here are strictly tenant-owned
    # (tenant_id NOT NULL), so they all use the plain tenant-match-or-
    # bypass policy.
    using_clause = (
        "tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid "
        "OR current_setting('app.platform_bypass', true) = 'true'"
    )
    for table in [
        "saved_lead_views",
        "lead_assignments",
        "lead_notes",
        "lead_status_history",
        "lead_tags",
    ]:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING ({using_clause}) WITH CHECK ({using_clause})"
        )


def downgrade() -> None:
    """Downgrade schema."""
    for table in [
        "lead_tags",
        "lead_status_history",
        "lead_notes",
        "lead_assignments",
        "saved_lead_views",
    ]:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_leads_assigned_to_user_id_users"), "leads", type_="foreignkey")
    op.drop_index(op.f("ix_leads_assigned_to_user_id"), table_name="leads")
    op.drop_column("leads", "assigned_to_user_id")
    op.drop_index(op.f("ix_lead_tags_tenant_id"), table_name="lead_tags")
    op.drop_index(op.f("ix_lead_tags_tag"), table_name="lead_tags")
    op.drop_index(op.f("ix_lead_tags_lead_id"), table_name="lead_tags")
    op.drop_table("lead_tags")
    op.drop_index(op.f("ix_lead_status_history_tenant_id"), table_name="lead_status_history")
    op.drop_index(op.f("ix_lead_status_history_lead_id"), table_name="lead_status_history")
    op.drop_table("lead_status_history")
    op.drop_index(op.f("ix_lead_notes_tenant_id"), table_name="lead_notes")
    op.drop_index(op.f("ix_lead_notes_lead_id"), table_name="lead_notes")
    op.drop_table("lead_notes")
    op.drop_index(op.f("ix_lead_assignments_tenant_id"), table_name="lead_assignments")
    op.drop_index(op.f("ix_lead_assignments_lead_id"), table_name="lead_assignments")
    op.drop_table("lead_assignments")
    op.drop_index(op.f("ix_saved_lead_views_tenant_id"), table_name="saved_lead_views")
    op.drop_table("saved_lead_views")
    # ### end Alembic commands ###
