"""milestone_7_self_serve_signup_and_onboarding

Revision ID: a42bb8826952
Revises: 2c23e5e7d97e
Create Date: 2026-07-14 01:56:57.893001

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a42bb8826952"
down_revision: str | None = "2c23e5e7d97e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "signup_attempts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("ip_address", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_signup_attempts_created_at"), "signup_attempts", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_signup_attempts_ip_address"), "signup_attempts", ["ip_address"], unique=False
    )
    op.add_column(
        "tenant_settings",
        sa.Column("onboarding_completed_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tenant_settings", "onboarding_completed_at")
    op.drop_index(op.f("ix_signup_attempts_ip_address"), table_name="signup_attempts")
    op.drop_index(op.f("ix_signup_attempts_created_at"), table_name="signup_attempts")
    op.drop_table("signup_attempts")
    # ### end Alembic commands ###
