"""milestone 2: services, custom fields, qualification, pipeline, leads

Revision ID: c1bf0520626a
Revises: a8b098efb625
Create Date: 2026-07-13 13:28:56.521080

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c1bf0520626a"
down_revision: str | None = "a8b098efb625"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "branches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_branches_tenant_id"), "branches", ["tenant_id"], unique=False)
    op.create_table(
        "custom_field_definitions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("entity_type", sa.String(length=30), nullable=False),
        sa.Column("field_key", sa.String(length=100), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("field_type", sa.String(length=30), nullable=False),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "entity_type", "field_key", name="uq_custom_field_tenant_entity_key"
        ),
    )
    op.create_index(
        op.f("ix_custom_field_definitions_tenant_id"),
        "custom_field_definitions",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "loss_reasons",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=150), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_loss_reasons_tenant_id"), "loss_reasons", ["tenant_id"], unique=False)
    op.create_table(
        "pipeline_stages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_won", sa.Boolean(), nullable=False),
        sa.Column("is_lost", sa.Boolean(), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "slug", name="uq_pipeline_stage_tenant_slug"),
    )
    op.create_index(
        op.f("ix_pipeline_stages_tenant_id"), "pipeline_stages", ["tenant_id"], unique=False
    )
    op.create_table(
        "public_form_attempts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("ip_address", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_public_form_attempts_created_at"),
        "public_form_attempts",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_public_form_attempts_ip_address"),
        "public_form_attempts",
        ["ip_address"],
        unique=False,
    )
    op.create_index(
        op.f("ix_public_form_attempts_tenant_id"),
        "public_form_attempts",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "qualification_forms",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_qualification_forms_tenant_id"), "qualification_forms", ["tenant_id"], unique=False
    )
    op.create_table(
        "service_categories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_service_categories_tenant_id"), "service_categories", ["tenant_id"], unique=False
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("color", sa.String(length=7), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "name", name="uq_tag_tenant_name"),
    )
    op.create_index(op.f("ix_tags_tenant_id"), "tags", ["tenant_id"], unique=False)
    op.create_table(
        "custom_field_options",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("field_definition_id", sa.UUID(), nullable=False),
        sa.Column("value", sa.String(length=100), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["field_definition_id"], ["custom_field_definitions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_custom_field_options_field_definition_id"),
        "custom_field_options",
        ["field_definition_id"],
        unique=False,
    )
    op.create_table(
        "qualification_questions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("form_id", sa.UUID(), nullable=False),
        sa.Column("field_definition_id", sa.UUID(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("help_text", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["field_definition_id"], ["custom_field_definitions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["form_id"], ["qualification_forms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_qualification_questions_form_id"),
        "qualification_questions",
        ["form_id"],
        unique=False,
    )
    op.create_table(
        "services",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("slug", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["category_id"], ["service_categories.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "slug", name="uq_service_tenant_slug"),
    )
    op.create_index(op.f("ix_services_tenant_id"), "services", ["tenant_id"], unique=False)
    op.create_table(
        "leads",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("reference_number", sa.String(length=20), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("company", sa.String(length=200), nullable=True),
        sa.Column("service_id", sa.UUID(), nullable=True),
        sa.Column("branch_id", sa.UUID(), nullable=True),
        sa.Column("stage_id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("score_reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("estimated_value", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("assigned_membership_id", sa.UUID(), nullable=True),
        sa.Column("preferred_contact_method", sa.String(length=20), nullable=True),
        sa.Column("next_follow_up_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consent_given", sa.Boolean(), nullable=False),
        sa.Column("consent_text_shown", sa.Text(), nullable=True),
        sa.Column("consented_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("utm_source", sa.String(length=200), nullable=True),
        sa.Column("utm_medium", sa.String(length=200), nullable=True),
        sa.Column("utm_campaign", sa.String(length=200), nullable=True),
        sa.Column("utm_term", sa.String(length=200), nullable=True),
        sa.Column("utm_content", sa.String(length=200), nullable=True),
        sa.Column("referrer_url", sa.Text(), nullable=True),
        sa.Column("loss_reason_id", sa.UUID(), nullable=True),
        sa.Column("is_possible_duplicate", sa.Boolean(), nullable=False),
        sa.Column("duplicate_of_lead_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_membership_id"], ["memberships.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["duplicate_of_lead_id"], ["leads.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["loss_reason_id"], ["loss_reasons.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["service_id"], ["services.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["stage_id"], ["pipeline_stages.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "reference_number", name="uq_lead_tenant_reference"),
    )
    op.create_index(
        op.f("ix_leads_assigned_membership_id"), "leads", ["assigned_membership_id"], unique=False
    )
    op.create_index(op.f("ix_leads_service_id"), "leads", ["service_id"], unique=False)
    op.create_index(op.f("ix_leads_stage_id"), "leads", ["stage_id"], unique=False)
    op.create_index(op.f("ix_leads_tenant_id"), "leads", ["tenant_id"], unique=False)
    op.create_table(
        "qualification_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column("depends_on_question_id", sa.UUID(), nullable=False),
        sa.Column("operator", sa.String(length=20), nullable=False),
        sa.Column("depends_on_value", sa.String(length=200), nullable=False),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["depends_on_question_id"], ["qualification_questions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["question_id"], ["qualification_questions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_qualification_rules_question_id"),
        "qualification_rules",
        ["question_id"],
        unique=False,
    )
    op.create_table(
        "idempotency_keys",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=200), nullable=False),
        sa.Column("request_hash", sa.Text(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "key", name="uq_idempotency_tenant_key"),
    )
    op.create_index(
        op.f("ix_idempotency_keys_tenant_id"), "idempotency_keys", ["tenant_id"], unique=False
    )
    op.create_table(
        "lead_answers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("question_id", sa.UUID(), nullable=True),
        sa.Column("question_label_snapshot", sa.String(length=200), nullable=False),
        sa.Column("field_type_snapshot", sa.String(length=30), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["question_id"], ["qualification_questions.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_lead_answers_lead_id"), "lead_answers", ["lead_id"], unique=False)
    op.create_table(
        "lead_notes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("author_user_id", sa.UUID(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["author_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_lead_notes_lead_id"), "lead_notes", ["lead_id"], unique=False)
    op.create_table(
        "lead_stage_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("from_stage_id", sa.UUID(), nullable=True),
        sa.Column("to_stage_id", sa.UUID(), nullable=False),
        sa.Column("changed_by_user_id", sa.UUID(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["changed_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["from_stage_id"], ["pipeline_stages.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["to_stage_id"], ["pipeline_stages.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_lead_stage_history_lead_id"), "lead_stage_history", ["lead_id"], unique=False
    )
    op.create_table(
        "lead_tags",
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("tag_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("lead_id", "tag_id"),
    )
    # server_default backfills existing tenant rows with a random UUID;
    # dropped after backfill since new rows always get one from the ORM.
    op.add_column(
        "tenants",
        sa.Column(
            "public_key", sa.UUID(), nullable=False, server_default=sa.text("gen_random_uuid()")
        ),
    )
    op.alter_column("tenants", "public_key", server_default=None)
    op.create_index(op.f("ix_tenants_public_key"), "tenants", ["public_key"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tenants_public_key"), table_name="tenants")
    op.drop_column("tenants", "public_key")
    op.drop_table("lead_tags")
    op.drop_index(op.f("ix_lead_stage_history_lead_id"), table_name="lead_stage_history")
    op.drop_table("lead_stage_history")
    op.drop_index(op.f("ix_lead_notes_lead_id"), table_name="lead_notes")
    op.drop_table("lead_notes")
    op.drop_index(op.f("ix_lead_answers_lead_id"), table_name="lead_answers")
    op.drop_table("lead_answers")
    op.drop_index(op.f("ix_idempotency_keys_tenant_id"), table_name="idempotency_keys")
    op.drop_table("idempotency_keys")
    op.drop_index(op.f("ix_qualification_rules_question_id"), table_name="qualification_rules")
    op.drop_table("qualification_rules")
    op.drop_index(op.f("ix_leads_tenant_id"), table_name="leads")
    op.drop_index(op.f("ix_leads_stage_id"), table_name="leads")
    op.drop_index(op.f("ix_leads_service_id"), table_name="leads")
    op.drop_index(op.f("ix_leads_assigned_membership_id"), table_name="leads")
    op.drop_table("leads")
    op.drop_index(op.f("ix_services_tenant_id"), table_name="services")
    op.drop_table("services")
    op.drop_index(op.f("ix_qualification_questions_form_id"), table_name="qualification_questions")
    op.drop_table("qualification_questions")
    op.drop_index(
        op.f("ix_custom_field_options_field_definition_id"), table_name="custom_field_options"
    )
    op.drop_table("custom_field_options")
    op.drop_index(op.f("ix_tags_tenant_id"), table_name="tags")
    op.drop_table("tags")
    op.drop_index(op.f("ix_service_categories_tenant_id"), table_name="service_categories")
    op.drop_table("service_categories")
    op.drop_index(op.f("ix_qualification_forms_tenant_id"), table_name="qualification_forms")
    op.drop_table("qualification_forms")
    op.drop_index(op.f("ix_public_form_attempts_tenant_id"), table_name="public_form_attempts")
    op.drop_index(op.f("ix_public_form_attempts_ip_address"), table_name="public_form_attempts")
    op.drop_index(op.f("ix_public_form_attempts_created_at"), table_name="public_form_attempts")
    op.drop_table("public_form_attempts")
    op.drop_index(op.f("ix_pipeline_stages_tenant_id"), table_name="pipeline_stages")
    op.drop_table("pipeline_stages")
    op.drop_index(op.f("ix_loss_reasons_tenant_id"), table_name="loss_reasons")
    op.drop_table("loss_reasons")
    op.drop_index(
        op.f("ix_custom_field_definitions_tenant_id"), table_name="custom_field_definitions"
    )
    op.drop_table("custom_field_definitions")
    op.drop_index(op.f("ix_branches_tenant_id"), table_name="branches")
    op.drop_table("branches")
    # ### end Alembic commands ###
