"""add csv import tables

Revision ID: eda5a5ae04d5
Revises: 6ab02302f662
Create Date: 2026-07-18 22:59:29.034074

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "eda5a5ae04d5"
down_revision: str | Sequence[str] | None = "6ab02302f662"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "csv_imports",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("requested_by_user_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("object_key", sa.String(length=500), nullable=False),
        sa.Column("original_filename", sa.String(length=300), nullable=False),
        sa.Column("detected_headers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sample_rows", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("column_mapping", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("imported_count", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("reservation_id", sa.UUID(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.String(length=2000), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["requested_by_user_id"],
            ["users.id"],
            name=op.f("fk_csv_imports_requested_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["credit_reservations.id"],
            name=op.f("fk_csv_imports_reservation_id_credit_reservations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_csv_imports_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_csv_imports")),
        sa.UniqueConstraint("tenant_id", "id", name="uq_csv_imports_tenant_id_id"),
    )
    op.create_index(op.f("ix_csv_imports_status"), "csv_imports", ["status"], unique=False)
    op.create_index(op.f("ix_csv_imports_tenant_id"), "csv_imports", ["tenant_id"], unique=False)
    op.create_table(
        "csv_import_errors",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("csv_import_id", sa.UUID(), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("message", sa.String(length=2000), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "csv_import_id"],
            ["csv_imports.tenant_id", "csv_imports.id"],
            name="fk_csv_import_errors_tenant_csv_import",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_csv_import_errors")),
    )
    op.create_index(
        op.f("ix_csv_import_errors_csv_import_id"),
        "csv_import_errors",
        ["csv_import_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_csv_import_errors_tenant_id"), "csv_import_errors", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###

    # Row Level Security, same pattern as every prior milestone's migration.
    using_clause = (
        "tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid "
        "OR current_setting('app.platform_bypass', true) = 'true'"
    )
    for table in ["csv_imports", "csv_import_errors"]:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING ({using_clause}) WITH CHECK ({using_clause})"
        )


def downgrade() -> None:
    """Downgrade schema."""
    for table in ["csv_import_errors", "csv_imports"]:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_csv_import_errors_tenant_id"), table_name="csv_import_errors")
    op.drop_index(op.f("ix_csv_import_errors_csv_import_id"), table_name="csv_import_errors")
    op.drop_table("csv_import_errors")
    op.drop_index(op.f("ix_csv_imports_tenant_id"), table_name="csv_imports")
    op.drop_index(op.f("ix_csv_imports_status"), table_name="csv_imports")
    op.drop_table("csv_imports")
    # ### end Alembic commands ###
