"""add platform role assignments, mfa scaffold fields

Revision ID: fe3f382fcffa
Revises: 8a1f2c3d4e5f
Create Date: 2026-07-17 10:52:25.201427

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fe3f382fcffa"
down_revision: str | Sequence[str] | None = "8a1f2c3d4e5f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "platform_role_assignments",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_platform_role_assignments_role_id_roles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_platform_role_assignments_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_role_assignments")),
        sa.UniqueConstraint("user_id", "role_id", name="uq_platform_role_assignments_user_role"),
    )
    op.create_index(
        op.f("ix_platform_role_assignments_role_id"),
        "platform_role_assignments",
        ["role_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_platform_role_assignments_user_id"),
        "platform_role_assignments",
        ["user_id"],
        unique=False,
    )
    op.add_column(
        "sessions",
        sa.Column(
            "assurance_level", sa.String(length=20), nullable=False, server_default="standard"
        ),
    )
    op.alter_column("sessions", "assurance_level", server_default=None)
    op.add_column(
        "users", sa.Column("mfa_enabled", sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.alter_column("users", "mfa_enabled", server_default=None)
    # ### end Alembic commands ###

    # Defense-in-depth: even if application code has a bug, the database
    # itself refuses to let a platform_role_assignments row point at a
    # tenant-scoped role (tenant_id IS NOT NULL).
    op.execute(
        """
        CREATE OR REPLACE FUNCTION enforce_platform_role_assignment() RETURNS trigger AS $$
        DECLARE
          role_tenant_id uuid;
        BEGIN
          SELECT tenant_id INTO role_tenant_id FROM roles WHERE id = NEW.role_id;
          IF role_tenant_id IS NOT NULL THEN
            RAISE EXCEPTION 'platform_role_assignments.role_id must reference a platform role (tenant_id IS NULL)';
          END IF;
          RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_platform_role_assignments_check
        BEFORE INSERT OR UPDATE ON platform_role_assignments
        FOR EACH ROW EXECUTE FUNCTION enforce_platform_role_assignment();
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(
        "DROP TRIGGER IF EXISTS trg_platform_role_assignments_check ON platform_role_assignments"
    )
    op.execute("DROP FUNCTION IF EXISTS enforce_platform_role_assignment()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "mfa_enabled")
    op.drop_column("sessions", "assurance_level")
    op.drop_index(
        op.f("ix_platform_role_assignments_user_id"), table_name="platform_role_assignments"
    )
    op.drop_index(
        op.f("ix_platform_role_assignments_role_id"), table_name="platform_role_assignments"
    )
    op.drop_table("platform_role_assignments")
    # ### end Alembic commands ###
