from __future__ import annotations

import pytest

from aura_core.executive import ExecutiveIntelligence, GoalEngine
from aura_core.memory import MemoryStore
from aura_core.providers import ModelRouter, OllamaProvider
from aura_core.tasks import TaskEngine


def make_stack(tmp_path):
    db_url = f"sqlite:///{tmp_path}/executive.db"
    goals = GoalEngine(db_url)
    tasks = TaskEngine(db_url)
    memory = MemoryStore(db_url)
    unreachable = OllamaProvider(host="http://127.0.0.1:1", model="llama3.1")
    router = ModelRouter(primary=unreachable, allow_test_fallback=True)
    return ExecutiveIntelligence(goals, tasks, memory, router), goals, tasks, memory


@pytest.mark.asyncio
async def test_review_goal_produces_a_decision_and_a_task(tmp_path):
    executive, goals, tasks, memory = make_stack(tmp_path)
    goal = goals.create(
        "Grow Gridkeep revenue", success_metric="MRR >= 100000 AED",
        budget={"marketing_aed_per_month": 5000}, stop_conditions=["pause if CAC too high"],
    )
    goals.activate(goal.id)

    outcome = await executive.review_goal(goals.get(goal.id))

    assert outcome.error is None
    assert outcome.decision is not None
    assert outcome.task_id is not None

    decisions = memory.decisions_for_goal(goal.id)
    assert len(decisions) == 1
    assert decisions[0].reasoning == "generated by the Model Router during a scheduled goal review"

    task = tasks.get(outcome.task_id)
    assert task.task_type == "execute_goal_step"
    assert task.status == "QUEUED"


@pytest.mark.asyncio
async def test_review_goal_marks_the_goal_reviewed(tmp_path):
    executive, goals, _tasks, _memory = make_stack(tmp_path)
    goal = goals.create(
        "g", success_metric="m", budget={}, stop_conditions=["s"], review_interval_seconds=0,
    )
    goals.activate(goal.id)
    assert goals.get(goal.id).last_reviewed_at is None

    await executive.review_goal(goals.get(goal.id))

    assert goals.get(goal.id).last_reviewed_at is not None


@pytest.mark.asyncio
async def test_run_review_cycle_covers_every_due_goal_and_only_those(tmp_path):
    executive, goals, _tasks, _memory = make_stack(tmp_path)
    due_goal = goals.create(
        "due", success_metric="m", budget={}, stop_conditions=["s"], review_interval_seconds=0,
    )
    not_due_goal = goals.create(
        "not due", success_metric="m", budget={}, stop_conditions=["s"], review_interval_seconds=3600,
    )
    goals.activate(due_goal.id)
    goals.activate(not_due_goal.id)

    outcomes = await executive.run_review_cycle()

    assert [o.goal_id for o in outcomes] == [due_goal.id]
