"""The built-in Capability catalog: one entry per action_type that
already has a real, registered handler somewhere in this codebase
(a connector or a built-in deterministic action) as of this writing.

This is generated by hand from the actual registered handlers, not
aspirational -- every name here is grep-verified against
connectors/*.py, actions/builtins.py, and governance/risk_engine.py's
classification tables. Higher-level, cross-domain requests ("find
customers for Gridkeep", "launch on Instagram") are NOT single
capabilities here -- they're workflows the Universal Planner composes
out of these atomic ones (see planning/universal_planner.py), because
pretending a single "sales.lead_discovery" capability exists with a real
execution implementation, when what actually exists is "browser
navigate/extract" plus "email send" plus a human decision, would be
exactly the fabricated capability this system exists to refuse.

Business-process action_types that ARE risk-classified in risk_engine.py
but have no registered handler anywhere (crm.read, crm.write,
memory.read as a broker action, and every RED-tier action_type --
finance.transfer_large, personnel.hire, security.change_root_policy,
etc.) are deliberately NOT listed here: they are real policy
placeholders for capabilities that don't exist yet, and belong in
CapabilityRegistry's gap-reporting path, not in a catalog implying they
can be executed today.
"""
from __future__ import annotations

from .models import Capability

CAPABILITY_CATALOG: dict[str, Capability] = {
    # -- browser --------------------------------------------------------
    "browser.navigate": Capability(
        name="browser.navigate", domain="browser",
        description="Load a URL in a real (optionally headless) browser session.",
        tools=("Playwright/Chromium",), verification="page load completes without navigation error",
        evidence_kind="final URL and page title", inputs=("url",),
    ),
    "browser.extract_text": Capability(
        name="browser.extract_text", domain="browser",
        description="Extract visible text from the current page or a CSS selector.",
        tools=("Playwright/Chromium",), verification="selector resolves to at least one element",
        evidence_kind="extracted text content", inputs=("selector",),
    ),
    "browser.extract_text_multi": Capability(
        name="browser.extract_text_multi", domain="browser",
        description="Extract text from multiple pages/selectors concurrently.",
        tools=("Playwright/Chromium",), verification="every target resolves or reports its own failure",
        evidence_kind="per-target extracted text", inputs=("targets",),
    ),
    "browser.screenshot": Capability(
        name="browser.screenshot", domain="browser",
        description="Capture a screenshot of the current page.",
        tools=("Playwright/Chromium",), verification="image bytes returned are non-empty and decodable",
        evidence_kind="base64 image data",
    ),
    "browser.download_file": Capability(
        name="browser.download_file", domain="browser",
        description="Trigger and save a real file download from a page.",
        tools=("Playwright/Chromium",), verification="downloaded file exists on disk inside the configured sandbox",
        evidence_kind="saved path and suggested filename", inputs=("url", "save_as"),
    ),
    # -- computer control -------------------------------------------------
    "computer_control.move_mouse": Capability(
        name="computer_control.move_mouse", domain="computer",
        description="Move the mouse pointer to a screen coordinate.",
        tools=("pynput",), verification="pointer position query after the move", inputs=("x", "y"),
    ),
    "computer_control.click": Capability(
        name="computer_control.click", domain="computer",
        description="Click at a screen coordinate.",
        tools=("pynput",), verification="input-injection call completes without error", inputs=("x", "y"),
    ),
    "computer_control.click_element": Capability(
        name="computer_control.click_element", domain="computer",
        description="Find a UI element by name/role/automation_id and click its center.",
        tools=("pynput", "UI Automation provider"),
        verification="element resolved before the click, then the click itself completes",
        inputs=("name", "role", "automation_id"),
    ),
    "computer_control.find_element": Capability(
        name="computer_control.find_element", domain="computer",
        description="Find a UI element by name/role/automation_id without acting on it.",
        tools=("UI Automation provider",), verification="element lookup returns real geometry or an honest no-match",
        inputs=("name", "role", "automation_id"),
    ),
    "computer_control.type_text": Capability(
        name="computer_control.type_text", domain="computer",
        description="Type text via keyboard injection.",
        tools=("pynput",), verification="input-injection call completes without error", inputs=("text",),
    ),
    "computer_control.key_press": Capability(
        name="computer_control.key_press", domain="computer",
        description="Press and release a single key.",
        tools=("pynput",), verification="input-injection call completes without error", inputs=("key",),
    ),
    "computer_control.open_app": Capability(
        name="computer_control.open_app", domain="computer",
        description="Launch a named application.",
        tools=("OS process launch",), verification="process starts without error",
    ),
    "computer_control.system_control": Capability(
        name="computer_control.system_control", domain="computer",
        description="A small set of system-level controls (e.g. mute).",
        tools=("OS APIs",), verification="call completes without error",
    ),
    # -- email ------------------------------------------------------------
    "email.list_messages": Capability(
        name="email.list_messages", domain="email",
        description="List recent messages in a mailbox folder.",
        tools=("IMAP",), verification="real IMAP UID SEARCH/FETCH against the configured server",
        evidence_kind="message summaries with UIDs", inputs=("folder", "limit"),
    ),
    "email.get_message": Capability(
        name="email.get_message", domain="email",
        description="Fetch one message's full content by UID.",
        tools=("IMAP",), verification="real IMAP FETCH returns the message", inputs=("uid",),
    ),
    "email.search_messages": Capability(
        name="email.search_messages", domain="email",
        description="Search a mailbox with an IMAP search criteria string.",
        tools=("IMAP",), verification="real IMAP SEARCH against the configured server", inputs=("criteria",),
    ),
    "email.save_draft": Capability(
        name="email.save_draft", domain="email",
        description="Save a drafted message to the Drafts folder without sending it.",
        tools=("IMAP",), verification="real IMAP APPEND with the \\Draft flag",
        evidence_kind="folder and subject of the saved draft", inputs=("to", "subject", "body", "folder"),
    ),
    "email.send_external": Capability(
        name="email.send_external", domain="email",
        description="Send an email to a real external recipient.",
        tools=("SMTP",), verification="SMTP server accepts the message for delivery",
        evidence_kind="recipient the SMTP server accepted", inputs=("to", "subject", "body"),
    ),
    # -- social -------------------------------------------------------------
    "instagram.publish_post": Capability(
        name="instagram.publish_post", domain="social",
        description="Publish an image post to an Instagram Business account.",
        tools=("Instagram Graph API",), verification="real two-step create-container-then-publish API round trip",
        evidence_kind="final media_id from the Graph API", inputs=("ig_user_id", "image_url", "caption"),
    ),
    "meta.publish_post": Capability(
        name="meta.publish_post", domain="social",
        description="Publish a post to a Facebook Page's feed.",
        tools=("Meta Graph API",), verification="Graph API returns a post id",
        evidence_kind="post id", inputs=("page_id", "body"),
    ),
    "meta.reply_to_comment": Capability(
        name="meta.reply_to_comment", domain="social",
        description="Reply to a comment on a Facebook Page post.",
        tools=("Meta Graph API",), verification="Graph API returns a comment id",
        evidence_kind="comment id", inputs=("comment_id", "body"),
    ),
    "meta.get_page_posts": Capability(
        name="meta.get_page_posts", domain="social",
        description="List a Facebook Page's recent posts.",
        tools=("Meta Graph API",), verification="real Graph API read", inputs=("page_id",),
    ),
    "meta.get_post_comments": Capability(
        name="meta.get_post_comments", domain="social",
        description="List comments on a Facebook Page post.",
        tools=("Meta Graph API",), verification="real Graph API read", inputs=("post_id",),
    ),
    "linkedin.share_post": Capability(
        name="linkedin.share_post", domain="social",
        description="Share a UGC post on LinkedIn.",
        tools=("LinkedIn REST API",), verification="LinkedIn API returns a share id",
        evidence_kind="share id",
    ),
    "linkedin.get_profile": Capability(
        name="linkedin.get_profile", domain="social",
        description="Read the authenticated LinkedIn profile.",
        tools=("LinkedIn REST API",), verification="real LinkedIn API read",
    ),
    "whatsapp.send_message": Capability(
        name="whatsapp.send_message", domain="social",
        description="Send a free-form WhatsApp Cloud API message.",
        tools=("WhatsApp Cloud API",), verification="Cloud API returns a message id",
        evidence_kind="wamid", inputs=("phone_number_id", "body"),
    ),
    "whatsapp.send_template_message": Capability(
        name="whatsapp.send_template_message", domain="social",
        description="Send a pre-approved WhatsApp template message (opens a 24h window).",
        tools=("WhatsApp Cloud API",), verification="Cloud API returns a message id",
        evidence_kind="wamid", inputs=("phone_number_id", "to", "template_name", "language_code", "components"),
    ),
    "whatsapp.send_media_message": Capability(
        name="whatsapp.send_media_message", domain="social",
        description="Send a WhatsApp media message (image/video/audio/document).",
        tools=("WhatsApp Cloud API",), verification="Cloud API returns a message id",
        evidence_kind="wamid", inputs=("phone_number_id", "to", "media_type", "media_id", "media_link", "caption"),
    ),
    "whatsapp.get_phone_number_status": Capability(
        name="whatsapp.get_phone_number_status", domain="social",
        description="Read a WhatsApp Business phone number's status.",
        tools=("WhatsApp Cloud API",), verification="real Cloud API read", inputs=("phone_number_id",),
    ),
    # -- telephony -----------------------------------------------------------
    "telephony.call": Capability(
        name="telephony.call", domain="telephony",
        description="Place an outbound call. Backed by MockTelephonyProvider until a real "
                     "provider (Twilio/SIP) is configured -- see connector status before relying on this.",
        tools=("Twilio/SIP (not yet configured)",), verification="provider call SID + final call status",
        evidence_kind="call record with provider field", inputs=("to", "message"),
    ),
    # -- finance --------------------------------------------------------------
    "finance.prepare_transaction": Capability(
        name="finance.prepare_transaction", domain="finance",
        description="Prepare a draft financial transaction. Never moves real funds -- "
                     "structurally draft-only, not just by policy.",
        tools=("MockPaymentProvider (draft ledger only)",), verification="draft record created with a status of 'drafted'",
        evidence_kind="transaction draft id", inputs=("amount", "currency", "recipient", "memo"),
    ),
    # -- cloud ------------------------------------------------------------------
    "cloud.deploy": Capability(
        name="cloud.deploy", domain="cloud",
        description="Deploy a service version. Backed by MockCloudProvider until a real "
                     "cloud provider is configured -- see connector status before relying on this.",
        tools=("AWS/GCP/Azure/etc. (not yet configured)",), verification="deployment record marked live",
        evidence_kind="deployment id and previous_deployment_id", inputs=("service", "version", "environment"),
    ),
    "cloud.rollback": Capability(
        name="cloud.rollback", domain="cloud",
        description="Roll back to the previous deployment for a service+environment.",
        tools=("AWS/GCP/Azure/etc. (not yet configured)",), verification="previous deployment record restored to live",
        evidence_kind="deployment id", inputs=("deployment_id",),
    ),
    "cloud.get_deployment_status": Capability(
        name="cloud.get_deployment_status", domain="cloud",
        description="Read a deployment's current status.",
        tools=("AWS/GCP/Azure/etc. (not yet configured)",), verification="ledger read", inputs=("deployment_id",),
    ),
    # -- engineering / git --------------------------------------------------------
    "github.list_pull_requests": Capability(
        name="github.list_pull_requests", domain="engineering",
        description="List a repository's pull requests.",
        tools=("GitHub REST API",), verification="real GitHub API read", inputs=("owner", "repo"),
    ),
    "github.get_pull_request": Capability(
        name="github.get_pull_request", domain="engineering",
        description="Read one pull request's details.",
        tools=("GitHub REST API",), verification="real GitHub API read", inputs=("owner", "repo", "number"),
    ),
    "github.list_issues": Capability(
        name="github.list_issues", domain="engineering",
        description="List a repository's issues.",
        tools=("GitHub REST API",), verification="real GitHub API read", inputs=("owner", "repo"),
    ),
    "github.get_issue": Capability(
        name="github.get_issue", domain="engineering",
        description="Read one issue's details.",
        tools=("GitHub REST API",), verification="real GitHub API read", inputs=("owner", "repo", "number"),
    ),
    "github.comment_on_issue": Capability(
        name="github.comment_on_issue", domain="engineering",
        description="Post a comment on a GitHub issue or pull request.",
        tools=("GitHub REST API",), verification="GitHub API returns the created comment",
        evidence_kind="comment id and URL", inputs=("owner", "repo", "number", "body"),
    ),
    "github.get_combined_status": Capability(
        name="github.get_combined_status", domain="engineering",
        description="Read a commit's combined CI status.",
        tools=("GitHub REST API",), verification="real GitHub API read", inputs=("owner", "repo", "ref"),
    ),
    # -- filesystem -----------------------------------------------------------------
    "filesystem.read_file": Capability(
        name="filesystem.read_file", domain="files",
        description="Read a file's contents from within the sandboxed filesystem root.",
        tools=("local filesystem",), verification="file exists and is readable", inputs=("path",),
    ),
    "filesystem.write_file": Capability(
        name="filesystem.write_file", domain="files",
        description="Write a file's contents inside the sandboxed filesystem root.",
        tools=("local filesystem",), verification="file re-read after write matches what was written",
        evidence_kind="bytes written", inputs=("path", "content"),
    ),
    "filesystem.list_dir": Capability(
        name="filesystem.list_dir", domain="files",
        description="List a directory's contents inside the sandboxed filesystem root.",
        tools=("local filesystem",), verification="directory listing succeeds", inputs=("path",),
    ),
    # -- http / research ---------------------------------------------------------------
    "http.get": Capability(
        name="http.get", domain="research",
        description="Make a GET request to an allow-listed host.",
        tools=("HTTP client",), verification="real HTTP response received", inputs=("url",),
    ),
    "http.post": Capability(
        name="http.post", domain="research",
        description="Make a POST request to an allow-listed host.",
        tools=("HTTP client",), verification="real HTTP response received", inputs=("url", "body"),
    ),
    # -- core -----------------------------------------------------------------------------
    "status.read": Capability(
        name="status.read", domain="core",
        description="Read AURA's own capability/connector status.",
        tools=("internal",), verification="direct registry read",
    ),
    "help.read": Capability(
        name="help.read", domain="core",
        description="List available deterministic commands.",
        tools=("internal",), verification="direct registry read",
    ),
    "tasks.read": Capability(
        name="tasks.read", domain="core",
        description="List durable tasks and their status.",
        tools=("internal",), verification="direct database read",
    ),
}
