"""List every Arabic UI string added since a base commit, with its English counterpart where one is adjacent, for native-speaker review.

    uv run python scripts/arabic_qa_checklist.py --base 6498b1f --out docs/ARABIC_QA.md

Nothing here claims the Arabic is correct. Every entry starts as NEEDS_NATIVE_REVIEW. Strings that contain religious terminology
are flagged: they must not be reworded casually, only by someone qualified.
"""
import argparse
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
ARABIC = re.compile(r"[؀-ۿ]")
LITERAL = re.compile(r'"([^"\n]*[؀-ۿ][^"\n]*)"|`([^`\n]*[؀-ۿ][^`\n]*)`')
PAIR = re.compile(r'\?\s*"((?:[^"\\]|\\.)*[؀-ۿ](?:[^"\\]|\\.)*)"\s*:\s*"((?:[^"\\]|\\.)*)"')
OBJECT_PAIR = re.compile(r'en:\s*"((?:[^"\\]|\\.)*)",\s*ar:\s*"((?:[^"\\]|\\.)*)"')
RELIGIOUS = re.compile(r"الحديث|حديث|التفسير|تفسير|الفقه|فقه|العقيدة|عقيدة|السيرة|فتوى|مذهب|المذهب|الحكم|القرآن|القرآنية|تلاوة|القارئ|الصحاب|الأصلي|العلماء|علماء|الشرح|الحاكم|درجات|الثبوت|الشريعة|الصلاة|الزكاة|حلال|حرام")


def added_lines(base: str) -> list[tuple[str, str]]:
    diff = subprocess.run(["git", "diff", "-U0", base, "--", "apps/web/src"], cwd=ROOT, capture_output=True, text=True, check=True).stdout
    out, current = [], ""
    for line in diff.splitlines():
        if line.startswith("+++ b/"):
            current = line[6:]
        elif line.startswith("+") and not line.startswith("+++") and ARABIC.search(line):
            out.append((current, line[1:]))
    return out


GROUP_RULES = (  # first match wins; a heuristic for sorting the review queue, not a statement about the text
    ("HADITH", re.compile(r"حديث|الحديث|درجات|الثبوت")), ("TAFSIR", re.compile(r"تفسير|التفسير")), ("FIQH", re.compile(r"فقه|الفقه|مذهب|المذهب|فتوى|الحكم")),
    ("AQEEDAH", re.compile(r"عقيدة|العقيدة")), ("QURAN", re.compile(r"القرآن|القرآنية|تلاوة|القارئ|آية|سورة")),
    ("SCHOLARSHIP", re.compile(r"العلماء|علماء|مصدر|مصادر|الشرح|الصحاب|السيرة|الأصلي|المراجع")),
    ("DIRECTORY", re.compile(r"مسجد|مساجد|دليل|الدليل|وظيف|فعالية|فعاليات|جمعية|جمعيات|تطوع|خدمات|منظمة|منظمات|الدولة|البلد")),
)


def group_of(arabic: str, file: str) -> str:
    for name, pattern in GROUP_RULES:
        if pattern.search(arabic):
            return name
    return "DIRECTORY" if "directory" in file else "GENERAL_UI"


def collect(base: str) -> dict[str, dict]:
    entries: dict[str, dict] = {}
    for path, line in added_lines(base):
        found = False
        for en, ar in OBJECT_PAIR.findall(line):
            entries.setdefault(ar, {"file": path, "en": en}); found = True
        for ar, en in PAIR.findall(line):
            entries.setdefault(ar, {"file": path, "en": en}); found = True
        if not found:
            for a, b in LITERAL.findall(line):
                text = a or b
                if ARABIC.search(text):
                    entries.setdefault(text, {"file": path, "en": ""})
    return entries


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--base", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--json", help="also write the strings as a review-queue seed (data/arabic-strings.json)")
    args = ap.parse_args()
    entries = collect(args.base)
    if args.json:
        import hashlib
        import json
        seed = [{"key": hashlib.sha1(f"{info['file']}|{ar}".encode()).hexdigest()[:16], "file": info["file"].replace("apps/web/src/", ""), "arabic": ar, "english": info["en"] or None,
                 "group": group_of(ar, info["file"]), "religious_term": bool(RELIGIOUS.search(ar))} for ar, info in sorted(entries.items(), key=lambda kv: (kv[1]["file"], kv[0]))]
        (ROOT / args.json).write_text(json.dumps({"base": args.base, "note": "Seed for the Arabic review queue. Every string starts NEEDS_NATIVE_REVIEW; no reviewer has approved any of it.", "strings": seed},
                                                  ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    rows = sorted(entries.items(), key=lambda kv: (kv[1]["file"], kv[0]))
    out = ["# Arabic QA checklist", "",
           f"Generated by `scripts/arabic_qa_checklist.py` from every Arabic string added to `apps/web/src` since `{args.base}` ({len(rows)} strings).", "",
           "**None of these strings has been reviewed by a native Arabic speaker.** They were written by the assistant that built the interface and must not be treated as correct. "
           "Rows marked **RELIGIOUS TERM** contain theological or technical vocabulary: do not reword them casually; have someone qualified confirm the wording.", "",
           "Review states: `NEEDS_NATIVE_REVIEW` (all, initially), `APPROVED`, `CHANGE_REQUESTED`.", "",
           "| # | File | Arabic | English counterpart | Flag | State |", "|---|---|---|---|---|---|"]
    for i, (ar, info) in enumerate(rows, 1):
        flag = "RELIGIOUS TERM" if RELIGIOUS.search(ar) else ""
        out.append(f"| {i} | `{info['file'].replace('apps/web/src/', '')}` | {ar.replace('|', '/')} | {info['en'].replace('|', '/') or '-'} | {flag} | NEEDS_NATIVE_REVIEW |")
    (ROOT / args.out).write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"{len(rows)} strings, {sum(1 for ar, _ in rows if RELIGIOUS.search(ar))} flagged as religious terms -> {args.out}")


if __name__ == "__main__":
    main()
