"""milestone 4 booking schema

Revision ID: 25ca81e21512
Revises: 9fa62b59def2
Create Date: 2026-07-14 18:00:32.299478

Also widens `email_templates.trigger_event` from VARCHAR(20) to
VARCHAR(30) — the column is `native_enum=False` (a plain string, not a
Postgres ENUM type), so adding the three new booking trigger event
values only required a Python-side enum change plus this width bump,
not a type migration.
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '25ca81e21512'
down_revision: str | None = '9fa62b59def2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_types',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_appointment_types_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointment_types')),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_appointment_types_tenant_name')
    )
    op.create_index(op.f('ix_appointment_types_tenant_id'), 'appointment_types', ['tenant_id'], unique=False)
    op.create_table('availability_exceptions',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_availability_exceptions_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_availability_exceptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_availability_exceptions')),
    sa.UniqueConstraint('tenant_id', 'user_id', 'date', name='uq_availability_exceptions_user_date')
    )
    op.create_index(op.f('ix_availability_exceptions_tenant_id'), 'availability_exceptions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_availability_exceptions_user_id'), 'availability_exceptions', ['user_id'], unique=False)
    op.create_table('staff_availability',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_staff_availability_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_staff_availability_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_availability'))
    )
    op.create_index(op.f('ix_staff_availability_tenant_id'), 'staff_availability', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_staff_availability_user_id'), 'staff_availability', ['user_id'], unique=False)
    op.create_table('appointments',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('staff_user_id', sa.UUID(), nullable=False),
    sa.Column('appointment_type_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='appointment_status', native_enum=False, length=20), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('cancelled_reason', sa.String(length=300), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['appointment_type_id'], ['appointment_types.id'], name=op.f('fk_appointments_appointment_type_id_appointment_types'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_appointments_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_appointments_lead_id_leads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_user_id'], ['users.id'], name=op.f('fk_appointments_staff_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_appointments_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointments'))
    )
    op.create_index(op.f('ix_appointments_appointment_type_id'), 'appointments', ['appointment_type_id'], unique=False)
    op.create_index(op.f('ix_appointments_lead_id'), 'appointments', ['lead_id'], unique=False)
    op.create_index(op.f('ix_appointments_staff_user_id'), 'appointments', ['staff_user_id'], unique=False)
    op.create_index(op.f('ix_appointments_starts_at'), 'appointments', ['starts_at'], unique=False)
    op.create_index(op.f('ix_appointments_tenant_id'), 'appointments', ['tenant_id'], unique=False)
    op.alter_column('email_templates', 'trigger_event',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('MANUAL', 'LEAD_CREATED', 'LEAD_ASSIGNED', 'STAGE_CHANGED', 'TASK_REMINDER', 'APPOINTMENT_BOOKED', 'APPOINTMENT_REMINDER', 'APPOINTMENT_CANCELLED', name='email_trigger_event', native_enum=False, length=30),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_templates', 'trigger_event',
               existing_type=sa.Enum('MANUAL', 'LEAD_CREATED', 'LEAD_ASSIGNED', 'STAGE_CHANGED', 'TASK_REMINDER', 'APPOINTMENT_BOOKED', 'APPOINTMENT_REMINDER', 'APPOINTMENT_CANCELLED', name='email_trigger_event', native_enum=False, length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_index(op.f('ix_appointments_tenant_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_starts_at'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_staff_user_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_lead_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_type_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_staff_availability_user_id'), table_name='staff_availability')
    op.drop_index(op.f('ix_staff_availability_tenant_id'), table_name='staff_availability')
    op.drop_table('staff_availability')
    op.drop_index(op.f('ix_availability_exceptions_user_id'), table_name='availability_exceptions')
    op.drop_index(op.f('ix_availability_exceptions_tenant_id'), table_name='availability_exceptions')
    op.drop_table('availability_exceptions')
    op.drop_index(op.f('ix_appointment_types_tenant_id'), table_name='appointment_types')
    op.drop_table('appointment_types')
    # ### end Alembic commands ###
