"""milestone 5 workflow automation schema

Revision ID: 4f265a2eb695
Revises: 6900c997221c
Create Date: 2026-07-14 18:27:46.375524

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '4f265a2eb695'
down_revision: str | None = '6900c997221c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflows',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('trigger_event', sa.Enum('LEAD_CREATED', 'STAGE_CHANGED', 'SCORE_THRESHOLD_REACHED', 'TAG_ADDED', 'APPOINTMENT_BOOKED', 'APPOINTMENT_COMPLETED', name='workflow_trigger_event', native_enum=False, length=30), nullable=False),
    sa.Column('trigger_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_workflows_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflows'))
    )
    op.create_index(op.f('ix_workflows_tenant_id'), 'workflows', ['tenant_id'], unique=False)
    op.create_table('workflow_steps',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('delay_minutes', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('SEND_EMAIL_TEMPLATE', 'CREATE_TASK', 'CHANGE_STAGE', 'ADD_TAG', name='workflow_action_type', native_enum=False, length=30), nullable=False),
    sa.Column('action_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_workflow_steps_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name=op.f('fk_workflow_steps_workflow_id_workflows'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_steps'))
    )
    op.create_index(op.f('ix_workflow_steps_tenant_id'), 'workflow_steps', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_workflow_steps_workflow_id'), 'workflow_steps', ['workflow_id'], unique=False)
    op.create_table('workflow_runs',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'CANCELLED', 'FAILED', name='workflow_run_status', native_enum=False, length=20), nullable=False),
    sa.Column('current_step_index', sa.Integer(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_workflow_runs_lead_id_leads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_workflow_runs_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name=op.f('fk_workflow_runs_workflow_id_workflows'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_runs'))
    )
    op.create_index(op.f('ix_workflow_runs_lead_id'), 'workflow_runs', ['lead_id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_next_run_at'), 'workflow_runs', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_workflow_runs_tenant_id'), 'workflow_runs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_workflow_id'), 'workflow_runs', ['workflow_id'], unique=False)
    op.create_table('workflow_step_logs',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('workflow_run_id', sa.UUID(), nullable=False),
    sa.Column('step_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('EXECUTED', 'FAILED', 'SKIPPED', name='workflow_step_log_status', native_enum=False, length=20), nullable=False),
    sa.Column('result_summary', sa.Text(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['workflow_steps.id'], name=op.f('fk_workflow_step_logs_step_id_workflow_steps'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_workflow_step_logs_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], name=op.f('fk_workflow_step_logs_workflow_run_id_workflow_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_step_logs'))
    )
    op.create_index(op.f('ix_workflow_step_logs_tenant_id'), 'workflow_step_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_workflow_step_logs_workflow_run_id'), 'workflow_step_logs', ['workflow_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_step_logs_workflow_run_id'), table_name='workflow_step_logs')
    op.drop_index(op.f('ix_workflow_step_logs_tenant_id'), table_name='workflow_step_logs')
    op.drop_table('workflow_step_logs')
    op.drop_index(op.f('ix_workflow_runs_workflow_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_tenant_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_next_run_at'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_lead_id'), table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_index(op.f('ix_workflow_steps_workflow_id'), table_name='workflow_steps')
    op.drop_index(op.f('ix_workflow_steps_tenant_id'), table_name='workflow_steps')
    op.drop_table('workflow_steps')
    op.drop_index(op.f('ix_workflows_tenant_id'), table_name='workflows')
    op.drop_table('workflows')
    # ### end Alembic commands ###
