"""add tenant capture tokens

Revision ID: 80b63d28fe69
Revises: 45ce592d6cd5
Create Date: 2026-07-14 12:31:16.848290

Backfills one capture token per pre-existing tenant so tenants created
before this migration aren't left without a public lead-capture URL.
"""
import secrets
import uuid
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "80b63d28fe69"
down_revision: str | None = "45ce592d6cd5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_capture_tokens',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_capture_tokens_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_capture_tokens')),
    sa.UniqueConstraint('token', name='uq_tenant_capture_tokens_token')
    )
    op.create_index(op.f('ix_tenant_capture_tokens_tenant_id'), 'tenant_capture_tokens', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tenant_capture_tokens_token'), 'tenant_capture_tokens', ['token'], unique=False)
    # ### end Alembic commands ###

    connection = op.get_bind()
    tenant_ids = connection.execute(sa.text("SELECT id FROM tenants")).scalars().all()
    for tenant_id in tenant_ids:
        connection.execute(
            sa.text(
                "INSERT INTO tenant_capture_tokens (id, tenant_id, token, is_active, created_at, updated_at) "
                "VALUES (:id, :tenant_id, :token, true, now(), now())"
            ),
            {"id": str(uuid.uuid4()), "tenant_id": str(tenant_id), "token": secrets.token_urlsafe(24)},
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_capture_tokens_token'), table_name='tenant_capture_tokens')
    op.drop_index(op.f('ix_tenant_capture_tokens_tenant_id'), table_name='tenant_capture_tokens')
    op.drop_table('tenant_capture_tokens')
    # ### end Alembic commands ###
