"""milestone 8 deadlines and portal schema

Revision ID: a8d00229e9e1
Revises: 940c9dc6be34
Create Date: 2026-07-15 05:50:24.102479

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'a8d00229e9e1'
down_revision: str | None = '940c9dc6be34'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deadlines',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'COMPLETED', name='deadline_status', native_enum=False, length=20), nullable=False),
    sa.Column('recurrence_interval_days', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_deadlines_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_deadlines_lead_id_leads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_deadlines_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deadlines'))
    )
    op.create_index(op.f('ix_deadlines_lead_id'), 'deadlines', ['lead_id'], unique=False)
    op.create_index(op.f('ix_deadlines_tenant_id'), 'deadlines', ['tenant_id'], unique=False)
    op.create_table('portal_accounts',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_portal_accounts_lead_id_leads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_portal_accounts_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_accounts')),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_portal_accounts_tenant_email'),
    sa.UniqueConstraint('tenant_id', 'lead_id', name='uq_portal_accounts_tenant_lead')
    )
    op.create_index(op.f('ix_portal_accounts_email'), 'portal_accounts', ['email'], unique=False)
    op.create_index(op.f('ix_portal_accounts_lead_id'), 'portal_accounts', ['lead_id'], unique=False)
    op.create_index(op.f('ix_portal_accounts_tenant_id'), 'portal_accounts', ['tenant_id'], unique=False)
    op.create_table('portal_invitations',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], name=op.f('fk_portal_invitations_invited_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_portal_invitations_lead_id_leads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_portal_invitations_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_invitations'))
    )
    op.create_index(op.f('ix_portal_invitations_email'), 'portal_invitations', ['email'], unique=False)
    op.create_index(op.f('ix_portal_invitations_lead_id'), 'portal_invitations', ['lead_id'], unique=False)
    op.create_index(op.f('ix_portal_invitations_tenant_id'), 'portal_invitations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_portal_invitations_token_hash'), 'portal_invitations', ['token_hash'], unique=True)
    op.create_table('portal_password_reset_tokens',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('portal_account_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['portal_account_id'], ['portal_accounts.id'], name=op.f('fk_portal_password_reset_tokens_portal_account_id_portal_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_portal_password_reset_tokens_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_password_reset_tokens'))
    )
    op.create_index(op.f('ix_portal_password_reset_tokens_portal_account_id'), 'portal_password_reset_tokens', ['portal_account_id'], unique=False)
    op.create_index(op.f('ix_portal_password_reset_tokens_tenant_id'), 'portal_password_reset_tokens', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_portal_password_reset_tokens_token_hash'), 'portal_password_reset_tokens', ['token_hash'], unique=True)
    op.create_table('portal_sessions',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('portal_account_id', sa.UUID(), nullable=False),
    sa.Column('session_token_hash', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['portal_account_id'], ['portal_accounts.id'], name=op.f('fk_portal_sessions_portal_account_id_portal_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_portal_sessions_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_sessions'))
    )
    op.create_index(op.f('ix_portal_sessions_portal_account_id'), 'portal_sessions', ['portal_account_id'], unique=False)
    op.create_index(op.f('ix_portal_sessions_session_token_hash'), 'portal_sessions', ['session_token_hash'], unique=True)
    op.create_index(op.f('ix_portal_sessions_tenant_id'), 'portal_sessions', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portal_sessions_tenant_id'), table_name='portal_sessions')
    op.drop_index(op.f('ix_portal_sessions_session_token_hash'), table_name='portal_sessions')
    op.drop_index(op.f('ix_portal_sessions_portal_account_id'), table_name='portal_sessions')
    op.drop_table('portal_sessions')
    op.drop_index(op.f('ix_portal_password_reset_tokens_token_hash'), table_name='portal_password_reset_tokens')
    op.drop_index(op.f('ix_portal_password_reset_tokens_tenant_id'), table_name='portal_password_reset_tokens')
    op.drop_index(op.f('ix_portal_password_reset_tokens_portal_account_id'), table_name='portal_password_reset_tokens')
    op.drop_table('portal_password_reset_tokens')
    op.drop_index(op.f('ix_portal_invitations_token_hash'), table_name='portal_invitations')
    op.drop_index(op.f('ix_portal_invitations_tenant_id'), table_name='portal_invitations')
    op.drop_index(op.f('ix_portal_invitations_lead_id'), table_name='portal_invitations')
    op.drop_index(op.f('ix_portal_invitations_email'), table_name='portal_invitations')
    op.drop_table('portal_invitations')
    op.drop_index(op.f('ix_portal_accounts_tenant_id'), table_name='portal_accounts')
    op.drop_index(op.f('ix_portal_accounts_lead_id'), table_name='portal_accounts')
    op.drop_index(op.f('ix_portal_accounts_email'), table_name='portal_accounts')
    op.drop_table('portal_accounts')
    op.drop_index(op.f('ix_deadlines_tenant_id'), table_name='deadlines')
    op.drop_index(op.f('ix_deadlines_lead_id'), table_name='deadlines')
    op.drop_table('deadlines')
    # ### end Alembic commands ###
