"""milestone 3 scoring assignment communications schema

Revision ID: c8f73ca17737
Revises: 80b63d28fe69
Create Date: 2026-07-14 13:28:08.735201

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'c8f73ca17737'
down_revision: str | None = '80b63d28fe69'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment_rules',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('strategy', sa.Enum('ROUND_ROBIN', 'SERVICE_BASED', 'PRIORITY_BASED', name='assignment_strategy', native_enum=False, length=20), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('eligible_user_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_assignment_rules_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assignment_rules'))
    )
    op.create_index(op.f('ix_assignment_rules_tenant_id'), 'assignment_rules', ['tenant_id'], unique=False)
    op.create_table('email_templates',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('trigger_event', sa.Enum('MANUAL', 'LEAD_CREATED', 'LEAD_ASSIGNED', 'STAGE_CHANGED', 'TASK_REMINDER', name='email_trigger_event', native_enum=False, length=20), nullable=False),
    sa.Column('trigger_stage_outcome', sa.String(length=10), nullable=True),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_email_templates_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_templates'))
    )
    op.create_index(op.f('ix_email_templates_tenant_id'), 'email_templates', ['tenant_id'], unique=False)
    op.create_table('scoring_rules',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('field', sa.String(length=150), nullable=False),
    sa.Column('operator', sa.Enum('EQUALS', 'NOT_EQUALS', 'CONTAINS', 'GREATER_THAN', 'LESS_THAN', 'IS_SET', 'IN', name='scoring_operator', native_enum=False, length=20), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_scoring_rules_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scoring_rules'))
    )
    op.create_index(op.f('ix_scoring_rules_tenant_id'), 'scoring_rules', ['tenant_id'], unique=False)
    op.create_table('scoring_settings',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('hot_threshold', sa.Integer(), nullable=False),
    sa.Column('warm_threshold', sa.Integer(), nullable=False),
    sa.Column('auto_priority', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_scoring_settings_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scoring_settings')),
    sa.UniqueConstraint('tenant_id', name='uq_scoring_settings_tenant')
    )
    op.create_index(op.f('ix_scoring_settings_tenant_id'), 'scoring_settings', ['tenant_id'], unique=False)
    op.create_table('assignment_rule_round_robin_state',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('last_assigned_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['assignment_rules.id'], name=op.f('fk_assignment_rule_round_robin_state_rule_id_assignment_rules'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_assignment_rule_round_robin_state_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assignment_rule_round_robin_state')),
    sa.UniqueConstraint('rule_id', name='uq_assignment_rrs_rule')
    )
    op.create_index(op.f('ix_assignment_rule_round_robin_state_rule_id'), 'assignment_rule_round_robin_state', ['rule_id'], unique=False)
    op.create_index(op.f('ix_assignment_rule_round_robin_state_tenant_id'), 'assignment_rule_round_robin_state', ['tenant_id'], unique=False)
    op.create_table('email_delivery_logs',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('recipient', sa.String(length=254), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='email_delivery_status', native_enum=False, length=20), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_email_delivery_logs_lead_id_leads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['email_templates.id'], name=op.f('fk_email_delivery_logs_template_id_email_templates'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_email_delivery_logs_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_delivery_logs'))
    )
    op.create_index(op.f('ix_email_delivery_logs_lead_id'), 'email_delivery_logs', ['lead_id'], unique=False)
    op.create_index(op.f('ix_email_delivery_logs_template_id'), 'email_delivery_logs', ['template_id'], unique=False)
    op.create_index(op.f('ix_email_delivery_logs_tenant_id'), 'email_delivery_logs', ['tenant_id'], unique=False)
    op.create_table('lead_score_logs',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_lead_score_logs_lead_id_leads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_lead_score_logs_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_score_logs'))
    )
    op.create_index(op.f('ix_lead_score_logs_created_at'), 'lead_score_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_lead_score_logs_lead_id'), 'lead_score_logs', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_score_logs_tenant_id'), 'lead_score_logs', ['tenant_id'], unique=False)
    # server_default required: `leads` already has rows (demo/seed data)
    # by the time this migration runs, so a bare NOT NULL ADD COLUMN would
    # fail on them.
    op.add_column('leads', sa.Column('priority_locked', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('tasks', sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'reminder_sent_at')
    op.drop_column('leads', 'priority_locked')
    op.drop_index(op.f('ix_lead_score_logs_tenant_id'), table_name='lead_score_logs')
    op.drop_index(op.f('ix_lead_score_logs_lead_id'), table_name='lead_score_logs')
    op.drop_index(op.f('ix_lead_score_logs_created_at'), table_name='lead_score_logs')
    op.drop_table('lead_score_logs')
    op.drop_index(op.f('ix_email_delivery_logs_tenant_id'), table_name='email_delivery_logs')
    op.drop_index(op.f('ix_email_delivery_logs_template_id'), table_name='email_delivery_logs')
    op.drop_index(op.f('ix_email_delivery_logs_lead_id'), table_name='email_delivery_logs')
    op.drop_table('email_delivery_logs')
    op.drop_index(op.f('ix_assignment_rule_round_robin_state_tenant_id'), table_name='assignment_rule_round_robin_state')
    op.drop_index(op.f('ix_assignment_rule_round_robin_state_rule_id'), table_name='assignment_rule_round_robin_state')
    op.drop_table('assignment_rule_round_robin_state')
    op.drop_index(op.f('ix_scoring_settings_tenant_id'), table_name='scoring_settings')
    op.drop_table('scoring_settings')
    op.drop_index(op.f('ix_scoring_rules_tenant_id'), table_name='scoring_rules')
    op.drop_table('scoring_rules')
    op.drop_index(op.f('ix_email_templates_tenant_id'), table_name='email_templates')
    op.drop_table('email_templates')
    op.drop_index(op.f('ix_assignment_rules_tenant_id'), table_name='assignment_rules')
    op.drop_table('assignment_rules')
    # ### end Alembic commands ###
