"""milestone 7 documents and onboarding schema

Revision ID: d71e840aed0d
Revises: 476edb3b5396
Create Date: 2026-07-15 05:15:22.474979

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'd71e840aed0d'
down_revision: str | None = '476edb3b5396'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_templates',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_onboarding_templates_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_onboarding_templates')),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_onboarding_templates_tenant_name')
    )
    op.create_index(op.f('ix_onboarding_templates_tenant_id'), 'onboarding_templates', ['tenant_id'], unique=False)
    op.create_table('onboarding_template_steps',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.Enum('TASK', 'DOCUMENT_REQUEST', name='onboarding_step_type', native_enum=False, length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('due_in_days', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['onboarding_templates.id'], name=op.f('fk_onboarding_template_steps_template_id_onboarding_templates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_onboarding_template_steps_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_onboarding_template_steps'))
    )
    op.create_index(op.f('ix_onboarding_template_steps_template_id'), 'onboarding_template_steps', ['template_id'], unique=False)
    op.create_index(op.f('ix_onboarding_template_steps_tenant_id'), 'onboarding_template_steps', ['tenant_id'], unique=False)
    op.create_table('document_requests',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'UPLOADED', 'APPROVED', 'REJECTED', name='document_request_status', native_enum=False, length=20), nullable=False),
    sa.Column('public_token', sa.String(length=64), nullable=True),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_document_requests_lead_id_leads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_document_requests_requested_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_document_requests_reviewed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_document_requests_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_requests')),
    sa.UniqueConstraint('public_token', name='uq_document_requests_public_token')
    )
    op.create_index(op.f('ix_document_requests_lead_id'), 'document_requests', ['lead_id'], unique=False)
    op.create_index(op.f('ix_document_requests_public_token'), 'document_requests', ['public_token'], unique=False)
    op.create_index(op.f('ix_document_requests_tenant_id'), 'document_requests', ['tenant_id'], unique=False)
    op.create_table('onboarding_cases',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='onboarding_case_status', native_enum=False, length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_onboarding_cases_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_onboarding_cases_lead_id_leads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['onboarding_templates.id'], name=op.f('fk_onboarding_cases_template_id_onboarding_templates'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_onboarding_cases_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_onboarding_cases'))
    )
    op.create_index(op.f('ix_onboarding_cases_lead_id'), 'onboarding_cases', ['lead_id'], unique=False)
    op.create_index(op.f('ix_onboarding_cases_template_id'), 'onboarding_cases', ['template_id'], unique=False)
    op.create_index(op.f('ix_onboarding_cases_tenant_id'), 'onboarding_cases', ['tenant_id'], unique=False)
    op.create_table('documents',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('document_request_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('file_name', sa.String(length=300), nullable=False),
    sa.Column('content_type', sa.String(length=150), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_request_id'], ['document_requests.id'], name=op.f('fk_documents_document_request_id_document_requests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_documents_lead_id_leads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_documents_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_documents_uploaded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_document_request_id'), 'documents', ['document_request_id'], unique=False)
    op.create_index(op.f('ix_documents_lead_id'), 'documents', ['lead_id'], unique=False)
    op.create_index(op.f('ix_documents_tenant_id'), 'documents', ['tenant_id'], unique=False)
    op.create_table('onboarding_case_steps',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('template_step_id', sa.UUID(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.Enum('TASK', 'DOCUMENT_REQUEST', name='onboarding_step_type', native_enum=False, length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'SKIPPED', name='onboarding_case_step_status', native_enum=False, length=20), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('document_request_id', sa.UUID(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['onboarding_cases.id'], name=op.f('fk_onboarding_case_steps_case_id_onboarding_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_request_id'], ['document_requests.id'], name=op.f('fk_onboarding_case_steps_document_request_id_document_requests'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_onboarding_case_steps_task_id_tasks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_step_id'], ['onboarding_template_steps.id'], name=op.f('fk_onboarding_case_steps_template_step_id_onboarding_template_steps'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_onboarding_case_steps_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_onboarding_case_steps'))
    )
    op.create_index(op.f('ix_onboarding_case_steps_case_id'), 'onboarding_case_steps', ['case_id'], unique=False)
    op.create_index(op.f('ix_onboarding_case_steps_document_request_id'), 'onboarding_case_steps', ['document_request_id'], unique=False)
    op.create_index(op.f('ix_onboarding_case_steps_task_id'), 'onboarding_case_steps', ['task_id'], unique=False)
    op.create_index(op.f('ix_onboarding_case_steps_tenant_id'), 'onboarding_case_steps', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_onboarding_case_steps_tenant_id'), table_name='onboarding_case_steps')
    op.drop_index(op.f('ix_onboarding_case_steps_task_id'), table_name='onboarding_case_steps')
    op.drop_index(op.f('ix_onboarding_case_steps_document_request_id'), table_name='onboarding_case_steps')
    op.drop_index(op.f('ix_onboarding_case_steps_case_id'), table_name='onboarding_case_steps')
    op.drop_table('onboarding_case_steps')
    op.drop_index(op.f('ix_documents_tenant_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_lead_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_request_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_onboarding_cases_tenant_id'), table_name='onboarding_cases')
    op.drop_index(op.f('ix_onboarding_cases_template_id'), table_name='onboarding_cases')
    op.drop_index(op.f('ix_onboarding_cases_lead_id'), table_name='onboarding_cases')
    op.drop_table('onboarding_cases')
    op.drop_index(op.f('ix_document_requests_tenant_id'), table_name='document_requests')
    op.drop_index(op.f('ix_document_requests_public_token'), table_name='document_requests')
    op.drop_index(op.f('ix_document_requests_lead_id'), table_name='document_requests')
    op.drop_table('document_requests')
    op.drop_index(op.f('ix_onboarding_template_steps_tenant_id'), table_name='onboarding_template_steps')
    op.drop_index(op.f('ix_onboarding_template_steps_template_id'), table_name='onboarding_template_steps')
    op.drop_table('onboarding_template_steps')
    op.drop_index(op.f('ix_onboarding_templates_tenant_id'), table_name='onboarding_templates')
    op.drop_table('onboarding_templates')
    # ### end Alembic commands ###
