"""milestone 6 proposals schema

Revision ID: e084e0d7c566
Revises: 11bc088dd65b
Create Date: 2026-07-15 04:32:31.825004

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'e084e0d7c566'
down_revision: str | None = '11bc088dd65b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposal_templates',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('terms', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_proposal_templates_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proposal_templates')),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_proposal_templates_tenant_name')
    )
    op.create_index(op.f('ix_proposal_templates_tenant_id'), 'proposal_templates', ['tenant_id'], unique=False)
    op.create_table('proposal_template_line_items',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['proposal_templates.id'], name=op.f('fk_proposal_template_line_items_template_id_proposal_templates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_proposal_template_line_items_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proposal_template_line_items'))
    )
    op.create_index(op.f('ix_proposal_template_line_items_template_id'), 'proposal_template_line_items', ['template_id'], unique=False)
    op.create_index(op.f('ix_proposal_template_line_items_tenant_id'), 'proposal_template_line_items', ['tenant_id'], unique=False)
    op.create_table('proposals',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'VIEWED', 'ACCEPTED', 'REJECTED', 'EXPIRED', name='proposal_status', native_enum=False, length=20), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('terms', sa.Text(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('public_token', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_by_name', sa.String(length=200), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_proposals_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_proposals_lead_id_leads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['proposal_templates.id'], name=op.f('fk_proposals_template_id_proposal_templates'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_proposals_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proposals')),
    sa.UniqueConstraint('public_token', name='uq_proposals_public_token')
    )
    op.create_index(op.f('ix_proposals_lead_id'), 'proposals', ['lead_id'], unique=False)
    op.create_index(op.f('ix_proposals_public_token'), 'proposals', ['public_token'], unique=False)
    op.create_index(op.f('ix_proposals_template_id'), 'proposals', ['template_id'], unique=False)
    op.create_index(op.f('ix_proposals_tenant_id'), 'proposals', ['tenant_id'], unique=False)
    op.create_table('proposal_line_items',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], name=op.f('fk_proposal_line_items_proposal_id_proposals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_proposal_line_items_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proposal_line_items'))
    )
    op.create_index(op.f('ix_proposal_line_items_proposal_id'), 'proposal_line_items', ['proposal_id'], unique=False)
    op.create_index(op.f('ix_proposal_line_items_tenant_id'), 'proposal_line_items', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proposal_line_items_tenant_id'), table_name='proposal_line_items')
    op.drop_index(op.f('ix_proposal_line_items_proposal_id'), table_name='proposal_line_items')
    op.drop_table('proposal_line_items')
    op.drop_index(op.f('ix_proposals_tenant_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_template_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_public_token'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_lead_id'), table_name='proposals')
    op.drop_table('proposals')
    op.drop_index(op.f('ix_proposal_template_line_items_tenant_id'), table_name='proposal_template_line_items')
    op.drop_index(op.f('ix_proposal_template_line_items_template_id'), table_name='proposal_template_line_items')
    op.drop_table('proposal_template_line_items')
    op.drop_index(op.f('ix_proposal_templates_tenant_id'), table_name='proposal_templates')
    op.drop_table('proposal_templates')
    # ### end Alembic commands ###
